quipucords/quipucords

README.rst

Most of the README content was written in https://github.com/quipucords/quipucords/pull/12. This is just to finish off the initial setup with the CI build and coverage info.

Add badging for build and coverage. Closes #2.

---

docs/swagger.yml

Add Swagger docs for network profiles

---

Makefile
quipucords/cli/auth/__init__.py
quipucords/cli/auth/add.py
quipucords/cli/auth/list.py
quipucords/cli/auth/tests.py
quipucords/cli/cli.py
quipucords/cli/clicommand.py
quipucords/cli/request.py
quipucords/cli/utils.py

Also a minor fix to the code coverage to omit some file like our test files and Django scaffolding we don't touch.

Add auth list command line and associated tests. Closes #29.

---

.github/issue_template.md
Makefile

- Changed Makefile all target to reference test-coverage instead of tests-coverage
- Spelling error in issue_template.md

Fix Makefile all target and spelling error in issue_template.md

---

quipucords/api/admin.py
quipucords/api/scanjob_views.py
quipucords/api/scanresults_model.py
quipucords/api/scanresults_serializer.py
quipucords/api/tests_scanresults.py

*Returns scan job info
*Returns results which are essentially basic row x column data
*Can augment in the future

Add a results endpoint for scans . Closes #41.

---

quipucords/api/networkprofile_serializer.py
quipucords/api/tests_networkprofile.py

Perform hosts input validation when creating/updating network profiles

---

.gitignore
Makefile
quipucords/api/fact_model.py
quipucords/api/fact_serializer.py
quipucords/api/fact_views.py
quipucords/api/tests_fact.py
quipucords/api/tests_hostcredential.py
quipucords/api/urls.py
quipucords/quipucords/settings.py

Create fact ingestion endpoint, models and view with tests

---

docs/swagger.yml
quipucords/api/admin.py
quipucords/api/fact_model.py
quipucords/api/report_model.py
quipucords/api/report_views.py
quipucords/api/tests_report.py
quipucords/api/urls.py

Create os reporting endpoint, models, views and test cases

---

docs/swagger.yml

facts REST API swagger

---

quipucords/api/fact_serializer.py
quipucords/fingerprinter/engine.py
quipucords/fingerprinter/tests_engine.py

Basic engine that processes facts

---

quipucords/api/__init__.py
quipucords/api/apps.py
quipucords/api/fact_collection_receiver.py
quipucords/api/fact_views.py
quipucords/api/fingerprint_model.py
quipucords/api/tests_report.py
quipucords/quipucords/settings.py

Moved fingerprint creation to an event model using a receiver

---

.coveragerc
Makefile
README.rst
elasticsearch/docker-compose.yml
quipucords/api/apps.py
quipucords/api/es_receivers.py
quipucords/api/tests_fact.py
quipucords/quipucords/settings.py
requirements.txt

Add receiver to pipe data to elasticsearch

---

quipucords/api/networkprofile_model.py
quipucords/api/networkprofile_views.py
quipucords/api/scanjob_model.py
quipucords/api/scanjob_views.py
quipucords/api/scanresults_model.py
quipucords/api/tests_scanresults.py

Improve relationship traversal for networkprofile and scan features

---

quipucords/api/fingerprint/serializer.py
quipucords/api/scanjob/serializer.py

- Add validation to FingerprintSerializer
- Fix validation of choice fields in ScanJobSerializer

Add validation to FingerprintSerializer

---

quipucords/api/es_receivers.py
quipucords/api/fact_collection_receiver.py

Add new facts to elasticsearch model

---

quipucords/api/hostcredential/serializer.py
quipucords/api/scanresults/serializer.py
quipucords/scanner/host.py
quipucords/scanner/utils.py
roles/cpu/tasks/main.yml
roles/date/tasks/main.yml
roles/virt/tasks/main.yml

- Remove host scan error messages from virt_num_guests and virt_num_running_guests

Update host scan so it sends integer for required integer fields

---

quipucords/api/es_receivers.py
quipucords/api/fact_collection_receiver.py

Removing logging for success case in the receivers

---

README.rst

Reference the ansible issue to work around max file limit

---

quipucords/quipucords/settings.py

Reverse the default to  avoid host key checking

---

quipucords/api/scanjob/model.py
quipucords/api/scanjob/serializer.py
quipucords/api/scanjob/tests_scanjob.py

Add systems_count, systems_scanned, fact_collection_id to the model

---

quipucords/scanner/host.py

Save incremental scan results

---

quipucords/scanner/discovery.py

Update the discover scan progress

---

quipucords/scanner/callback.py
quipucords/scanner/host.py
quipucords/scanner/tests_host.py
quipucords/scanner/utils.py
roles/host_done/tasks/main.yml

Remove grouping, run with free strategy, update results after single host completes

---

.coveragerc
README.rst

Add instructions to install sshpass

---

quipucords/api/scanjob/model.py
quipucords/api/scanjob/utils.py
quipucords/api/signals/scanjob_signal.py
quipucords/quipucords/settings.py
quipucords/scanner/manager.py

- Running jobs are load first, then pending
- Required manual env to specify hostname/port.
Closes #187 
Closes #137

Reload running or pending scan jobs are server restart

---

quipucords/api/messages.py
quipucords/api/networkprofile/serializer.py
quipucords/api/networkprofile/tests_networkprofile.py

Network profile creation now validates for a host credential that is not in the db

---

quipucords/api/hostcredential/serializer.py
quipucords/api/hostcredential/tests_hostcredential.py
quipucords/api/messages.py
quipucords/api/networkprofile/serializer.py
quipucords/api/networkprofile/tests_networkprofile.py

Previous behavior was a 500
Closes #210

Add logic to check for name conflicts with update/create host creds/network profiles

---

.travis.yml
Makefile
qpc/auth/tests_add.py
qpc/auth/tests_clear.py
qpc/auth/tests_edit.py
qpc/auth/tests_list.py
qpc/auth/tests_show.py
qpc/cli.py
qpc/messages.py
qpc/network/tests_add.py
qpc/network/tests_clear.py
qpc/network/tests_edit.py
qpc/network/tests_list.py
qpc/network/tests_show.py
qpc/request.py
qpc/scan/tests_cancel.py
qpc/scan/tests_list.py
qpc/scan/tests_pause.py
qpc/scan/tests_restart.py
qpc/scan/tests_show.py
qpc/scan/tests_start.py
qpc/server/__init__.py
qpc/server/commands.py
qpc/server/configure_host.py
qpc/server/tests_configure_host.py
qpc/utils.py

Add host configuration to the CLI

---

.travis.yml
qpc/utils.py
quipucords/scanner/host.py

Updated code to run with python 3.4

---

client/.gitignore
client/README.rst

Initial files for UI 
- gitignore to avoid branch collision
- initial ReadMe
- initial UI directory for build
closes #231

Add preparation files for UI integration

---

docs/swagger.yml
quipucords/api/credential/model.py
quipucords/api/credential/serializer.py
quipucords/api/credential/tests_credential.py
quipucords/api/messages.py

- Added a cred_type to credentials
- Specific validation rules added per type (hosts or vcenter)
- Tests
Closes #229

Add ability to have VCenter credentials

---

client/package.json
quipucords/client/index.html
quipucords/quipucords/settings.py

UI updates
- Initial package.json 
- Minor adjustment for the Django settings to allow serving static files. 
- Placeholder HTML
closes #236

Update Django serve settings for UI

---

qpc/utils.py

Added support to error method for non-dictionary objects (e.g. list or object)

---

client/package-lock.json
client/public/index.html
client/public/manifest.json
client/src/App.css
client/src/App.js
client/src/components/Content/Content.js
client/src/components/Masthead/Masthead.css
client/src/components/Masthead/Masthead.js
client/src/components/VerticalNavigation/VerticalNavigation.js
client/src/index.js
client/src/navItems.js

Initial setup for the base navigation in the UI. Completes a task in issue #240

Initial UI navigation layout

---

quipucords/api/fact/model.py
quipucords/api/fact/serializer.py
quipucords/api/fact/tests_fact.py
quipucords/api/models.py
quipucords/api/serializers.py
quipucords/api/signals/fact_collection_receiver.py
quipucords/api/tests_report.py
quipucords/scanner/host.py

Rename Fact to SystemFacts

---

quipucords/quipucords/settings.py
quipucords/quipucords/urls.py

Incremental update for static file settings
- Updated static serve from ```client``` directory instead of ```static```.
Partially updates issue #242 
Minimal confirmation/testing on API interaction. Recommend fully confirming API behavior before merging.

Django serve static file settings

---

docs/source/man.rst
docs/swagger.yml
qpc/cred/__init__.py
qpc/cred/add.py
qpc/cred/edit.py
qpc/cred/tests_add.py
qpc/cred/tests_edit.py
qpc/cred/utils.py
qpc/messages.py
quipucords/api/credential/model.py
quipucords/api/credential/serializer.py
quipucords/api/credential/tests_credential.py
quipucords/api/messages.py

CLI support for vcenter

---

docs/swagger.yml
quipucords/api/credential/tests_credential.py
quipucords/api/credential/view.py

Add cred_type filter to the credential list API

---

docs/source/man.rst
qpc/cred/list.py
qpc/cred/tests_list.py
qpc/messages.py

Add filter by type to credential API

---

docs/swagger.yml
quipucords/api/source/tests_source.py
quipucords/api/source/view.py

Add filter by source_type to list source API

---

docs/source/man.rst
qpc/cred/list.py
qpc/messages.py
qpc/source/__init__.py
qpc/source/list.py
qpc/source/tests_list.py

Add CLI support to filter sources by source_type

---

client/package.json
client/scripts/api.sh

Additions for running a mock API from Swagger.
- Additional NPM script
- Bash updates
Part of #240

Mock API updates

---

quipucords/api/messages.py
quipucords/api/source/serializer.py
quipucords/api/source/tests_source.py

Add validation for empty host array on both update and create

---

.dockerignore

Added initial ```.dockerignore``` in prep for excluding UI ```client```(build) directory
closes #290

Initial dockerignore

---

docs/swagger.yml
quipucords/api/scanjob/tests_scanjob.py
quipucords/api/scanjob/view.py

Add filtering by scan_type and status to list scanjob api

---

client/README.rst
client/package.json

- Starting ReadMe documentation. 
- NPM script for building Quipucords UI
part of issue #240 
@jlprevatt including you on the review for the ```baseline UI ReadMe``` feel free to ignore the ```package.json``` update

UI Documentation Updates

---

docs/source/man.rst
qpc/messages.py
qpc/scan/__init__.py
qpc/scan/list.py
qpc/scan/tests_list.py

Add filtering by type/status to CLI list scans

---

quipucords/api/connresults/model.py
quipucords/api/scanjob/tests_scanjob.py

Improve coverage on ScanJob

---

quipucords/scanner/__init__.py
quipucords/scanner/network/__init__.py
quipucords/scanner/network/connect.py
quipucords/scanner/network/connect_callback.py
quipucords/scanner/network/inspect.py
quipucords/scanner/network/inspect_callback.py
quipucords/scanner/network/tests_network_connect.py
quipucords/scanner/network/tests_network_inspect.py

Split ResultCallback handlers into connect and inspect

---

quipucords/scanner/network/inspect.py
roles/file_contents/tasks/main.yml

Import file_contents roles from rho

---

quipucords/scanner/network/inspect_callback.py

Remove extra line in inspect_callback.py

---

quipucords/scanner/network/inspect.py
roles/check_dependencies/tasks/main.yml
roles/jboss_eap/tasks/main.yml

This commit is only the Ansible role. I will submit the postprocessing separately.

Import jboss_eap role from rho to sonar

---

.gitignore
Makefile
quipucords/api/common/util.py
quipucords/api/fact/model.py
quipucords/api/fact/raw_fact_util.py
quipucords/api/fact/serializer.py
quipucords/api/fact/tests_fact.py
quipucords/api/fact/view.py
quipucords/api/fingerprint/model.py
quipucords/api/messages.py
quipucords/api/models.py
quipucords/api/scantasks/serializer.py
quipucords/api/serializers.py
quipucords/api/signals/fact_collection_receiver.py
quipucords/api/tests_report.py
quipucords/fingerprinter/__init__.py
quipucords/fingerprinter/tests_engine.py
quipucords/quipucords/settings.py
quipucords/scanner/job.py

Closes #329 
Code coverage will decrease on this because there is some code that needs to be refactored as part of #348.  I will tackle test coverage in #348.

Update facts endpoint to support multiple network sources (tolerate vcenter but ignore)

---

quipucords/scanner/network/inspect.py
roles/uname/tasks/main.yml

This copies over the rho uname role to quipucords.
Closes #362

Merge uname fingerprints from rho to sonar

---

docs/swagger.yml

Fixes existing validation errors and updates facts endpoint to match implementation

---

roles/check_dependencies/tasks/main.yml

Add missing tasks to check_dependencies role

---

Makefile
quipucords/scanner/job.py
quipucords/scanner/network/connect.py
quipucords/scanner/network/inspect.py
quipucords/scanner/task.py
quipucords/scanner/vcenter/connect.py
quipucords/scanner/vcenter/inspect.py
quipucords/scanner/vcenter/tests_vc_connect.py
quipucords/scanner/vcenter/tests_vc_inspect.py

- Consolidate get_facts/get_result in to task superclass
- Fix issues in Makefile
Closes #380

Add VCenter raw facts into the flow.

---

client/.eslintrc
client/package-lock.json
client/package.json

Initial eslint and prettier setup, also linted files. Closes #388

UI eslint and prettier, plus linted files

---

quipucords/api/fingerprint/model.py
quipucords/api/fingerprint/serializer.py
quipucords/fingerprinter/__init__.py
quipucords/fingerprinter/tests_engine.py

Remove duplicate systems based on bios id and subscription manager id

---

client/package-lock.json
client/package.json
client/scripts/swagger.js

- Serve the API documentation through a NPM script. 
- Restored the original ```start:quipucords``` NPM script, retained the docker version separately.
closes #395

UI Run API documentation

---

quipucords/scanner/network/processing/__init__.py

This makes sure the processors will be loaded and used in the post processing step.
Closes #400

Import eap in processing init so it gets loaded

---

client/.env.development
client/.env.production
client/src/services/credentialsApi.js
client/src/services/scansApi.js
client/src/services/sourcesApi.js

- Environment configs for dev and prod.
- Updated API calls around the return promise to make them similar to the Sources API call.
Closes #432

UI Add initial environment configs for builds

---

quipucords/scanner/network/inspect.py
roles/redhat_packages/tasks/main.yml

Cut out quite a few tasks that didn't actually do anything, so please double check that all the intended functionality is still here.
Closes #359

Copy redhat_packages from rho to sonar

---

client/src/redux/actions/credentialsActions.js
client/src/redux/actions/credentialsActions.test.js
client/src/redux/actions/factsActions.js
client/src/redux/actions/factsActions.test.js
client/src/redux/actions/reportsActions.js
client/src/redux/actions/reportsActions.test.js
client/src/redux/actions/scansActions.js
client/src/redux/actions/scansActions.test.js
client/src/redux/actions/sourcesActions.js
client/src/redux/actions/sourcesActions.test.js
client/src/redux/reducers/aboutReducer.js
client/src/redux/reducers/credentialsReducer.js
client/src/redux/reducers/credentialsReducer.test.js
client/src/redux/reducers/factsReducer.js
client/src/redux/reducers/factsReducer.test.js
client/src/redux/reducers/navigationBarReducer.js
client/src/redux/reducers/reportsReducer.js
client/src/redux/reducers/reportsReducer.test.js
client/src/redux/reducers/scansReducer.js
client/src/redux/reducers/scansReducer.test.js
client/src/redux/reducers/scansToolbarReducer.js
client/src/redux/reducers/sourcesReducer.js
client/src/redux/reducers/sourcesReducer.test.js
client/src/redux/reducers/sourcesToolbarReducer.js

Follow up updates for API and Redux refinement.
~~Input needed... should we apply the same change across the ```src/redux``` directory for Reducers as well.~~
updates #434

UI API refinement

---

client/scripts/api.sh

Minor patch for when there's a space within the Swagger file path.
closes #465

UI Build mock API Swagger file path fix

---

quipucords/scanner/vcenter/connect.py
quipucords/scanner/vcenter/tests_vc_connect.py

Catch exception if vcenter host cannot be reached

---

quipucords/api/fingerprint/model.py
quipucords/api/fingerprint/serializer.py
quipucords/api/source/model.py
quipucords/api/tests_report.py
quipucords/fingerprinter/__init__.py
quipucords/fingerprinter/tests_engine.py

Updated fingerprint to capture source of system fact value

---

quipucords/api/connresults/model.py
quipucords/api/connresults/serializer.py
quipucords/api/inspectresults/model.py
quipucords/api/inspectresults/serializer.py

Converted inspect/connection result value to a TextField

---

roles/jboss_brms/tasks/main.yml
roles/jboss_fuse_on_karaf/tasks/main.yml

Make sure data for postprocessing does not go through Jinja2

---

quipucords/scanner/network/inspect_callback.py
quipucords/scanner/network/tests_network_inspect.py

Drop internal_ facts that come from set_facts tasks

---

quipucords/api/common/serializer.py
quipucords/api/fingerprint/serializer.py
quipucords/api/inspectresults/serializer.py
quipucords/api/scanjob/tests_scanjob.py

Move CustomJSONField to a common class and use with the inspection result RawFact

---

docs/source/beta.rst

FYI - @jlprevatt - Info to help provide user CLI install steps.

Add documentation for quipucords beta CLI install. Closes #424.

---

client/package-lock.json
client/package.json
client/src/components/credentials/credentialListItem.js
client/src/components/credentials/credentials.js
client/src/components/credentials/credentialsEmptyState.js
client/src/components/credentials/credentialsToolbar.js
client/src/components/credentials/crendentialConstants.js
client/src/components/scans/scans.js
client/src/components/scans/scansToolbar.js
client/src/components/sources/sourceConstants.js
client/src/components/sources/sourceListItem.js
client/src/components/sources/sources.js
client/src/components/sources/sourcesToolbar.js
client/src/redux/reducers/credentialsToolbarReducer.js
client/src/redux/reducers/credentialsToolbarReducer.test.js
client/src/redux/reducers/index.js
client/src/routes.js
client/src/styles/entitlements/_scans.scss
client/src/styles/entitlements/_verticalNavigation.scss
client/src/styles/entitlements/_views.scss

Add Credentials View, add Sources compound expansion

---

client/src/components/scans/scanHostList.js
client/src/components/scans/scanListItem.js
client/src/components/scans/scanSourceList.js
client/src/components/scans/scans.js
client/src/components/sources/sourceCredentialsList.js
client/src/components/sources/sourceHostList.js
client/src/components/sources/sourceListItem.js
client/src/components/sources/sources.js
client/src/styles/entitlements/_views.scss

Add expansion views for list views

---

quipucords/api/credential/view.py
quipucords/api/fact/view.py
quipucords/api/report_views.py
quipucords/api/scanjob/view.py
quipucords/api/source/view.py

Modify handling of QPC_DISABLE_AUTHENTICATION so that unset and False both enable authentication
Closes #532

Modify handling of QPC_DISABLE_AUTHENTICATION

---

client/README.rst

Readme.rst minor adjustments around the installation.
closes #434 
@jlprevatt

UI Readme.rst Installation and Serving Updates

---

roles/check_dependencies/tasks/main.yml

Fix errors when check_dependencies tasks fail

---

roles/cpu/tasks/main.yml
roles/date/tasks/main.yml
roles/file_contents/tasks/main.yml
roles/subman/tasks/main.yml
roles/uname/tasks/main.yml
roles/virt_what/tasks/main.yml

Fix more playbook errors on failed tasks

---

README.rst
bin/timeout_ssh

Fix timeout_ssh for MacOS

---

docs/source/man.rst

Please review the changes. Tag-teaming on different sections to split the work is okay.
Major conceptual changes:
1. Changed first sentence (Rho artifact) from "discover and manage product entitlement metadata" to "inspect and report on" because I do not want to make any promises about function that we are not delivering. qpc doesn't really help you "manage" your entitlements directly (the "repair" step).
2. Rho was called a "discovery and inspection tool," a reference to the internal materials that described the proposed stages of entitlements reporting: discovery, inspection, deduplication, reconciliation... etc. If "discovery" is not going to be emphasized as an independent process, there's no need to keep the phrase "discovery and inspection" in the docs. So qpc (and Sonar) are now …

Edits ready for review: 489: sprint 14 changes to man.rst

---

Jenkinsfile

We have slaves now provided by the OpenStack jenkins plugin.

Use slave provided by the OpenStack jenkins plugin

---

quipucords/scanner/network/processing/eap.py
quipucords/scanner/network/processing/karaf.py
quipucords/scanner/network/processing/util.py
roles/check_dependencies/tasks/main.yml
roles/jboss_eap/tasks/main.yml
roles/jboss_fuse_on_karaf/tasks/main.yml

Also, combine duplicate Processor classes.
Closes #553 .

Add dependency to systemctl and chkconfig processors

---

client/.gitignore
client/scripts/api.sh

Additional checks around the mock api and Swagger. May have gone a little overboard, but this now brings container error handling in addition to the Swagger spec check that happens.
updates #534

UI Swagger build updates

---

client/src/components/credentials/credentialListItem.js
client/src/components/credentials/credentials.js
client/src/components/credentials/credentialsToolbar.js
client/src/components/scans/scanListItem.js
client/src/components/simpleTooltIp/simpleTooltip.js
client/src/components/sources/createScanDialog.js
client/src/components/sources/sourceListItem.js
client/src/components/sources/sources.js
client/src/styles/entitlements/_scans.scss
client/src/styles/entitlements/_views.scss

UI: Update list views per mocks, add tooltips

---

quipucords/scanner/network/processing/eap.py
quipucords/scanner/network/processing/karaf.py
quipucords/scanner/network/processing/process.py
quipucords/scanner/network/processing/test_karaf.py
quipucords/scanner/network/processing/tests_eap.py
roles/jboss_eap/tasks/main.yml
roles/jboss_fuse_on_karaf/tasks/main.yml

This is my fix for #515 , including all of its subsidiary bugs.
Closes #515 . Closes #564 . Closes #587 .Closes #588 . Closes #589 . Closes #591 . Closes #594 .

Fix several bugs related to postprocessing

---

client/src/components/confirmationModal/confirmationModal.js
client/src/components/createCredentialDialog/createCredentialDialog.js
client/src/components/credentials/credentials.js
client/src/components/scans/scans.js
client/src/components/sources/addSourceWizard.js
client/src/components/sources/createScanDialog.js
client/src/components/sources/sources.js
client/src/redux/reducers/confirmationModalReducer.js
client/src/redux/reducers/confirmationModalReducer.test.js
client/src/styles/entitlements/_overrides.scss
client/src/styles/entitlements/_views.scss

UI: add icon to confirm dialog, update views for inner scroll

---

Makefile
docs/source/man.rst
docs/swagger.yml
qpc/messages.py
qpc/source/__init__.py
qpc/source/add.py
qpc/source/edit.py
qpc/source/utils.py
quipucords/api/source/model.py
quipucords/api/source/serializer.py
quipucords/api/source/tests_source.py
quipucords/scanner/vcenter/tests_vc_utils.py
quipucords/scanner/vcenter/utils.py

Will need to set appropriate flags for vcenter now to run without cert validation.

Add ssl options for vcenter. Closes #504.

---

docs/source/beta.rst

@jlprevatt FYI
Minor update to beta doc to provide more setup configuration for Satellite or vCenter around SSL connection configuration.

Add ssl option beta info for vCenter and Satellite. Closes #615.

---

quipucords/api/scanjob/model.py
quipucords/api/scanjob/tests_scanjob.py
quipucords/api/scanjob/view.py
quipucords/api/scantasks/model.py
quipucords/api/scantasks/tests_scantask.py
quipucords/fingerprinter/__init__.py
quipucords/quipucords/settings.py
quipucords/scanner/job.py
quipucords/scanner/network/connect.py
quipucords/scanner/network/inspect.py
quipucords/scanner/network/inspect_callback.py
quipucords/scanner/network/tests_network_connect.py
quipucords/scanner/network/tests_network_inspect.py
quipucords/scanner/satellite/api.py
quipucords/scanner/satellite/connect.py
quipucords/scanner/satellite/inspect.py
quipucords/scanner/satellite/six.py
quipucords/scanner/satellite/tests_sat_inspect.py
quipucords/scanner/satellite/tests_sat_six.py
quipucords/scanner/satellite/utils.py
quipucords/scanner/vcenter/connect.py
quipucords/scanner/vcenter/inspect.py
quipucords/scanner/vcenter/tests_vc_connect.py
quipucords/scanner/vcenter/tests_vc_inspect.py

Closes #530 
```
INFO Job 11 - STATE UPDATE (created, inspect)
INFO "POST /api/v1/scans/ HTTP/1.1" 201 136
INFO Job 11 - STATE UPDATE (pending, inspect)
INFO Job 11 - STATE UPDATE (running, inspect)
INFO Job 11 - Includes the following incomplete tasks: 33, 34, 35, 36, 37, 38
INFO Task 33 - STATE UPDATE (running, connect, vcenter, VSource)
INFO Task 33 - INITIAL VCENTER CONNECT STATS. Stats: elapsed_time=2s, systems_count=105, systems_scanned=0, systems_failed=0
INFO Task 33 - COMPLETION STATS. Stats: elapsed_time=2s, systems_count=105, systems_scanned=0, systems_failed=0
INFO Task 33 - STATE UPDATE (completed, connect, vcenter, VSource)
INFO Task 34 - STATE UPDATE (running, connect, satellite, SSource)
INFO Task 34 - INITIAL STATELLITE STATS Stats: elapsed_time=0s, systems_count=225, …
```

Improve info log level to produce meaningful state

---

client/src/common/helpers.js
client/src/components/createCredentialDialog/createCredentialDialog.js
client/src/components/credentials/credentialListItem.js
client/src/components/credentials/credentials.js
client/src/components/credentials/crendentialConstants.js
client/src/components/scans/scanConstants.js
client/src/components/scans/scanListItem.js
client/src/components/scans/scans.js
client/src/components/simpleTooltIp/simpleTooltip.js
client/src/components/sources/sourceConstants.js
client/src/components/sources/sourceListItem.js
client/src/components/sources/sources.js
client/src/components/sources/sourcesToolbar.js
client/src/redux/actions/scansActions.js
client/src/styles/entitlements/_overrides.scss
client/src/styles/entitlements/_views.scss

UI: update views, sort/filters per mocks

---

docs/swagger.yml
qpc/cred/clear.py
quipucords/api/common/pagination.py
quipucords/api/credential/view.py
quipucords/quipucords/settings.py

@quipucords/ux-ui  This PR also adds the ordered filtering capability and you can specify `page_size`.

Fixes clear all due to paging and adds ordering. Closes #635 #631.

---

quipucords/api/scanjob/serializer.py
quipucords/api/scantasks/model.py
quipucords/scanner/network/connect_callback.py
quipucords/scanner/network/inspect_callback.py
quipucords/scanner/network/processing/process.py
quipucords/scanner/network/processing/tests_process.py
quipucords/scanner/satellite/connect.py
quipucords/scanner/satellite/inspect.py

Enhance error logging to capture task context

---

roles/subman/tasks/main.yml

Make subman.has_facts_file into a boolean

---

quipucords/api/scanjob/model.py
quipucords/api/scantasks/model.py
quipucords/scanner/network/inspect.py
quipucords/scanner/network/inspect_callback.py
quipucords/scanner/network/tests_network_inspect.py

Closes #659 
Closes #671 
Closes #672

Fix error handling for ansible errors, resume of paused scans, failure stats

---

docs/swagger.yml

Add facts/id swagger doc

---

docs/source/man.rst

Man page updates for report cli

---

client/.env.development
client/.env.production
client/README.rst
client/package.json
client/scripts/api.sh
client/src/redux/store.js
client/src/services/userService.js

- Relocated the Redux console logging setting to the  "gitignored" ```.env.local``` file, aimed at letting a dev alter it without having to check it back in.
- Corrects the issue around running Docker through UI build with port updates
- Spoof auth token fixes, which appear as an inability to get past the "login failed" alerts. Corrected so it consistently bypasses this during local development
updates #534 
closes #686

UI: ReadMe & Testing Build

---

qpc/source/add.py
quipucords/api/credential/model.py
quipucords/scanner/network/connect.py

Ensure ordering is preserved from CLI

---

.github/issue_template.md

Adds sample list of items to verify to meet acceptance criteria.
Closes https://github.com/quipucords/quipucords/issues/710

Add acceptance criteria to issue template

---

quipucords/scanner/network/connect_callback.py
quipucords/scanner/network/tests_network_connect.py

Retry failed hosts

---

client/.gitignore
client/package.json
client/scripts/postinstall.sh
quipucords/quipucords/templates/base.html
quipucords/quipucords/templates/registration/login.html

UI: Update login dialog to RCUE styling

---

quipucords/scanner/network/inspect.py

Restrict results query to current task

---

quipucords/scanner/job.py
quipucords/scanner/vcenter/utils.py

- Fix vcenter SSL handling
- Catch unexpected exceptions from a taska and mark job as failed.
Closes #720

Various fixes

---

quipucords/api/connresults/model.py
quipucords/api/connresults/serializer.py
quipucords/api/inspectresults/model.py
quipucords/api/inspectresults/serializer.py
quipucords/api/scanjob/model.py
quipucords/api/scanjob/serializer.py
quipucords/api/scanjob/tests_scanjob.py
quipucords/api/scanjob/view.py
quipucords/scanner/job.py
quipucords/scanner/network/connect.py
quipucords/scanner/network/inspect.py
quipucords/scanner/network/tests_network_connect.py
quipucords/scanner/network/tests_network_inspect.py
quipucords/scanner/satellite/connect.py
quipucords/scanner/satellite/inspect.py
quipucords/scanner/satellite/tests_sat_connect.py
quipucords/scanner/satellite/tests_sat_factory.py
quipucords/scanner/satellite/tests_sat_inspect.py
quipucords/scanner/satellite/tests_sat_six.py
quipucords/scanner/satellite/tests_sat_utils.py
quipucords/scanner/vcenter/connect.py
quipucords/scanner/vcenter/inspect.py
quipucords/scanner/vcenter/tests_vc_connect.py
quipucords/scanner/vcenter/tests_vc_inspect.py
quipucords/scanner/vcenter/tests_vc_utils.py

Move results into job model

---

quipucords/api/source/tests_source.py

Patch tests & fix post errors.

Fix source test throwing exception. Closes #738

---

bin/qpc

Add a Python version check in bin/qpc

---

docs/swagger.yml
quipucords/api/source/tests_source.py
quipucords/api/source/view.py

Add most recent connection task data to a source. Closes #610.

---

.gitignore

Initial adds to ignore for built/compiled UI assets
updates #690 relates to #764

Add ignore for built UI resources

---

Jenkinsfile

Ran this update through successfully on Jenkins.

Build client during container image Jenkins Job. Closes #764.

---

client/src/redux/actions/scansActions.js
client/src/redux/actions/tests/scansActions.test.js
client/src/redux/reducers/scansReducer.js
client/src/redux/reducers/tests/scansReducer.test.js

UI: Add scan action and reducer tests

---

docs/source/man.rst
qpc/scan/__init__.py
qpc/scan/edit.py
qpc/scan/list.py
qpc/scan/tests_scan_edit.py
qpc/scan/tests_scan_list.py
qpc/scan/utils.py

fixed scan edit
fixed scan list
added tests
corrected URI & utils issue

Updated man page, added scan edit tests, fixed URI. Part of #698

---

quipucords/api/scan/view.py
quipucords/api/urls.py
quipucords/api/views.py

Also, add ability to order and filter.

Move /scans/{id}/jobs to an api_view

---

qpc/cli.py
qpc/messages.py
qpc/scan/__init__.py
qpc/scan/commands.py
qpc/scan/pause.py
qpc/scan/restart.py
qpc/scan/start.py
qpc/scan/status.py
qpc/scan/tests_scan_cancel.py
qpc/scan/tests_scan_pause.py
qpc/scan/tests_scan_restart.py
qpc/scan/tests_scan_start.py
qpc/scan/tests_scan_status.py

- scan start & tests
- scan restart & tests
- scan pause & tests
- scan cancel & tests
- scan status & tests
TODO:
-scan job (list scan jobs for a scan)

Update Scan Job CLI. Part of #700

---

client/src/components/scans/scanListItem.js
client/src/components/sources/sourceHostList.js
client/src/components/sources/sourceListItem.js
client/src/components/sources/sources.js

Updates #690 
Shows correct scan status/time
Shows correct hosts when expanding a source

UI: update scans list and source list with data

---

docs/source/beta.rst

Please review the changes in the second major edit to beta.rst. 
Known final cleanup to-dos:
- figuring out best formatting (esp. code examples) for readthedocs HTML output and the PDF build you can launch from that. There are a couple of sections in this edit where I did some tagging experiments to compare in the new build.
- qpc server install steps still tbd (at least, in my branch)
- need contact URL for pilot feedback--Dan is working on it
- reading the whole thing One More Time to catch errors, typos, etc.
Closes #766

Edits ready for review: 766 beta.rst edits round 2

---

docs/source/man.rst
qpc/messages.py
qpc/scan/job.py
qpc/scan/tests_scan_job.py

Added args validation & messages/ added tests
Removed unnecessary code
Updated man page

Made scan name optional for scan job. Closes #811

---

docs/source/man.rst

Move clearing scans to the scan section

---

quipucords/api/scanjob/model.py
quipucords/api/scantasks/model.py
quipucords/scanner/network/inspect_callback.py

Add elapsed time to the job/task info prefix

---

docs/source/beta.rst

FYI @quipucords/documentation 
Provides info for word-smithing.

Add information for obtaining the server container image. Closes #426.

---

quipucords/api/credential/tests_credential.py
quipucords/api/credential/view.py
quipucords/api/messages.py

Fix CLI presentation for delete cred

---

roles/jboss_eap5/tasks/main.yml

Tasks were chosen by installing EAP 5 on a test server and looking for
characteristics that could identify it.
Closes #848 .

Add an Ansible role to detect JBoss EAP 5

---

qpc/clicommand.py
qpc/request.py
qpc/utils.py

For example, this is what the beginning of the log after running Kevan's setup script looks like:
```INFO:qpc:Method: "POST", Command: "qpc scan add", URL: "http://127.0.0.1:8000/api/v1/scans/", Payload: "{'name': 'NMixScan', 'sources': [1, 8, 5], 'scan_type': 'inspect', 'options': {'max_concurrency': 50}}", Status Code: "201"
INFO:qpc:Method: "POST", Command: "qpc cred add", URL: "http://127.0.0.1:8000/api/v1/credentials/", Payload: "{'name': 'VCreds', 'cred_type': 'vcenter', 'username': 'chambrid', 'ssh_keyfile': None, 'password': 'Redhat2!', 'ssh_passphrase': None, 'become_password': None}", Status Code: "201"
INFO:qpc:Method: "POST", Command: "qpc cred add", URL: "http://127.0.0.1:8000/api/v1/credentials/", Payload: "{'name': 'SCreds5', 'cred_type': 'satellite', 'username': 'admin', …
```

Restructured logging. Closes #813

---

docs/swagger.yml
quipucords/api/common/util.py
quipucords/api/messages.py
quipucords/api/models.py
quipucords/api/scan/model.py
quipucords/api/scan/serializer.py
quipucords/api/scan/tests_scan.py
quipucords/api/scanjob/model.py
quipucords/api/scanjob/serializer.py
quipucords/api/scanjob/tests_scanjob.py
quipucords/api/source/view.py
quipucords/scanner/network/inspect.py
quipucords/scanner/network/tests_network_inspect.py
quipucords/scanner/test_util.py

Add extended product search options to ScanOptions

---

docs/source/man.rst
qpc/scan/add.py
qpc/scan/edit.py
qpc/scan/tests_scan_add.py
qpc/scan/tests_scan_edit.py
qpc/scan/utils.py
quipucords/api/models.py
quipucords/api/scan/model.py
quipucords/api/scan/serializer.py
quipucords/api/scan/tests_scan.py
quipucords/api/scanjob/model.py
quipucords/api/scanjob/tests_scanjob.py
quipucords/api/source/view.py
quipucords/scanner/network/connect.py
quipucords/scanner/network/inspect.py
quipucords/scanner/test_util.py

Make ScanOptions optional

---

quipucords/api/scan/model.py
quipucords/api/scanjob/tests_scanjob.py

Added more test cases.
Closes #891

Fix issue with enabled_extended_product_search equal None

---

docs/source/man.rst

Please review the changes for this edit. Thanks.
Closes #834

834: man.rst changes for edit 2

---

client/src/components/mastheadOptions/mastheadOptions.js

UI: Log out copy fix

---

client/src/components/addSourceWizard/addSourceWizard.js
client/src/components/addSourceWizard/addSourceWizardConstants.js
client/src/components/addSourceWizard/addSourceWizardStepThree.js
client/src/components/addSourceWizard/addSourceWizardStepTwo.js
client/src/components/scans/scanListItem.js
client/src/components/scans/scans.js
client/src/redux/reducers/addSourceWizardReducer.js
client/src/redux/reducers/tests/addSourceWizardReducer.test.js
client/src/services/sourcesService.js
client/src/styles/entitlements/_overrides.scss

Only allow selection of correct credential types
Don’t close the wizard on error
Update results page
Add scan name to action notifications

UI: wizard fixes

---

client/src/components/addSourceWizard/addSourceWizardStepOne.js
client/src/components/addSourceWizard/addSourceWizardStepTwo.js
client/src/components/createCredentialDialog/createCredentialDialog.js
client/src/components/sources/sources.js
client/src/constants/apiConstants.js
client/src/redux/reducers/sourcesReducer.js
client/src/redux/reducers/tests/sourcesReducer.test.js
client/src/services/sourcesService.js

Implement Delete source
Update sources list after Add, Edit, Delete
Do no lost updates in wizard when a new credential is added
Fixes #827

UI: Fixes in source view and wizard

---

quipucords/scanner/network/inspect_callback.py

Fix counting issue with unreachable hosts during inspection

---

quipucords/api/scan/tests_scan.py
quipucords/api/scan/view.py

Add status_details to recent scan

---

quipucords/scanner/network/connect.py

Always reset stats are restarting scan.

---

quipucords/fingerprinter/__init__.py
quipucords/fingerprinter/tests_engine.py

Use vCenter cpu cores in merge with network data if possible

---

client/src/common/helpers.js
client/src/components/scans/scanJobsList.js
client/src/components/scans/scanListItem.js
client/src/components/sources/sourceListItem.js
client/src/components/sources/sources.js
client/src/redux/reducers/addSourceWizardReducer.js
client/src/redux/reducers/credentialsReducer.js
client/src/redux/reducers/factsReducer.js
client/src/redux/reducers/reportsReducer.js
client/src/redux/reducers/scansReducer.js
client/src/redux/reducers/sourcesReducer.js
client/src/redux/reducers/userReducer.js

UI: Update error message determination methods.

---

client/src/components/credentials/credentials.js
client/src/components/scans/scans.js
client/src/components/sources/sources.js
client/src/components/viewToolbar/viewToolbar.js
client/src/styles/entitlements/_views.scss

UI: Add last refresh time to views.

---

quipucords/api/fingerprint/model.py
quipucords/api/fingerprint/serializer.py
quipucords/api/fingerprint/tests_fingerprint_model.py
quipucords/api/report/renderer.py
quipucords/api/report/tests_report.py
quipucords/fingerprinter/__init__.py
quipucords/fingerprinter/tests_engine.py

- JSON includes sources field for each system.  
- CSV contains column for network/vcenter/satellite and source names.
Closes #952

Add source information into summary report

---

quipucords/api/fingerprint/model.py
quipucords/fingerprinter/__init__.py

Add BARE_METAL constant to SystemFingerprint model

Add a constant for bare_metal 

---

client/src/components/scans/scanJobsList.js
client/src/components/scans/scans.js
client/src/components/sources/createScanDialog.js

UI: Start scans when they are created

---

client/src/components/addSourceWizard/addSourceWizardDropdownSelect.js
client/src/components/addSourceWizard/addSourceWizardStepOne.js
client/src/components/addSourceWizard/addSourceWizardStepThree.js
client/src/components/addSourceWizard/addSourceWizardStepTwo.js
client/src/components/app.js
client/src/styles/entitlements/_views.scss

Logout auth
* Hide the menu system when a user hits the back button
Add source wizard
* Port placeholder copy updated
* Style updates for the credentials dropdown
* Fix for undefined display for port, with singleHostPort display
* Fix for undefined ID being submitted with new sources
* Clean up
Note:
* Discovered additional issues around how the credentials are reset when changing `sourceType`, those should be handled in a follow up PR
* [Filtered the props on the Dropdown component since it allowed the maximum number of props to be passed through](https://react-bootstrap.github.io/components/dropdowns/#btn-dropdowns-props-dropdown)
updates #839 fixes #910

UI: Logout authentication display, and add source wizard updates

---

quipucords/fingerprinter/__init__.py
quipucords/fingerprinter/tests_engine.py

Apply new rules to computer system_creation_date

---

docs/source/getting_started.rst
docs/source/man.rst
docs/swagger.yml
qpc/messages.py
qpc/source/__init__.py
qpc/source/add.py
qpc/source/edit.py
qpc/source/tests_source_add.py
qpc/source/utils.py
quipucords/api/source/model.py
quipucords/api/source/serializer.py
quipucords/api/source/tests_source.py
quipucords/scanner/satellite/api.py
quipucords/scanner/satellite/connect.py
quipucords/scanner/satellite/factory.py
quipucords/scanner/satellite/inspect.py
quipucords/scanner/satellite/tests_sat_connect.py
quipucords/scanner/satellite/tests_sat_factory.py
quipucords/scanner/satellite/tests_sat_inspect.py
quipucords/scanner/satellite/tests_sat_utils.py
quipucords/scanner/satellite/utils.py

@quipucords/ux-ui 
FYI, this removes the need to specify a satellite version.

Detect satellite version. Closes #767.

---

docs/source/index.rst

Closes #961 
Some changes to make index.rst intro text wording more closely match the changes in beta.rst and man.rst.

961: making index more closely match beta and man text

---

quipucords/api/scanjob/model.py
quipucords/api/scanjob/view.py

- Change order of updating and killing job
- Attempt a retry if update of db fails
Closes #954

Several changes to avoid db lock issues

---

quipucords/api/credential/model.py
quipucords/api/source/model.py
quipucords/scanner/job.py

Add additional context logging to a job.

---

client/src/components/scans/scanConstants.js
client/src/components/sources/sourceConstants.js
client/src/components/viewToolbar/viewToolbar.js
client/src/styles/entitlements.scss
client/src/styles/entitlements/_overrides.scss

UI: remove unsupported sort and filter fields

---

client/src/components/addSourceWizard/addSourceWizard.js
client/src/components/app.js
client/src/components/createCredentialDialog/createCredentialDialog.js
client/src/components/credentials/credentials.js
client/src/components/refreshTimeButton/refreshTimeButton.js
client/src/components/scans/scans.js
client/src/components/sources/sources.js
client/src/components/viewToolbar/viewToolbar.js

- Both CreateCredentialDialogs were being shown simultaneously
- Move forceUpdate to only redraw the refresh button not entire view
Updates #839

UI: use common createCredentialDialog, refreshTimeButton

---

client/src/components/scans/scanHostList.js
client/src/components/scans/scanJobsList.js
client/src/components/scans/scanListItem.js
client/src/components/scans/scanSourceList.js
client/src/components/scans/scans.js
client/src/components/sources/sourceCredentialsList.js
client/src/components/sources/sourceHostList.js
client/src/components/sources/sourceListItem.js
client/src/components/sources/sources.js

UI: Refresh expansion area data on view refresh

---

client/src/components/sources/sourceHostList.js
client/src/components/sources/sourceListItem.js

UI: Fix to get task_results from all connection_results

---

client/src/components/sources/sourceHostList.js

Swagger structure is incorrect. Put back to prod/stage results format

UI: Undo change to  get task_results from connection_results

---

client/src/components/addSourceWizard/addSourceWizard.js
client/src/components/addSourceWizard/addSourceWizardStepTwo.js

What is it
* Fix for network hosts regex
* Initial automation for setting up a connection scan
What's not in the PR
* Fixes and filters for connection vs inspection scan within the Scans view.
updates #839

UI: Add source wizard fixes

---

quipucords/scanner/network/processing/__init__.py
quipucords/scanner/network/processing/ifconfig.py
roles/ifconfig/tasks/main.yml

Move ifconfig ip address to post processing class

---

client/src/components/credentials/credentials.js
client/src/components/scans/scanConstants.js
client/src/components/scans/scans.js
client/src/components/sources/sourceConstants.js
client/src/components/sources/sources.js

UI: Add sort by most recent for scans and sources

---

client/src/components/addSourceWizard/addSourceWizard.js
client/src/redux/actions/sourcesActions.js
client/src/services/sourcesService.js

* Fix for firing quick connection scan
updates #1017

UI: Add source wizard quick connection scan

---

client/scripts/api.sh

* Update related to new Django routing
updates #1017

UI: Fix staging docker

---

docs/swagger.yml
quipucords/api/credential/view.py
quipucords/api/scan/view.py
quipucords/api/source/view.py

FYI @quipucords/ux-ui 
Adds feasible requested partial search matches.

Add ability to perform partial search matches against specific resource fields. Closes #923.

---

quipucords/scanner/satellite/six.py
quipucords/scanner/satellite/tests_sat_six.py

Add process pool to satellite 6.1

---

client/package.json
client/src/common/helpers.js
client/src/components/confirmationModal/confirmationModal.js
client/src/components/credentials/credentialListItem.js
client/src/components/listStatusItem/listStatusItem.js
client/src/components/scans/scanJobsList.js
client/src/components/scans/scanListItem.js
client/src/components/scans/scanSourceList.js
client/src/components/scans/scans.js
client/src/components/simpleTooltIp/simpleTooltip.js
client/src/components/sources/sourceCredentialsList.js
client/src/components/sources/sourceListItem.js
client/src/components/sources/sources.js
client/src/components/viewToolbar/viewToolbar.js
client/src/redux/actions/scansActions.js

What's included
* Build, add clean up to staging start up
* Scans service minor missing param
* Export as default clean up, update imports
* Confirmation modal state-to-props clean up
* Clean up, let vs const
* Aria label fix
* Animated spinner for scans view
updates #1017

UI: Build, animation for scans, & clean up

---

docs/swagger.yml
quipucords/api/inspectresults/model.py

Remove array from response body of job results

---

client/src/components/credentials/crendentialConstants.js
client/src/components/scans/scanConstants.js
client/src/components/sources/sourceConstants.js
client/src/redux/reducers/viewOptionsReducer.js

UI: Add filtering by names

---

docs/swagger.yml
quipucords/api/scanjob/tests_scanjob.py
quipucords/api/scanjob/view.py

Remove jobs/{id}/results API

---

client/src/components/scans/scanHostList.js
client/src/components/scans/scanJobsList.js
client/src/components/scans/scanListItem.js
client/src/components/sources/sourceCredentialsList.js
client/src/components/sources/sourceHostList.js
client/src/components/sources/sourceListItem.js
client/src/styles/entitlements/_views.scss

Updated the loading indicators for expansions to be in the expand area
Updated error messages in expand areas to be a single line
Fixes a portion of #1030 
@bclarhk

UI: Fix for showing correct hosts in expanded views

---

client/src/components/app.js
client/src/components/mergeReportsDialog/mergeReportsDialog.js
client/src/components/sources/createScanDialog.js
client/src/components/sources/sourceListItem.js
client/src/components/toastNotificationList/toastNotificatinsList.js

* Minor fix for naming on normalizeCount
* Component mapStateToProps const conversion
* Disabled merged scans button when less than 2 valid scans

UI: Helper & component mapStateToProps conversion updates

---

docs/swagger.yml
quipucords/api/source/tests_source.py
quipucords/api/source/view.py

Add source counts to the last connection job

---

quipucords/scanner/satellite/utils.py

Change 404 to an info log for satellite 5

---

client/.gitignore
client/package.json
client/scripts/api.sh

* NPM API clean up script
* Persist data across staging and prod containers
updates #1017

UI: Build, staging & prod data persistence

---

quipucords/api/credential/view.py
quipucords/api/scan/view.py
quipucords/api/source/view.py

http://django-filter.readthedocs.io/en/latest/ref/filters.html#distinct

Add distinct to filter to remove duplicates. Closes #1080.

---

docs/swagger.yml
quipucords/api/common/util.py
quipucords/api/scan/tests_scan.py
quipucords/api/scanjob/model.py
quipucords/api/scanjob/tests_scanjob.py
quipucords/api/source/view.py

Add how recent scan job (scans)  and connection (sources) are computed

---

quipucords/fingerprinter/__init__.py

Add debug logging for fingerprints

---

quipucords/fingerprinter/jboss_eap.py

Filter wildfly and jboss-as from versions.

---

docs/swagger.yml

Swagger for token endpoint

---

docs/swagger.yml

Update swagger for user.  Issue 1097.

---

docs/swagger.yml
quipucords/api/messages.py
quipucords/api/scanjob/tests_scanjob.py
quipucords/api/scanjob/view.py

Order and filter connection and inspection results. Closes #1101.

---

quipucords/scanner/network/processing/__init__.py
quipucords/scanner/network/processing/tests_yum.py
quipucords/scanner/network/processing/yum.py
roles/redhat_packages/tasks/main.yml

```
"yum_enabled_repolist": [
{
"repo": "!jb-eap-7-for-rhel-7-server-rpms/7Server/x86_64",
"name": "JBoss Enterprise Applicat"
},
{
"repo": "!rhel-7-server-rpms/7Server/x86_64",
"name": "Red Hat Enterprise Linux"
},
{
"repo": "!rhel7-cdn-internal/7Server/x86_64",
"name": "RHEL 7 - x86_64"
},
{
"repo": "!rhel7-cdn-internal-extras/7Server/x86_64",
"name": "RHEL 7 - x86_64"
},
{
"repo": "!rhel7-cdn-internal-optional/7Server/x86_64",
"name": "RHEL 7 - x86_64"
}
]
```

Gather enabled yum repo lists. Closes #1084.

---

docs/swagger.yml
quipucords/api/scanjob/tests_scanjob.py
quipucords/api/scanjob/view.py

Filter inspection and connection results by source identifier. Closes #1118.

---

docs/swagger.yml

Swagger updates for source

---

client/src/components/scans/scanHostList.js
client/src/components/sources/sourceListItem.js
client/src/styles/entitlements/_views.scss

UI: Update to use server filter/sort for expanded hosts lists, use paging where possible

---

docs/swagger.yml

Swagger updates for scan job

---

client/src/components/credentials/credentialListItem.js
client/src/components/scanHostList/scanHostList.js
client/src/components/scans/scanListItem.js
client/src/components/sources/sourceListItem.js
client/src/styles/entitlements/_views.scss

UI: Remove pager buttons in lieu of a show more link, styling adjustments

---

docs/source/encryption.rst

1133: edits to encryption.rst

---

docs/swagger.yml

Update swagger reference for details report.

---

docs/source/scanning.rst

1136: Edits plus new point of failure info for scanning.rst

---

install/roles/docker/tasks/main.yml
install/roles/qpc_server/tasks/main.yml

Ensure the packages directory exist so a file can be downloaded to it.

---

docs/source/authentication.rst

Please review the changes to authentication.rst. Thanks.
Closes #1148

1148: Edits for authentication.rst

---

client/package.json
client/src/components/scanHostList/scanHostList.js
client/src/styles/entitlements/_views.scss

UI: Use infinite scroll for host lists.

---

client/src/components/credentials/credentialListItem.js
client/src/styles/entitlements/_views.scss

UI: Update Credentials list view alignment for consistency

---

client/src/components/scans/scanJobsList.js
client/src/components/scans/scanListItem.js

UI: Allow download of reports for failed scans with report IDs.

---

quipucords/fingerprinter/jboss_brms.py
quipucords/scanner/network/processing/brms.py

Handle Drools versions

---

client/src/common/helpers.js
client/src/components/credentials/__tests__/__snapshots__/credentialsEmptyState.test.js.snap
client/src/components/credentials/__tests__/__snapshots__/credentialsListItem.test.js.snap
client/src/components/credentials/__tests__/credentialsEmptyState.test.js
client/src/components/credentials/__tests__/credentialsListItem.test.js
client/src/components/credentials/credentialListItem.js
client/src/components/mergeReportsDialog/__tests__/__snapshots__/mergeReportsDialog.test.js.snap
client/src/components/mergeReportsDialog/__tests__/mergeReportsDialog.test.js
client/src/components/scans/__tests__/__snapshots__/scanJobsList.test.js.snap
client/src/components/scans/__tests__/__snapshots__/scanListItem.test.js.snap
client/src/components/scans/__tests__/__snapshots__/scanSourceList.test.js.snap
client/src/components/scans/__tests__/scanJobsList.test.js
client/src/components/scans/__tests__/scanListItem.test.js
client/src/components/scans/__tests__/scanSourceList.test.js
client/src/components/scans/scanListItem.js
client/src/components/scans/scanSourceList.js
client/src/components/sources/__tests__/__snapshots__/createScanDialog.test.js.snap
client/src/components/sources/__tests__/__snapshots__/sourceCredentialsList.test.js.snap
client/src/components/sources/__tests__/__snapshots__/sourcesEmptyState.test.js.snap
client/src/components/sources/__tests__/__snapshots__/sourcesListItem.test.js.snap
client/src/components/sources/__tests__/createScanDialog.test.js
client/src/components/sources/__tests__/sourceCredentialsList.test.js
client/src/components/sources/__tests__/sourcesEmptyState.test.js
client/src/components/sources/__tests__/sourcesListItem.test.js
client/src/components/sources/createScanDialog.js
client/src/components/sources/sourceCredentialsList.js
client/src/components/sources/sourceListItem.js
client/src/index.js

Apply unit tests to view components.
* Unit test warning fix for Merge Reports dialog
* Credential view component snapshot tests
* Sources, createScanDialog snapshot test & logic update
* Sources, sourceCredentialsList snapshot test & stateless update
Remaining
updates #1135

UI: Unit testing and related view component updates

---

docs/swagger.yml
quipucords/api/common/util.py
quipucords/api/scan/tests_scan.py
quipucords/api/scanjob/model.py
quipucords/api/scanjob/serializer.py
quipucords/api/scanjob/tests_scanjob.py
quipucords/api/scantasks/model.py
quipucords/api/scantasks/serializer.py
quipucords/api/scantasks/tests_scantask.py
quipucords/api/source/tests_source.py
quipucords/api/source/view.py
quipucords/scanner/network/connect.py
quipucords/scanner/network/connect_callback.py
quipucords/scanner/network/inspect.py
quipucords/scanner/network/inspect_callback.py
quipucords/scanner/satellite/api.py
quipucords/scanner/vcenter/tests_vc_inspect.py

Break unreachable hosts out from failed hosts on network scan

---

quipucords/fingerprinter/jboss_eap.py
quipucords/fingerprinter/tests_product_eap.py
quipucords/scanner/network/processing/eap.py
quipucords/scanner/network/processing/test_eap.py

Deduplicate EAP versions

---

client/src/common/helpers.js
client/src/components/listStatusItem/__tests__/listStatusItem.test.js
client/src/components/listStatusItem/listStatusItem.js
client/src/components/scans/scanListItem.js
client/src/components/sources/__tests__/__snapshots__/sourcesListItem.test.js.snap
client/src/components/sources/sourceListItem.js
client/src/styles/entitlements/_views.scss

UI: Support for differentiation of unreachable hosts

---

quipucords/scanner/network/processing/brms.py

Add flag to allow any RC from locate

---

client/src/components/scans/scanListItem.js

UI: Show source associated with system in scans results lists.

---

quipucords/fingerprinter/jboss_fuse.py

Make constant names match values in `jboss_fuse.py`

---

quipucords/api/report/tests_report.py
quipucords/api/report/view.py

Return 424 for case where FC exists but no report

---

client/README.rst

Patternfly reference added
updates #1195

UI: ReadMe update

---

qpc.spec
qpc/source/__init__.py

Allow true/false for boolean values in source options

---

qpc.spec
qpc/source/edit.py
qpc/source/tests_source_edit.py

enable editing disable-ssl for a source #1212

---

quipucords/api/scanjob/model.py
quipucords/api/scanjob/tests_scanjob.py
quipucords/api/signals/scanjob_signal.py
quipucords/scanner/job.py
quipucords/scanner/manager.py
quipucords/scanner/tests_manager.py

- Wait for process to terminate with a join
- Cleanup state transitions for job manager
Closes #1208

Fix database lock issue

---

quipucords/scanner/job.py
quipucords/scanner/manager.py

Wait to mark scan job failed until all tasks complete

---

client/scripts/api.sh
quipucords/quipucords/templates/registration/logged_out.html
quipucords/quipucords/templates/registration/login.html

* Remove dev server port check, keep for staging
* Copy update for app description
updates #1195

UI: Build and app description updates

---

docs/source/configure.rst
docs/source/install.rst
docs/source/install_cli.rst
docs/source/install_scripted.rst
docs/source/install_server_rhel6_centos6.rst
docs/source/install_server_rhel7.rst
docs/source/install_steps.rst
docs/source/quick_start.rst

Please review the changes to the install section. Thanks.
Closes #1237

1237: edits and reorg for install section

---

quipucords/api/credential/serializer.py
quipucords/api/credential/tests_credential.py

Update vCenter cred validation to allow partial updates. 

---

client/src/components/credentials/crendentialConstants.js
client/src/components/scans/scanConstants.js
client/src/components/scans/scans.js
client/src/components/sources/sourceConstants.js
client/src/components/sources/sources.js
client/src/components/viewToolbar/viewToolbar.js
client/src/redux/reducers/viewOptionsReducer.js
client/src/services/credentialsService.js
client/src/services/reportsService.js
client/src/services/scansService.js
client/src/services/sourcesService.js
quipucords/quipucords/templates/registration/logged_out.html
quipucords/quipucords/templates/registration/login.html

**Copy, fix, and clean up** 
* App description copy
* Revert fix for refresh timer on scans
* Services, updated static methods
**Scans & Sources most recent sort**
* `Most recent` copy fix
* Default Scans & Sources most recent sort to descending
updates #913 
updates #1195

UI: Copy updates, Scans & Sources most recent sort

---

Makefile
docs/swagger.yml
quipucords/api/admin.py
quipucords/api/fact/tests_fact.py
quipucords/api/fact/util.py
quipucords/api/migrations/0001_initial.py
quipucords/api/models.py
quipucords/api/report/renderer.py
quipucords/api/report/tests_report.py
quipucords/api/report/view.py
quipucords/api/scanjob/tests_scanjob.py
quipucords/api/status/model.py
quipucords/api/status/view.py
quipucords/fingerprinter/__init__.py
quipucords/fingerprinter/jboss_brms.py
quipucords/fingerprinter/jboss_eap.py
quipucords/fingerprinter/jboss_fuse.py
quipucords/fingerprinter/tests_engine.py
quipucords/fingerprinter/tests_product_brms.py
quipucords/fingerprinter/tests_product_eap.py
quipucords/fingerprinter/tests_product_fuse.py
quipucords/quipucords/environment.py
quipucords/quipucords/settings.py

Add global identifier to results

---

docs/source/cli_configure.rst
docs/source/cli_login.rst
docs/source/cli_logout.rst
docs/source/cli_server_interaction.rst
docs/source/index.rst
docs/source/install_server_rhel6_centos6.rst
docs/source/quick_start.rst

1259: Changes to CLI and QSG sections, other edits

---

docs/swagger.yml

Swagger updates for reports/deployment endpoint

---

docs/source/index.rst
docs/source/install_server_rhel7.rst
docs/source/man.rst
docs/source/quick_start.rst
docs/source/using_qpc.rst
docs/source/working_with_reports.rst
docs/source/working_with_scan_jobs.rst
docs/source/working_with_scans.rst
docs/source/working_with_sources.rst

1263: Changes for working with... section

---

bin/timeout_ssh
quipucords/scanner/network/inspect.py

work around ansible bug where command must be called ssh

---

client/src/components/addSourceWizard/addSourceWizardStepTwo.js
client/src/styles/entitlements/_views.scss

* SSL cert option for vCenter and Satellite sources
closes #1256
updates #1277 
@bclarhk @dozdowski

UI: Add Source Wizard, SSL Cert option

---

docs/source/cli_configure.rst
docs/source/cli_login.rst
docs/source/cli_logout.rst
docs/source/cli_server_interaction.rst
docs/source/index.rst
docs/source/install_server_centos7.rst
docs/source/install_server_fedora26_fedora27.rst
docs/source/install_server_rhel6_centos6.rst
docs/source/install_server_rhel7.rst
docs/source/install_steps.rst
docs/source/man.rst
docs/source/quick_start.rst
docs/source/using_qpc.rst

1292: miscellaneous cleanup, mostly tagging fixes

---

roles/check_dependencies/tasks/main.yml
roles/ifconfig/tasks/main.yml

Update ifconfig role to run for sudo & root users

---

roles/redhat_packages/tasks/main.yml

redhat_packages_gpg_is_redhat Fact failing on RHEL 5.6 Possibly Others

---

quipucords/scanner/manager.py
quipucords/scanner/network/inspect_callback.py
roles/check_dependencies/tasks/main.yml
roles/cpu/tasks/main.yml
roles/date/tasks/main.yml
roles/dmi/tasks/main.yml
roles/ifconfig/tasks/main.yml
roles/jboss_eap/tasks/main.yml
roles/jboss_eap5/tasks/main.yml
roles/jboss_fuse_on_karaf/tasks/main.yml
roles/redhat_packages/tasks/main.yml
roles/subman/tasks/main.yml
roles/virt/tasks/main.yml
roles/virt_what/tasks/main.yml

Missing entry in Summary report

---

quipucords/scanner/network/processing/karaf.py
quipucords/scanner/network/processing/util.py
roles/jboss_eap/tasks/main.yml
roles/jboss_eap5/tasks/main.yml
roles/jboss_fuse/tasks/main.yml
roles/jboss_fuse_on_karaf/tasks/main.yml

Detect consistent presence of fuse between root & sudo user

---

quipucords/api/scanjob/model.py
quipucords/api/signals/scanjob_signal.py
quipucords/scanner/job.py
quipucords/scanner/manager.py
quipucords/scanner/network/connect.py
quipucords/scanner/network/inspect.py
quipucords/scanner/network/tests_network_inspect.py
quipucords/scanner/satellite/api.py
quipucords/scanner/satellite/connect.py
quipucords/scanner/satellite/five.py
quipucords/scanner/satellite/inspect.py
quipucords/scanner/satellite/six.py
quipucords/scanner/satellite/tests_sat_connect.py
quipucords/scanner/satellite/tests_sat_five.py
quipucords/scanner/satellite/tests_sat_inspect.py
quipucords/scanner/satellite/tests_sat_six.py
quipucords/scanner/task.py
quipucords/scanner/tests_manager.py
quipucords/scanner/vcenter/connect.py
quipucords/scanner/vcenter/inspect.py
quipucords/scanner/vcenter/tests_vc_connect.py
quipucords/scanner/vcenter/tests_vc_inspect.py

Add interrupt using shared memory to jobs/tasks

---

quipucords/scanner/network/processing/brms.py
quipucords/scanner/network/processing/eap.py
quipucords/scanner/network/processing/test_brms.py
roles/jboss_brms/tasks/main.yml

Detect consistent presence of brms between root & sudo user

---

quipucords/scanner/network/processing/yum.py
roles/redhat_packages/tasks/main.yml

Cleanup yum_enabled_repolist

---

quipucords/api/scanjob/model.py
quipucords/api/scantasks/model.py
quipucords/api/scantasks/tests_scantask.py
quipucords/scanner/satellite/five.py
quipucords/scanner/satellite/six.py
quipucords/scanner/satellite/tests_sat_five.py
quipucords/scanner/satellite/tests_sat_six.py
quipucords/scanner/satellite/tests_sat_utils.py
quipucords/scanner/satellite/utils.py

Ensure the system name is unique for satellite

---

quipucords/api/scanjob/model.py
quipucords/api/scantasks/model.py
quipucords/api/scantasks/tests_scantask.py
quipucords/scanner/satellite/five.py
quipucords/scanner/satellite/six.py
quipucords/scanner/satellite/tests_sat_five.py
quipucords/scanner/satellite/tests_sat_six.py
quipucords/scanner/satellite/tests_sat_utils.py
quipucords/scanner/satellite/utils.py

* Ensure the system name is unique for satellite
* Update doc string to reflect systems_unreachable

Ensure the system name is unique for satellite (#1324)

---

docs/source/authentication.rst
docs/source/commands.rst

Document required commands for network scan

---

docs/source/authentication.rst
docs/source/commands.rst

* Document required commands for network scan

Document required commands for network scan (#1325)

---

docs/source/con_about_qpc.rst
docs/source/index.rst
docs/source/install_scripted.rst
docs/source/man.rst
docs/source/requirements.rst
qpc.spec

Please review the changes. 
In addition to Elijah's comments, there were a few other minor edits, mostly in man.rst.
Closes #1321

1321: Adding changes for Elijah's comments plus a few other minor edits

---

quipucords/scanner/vcenter/inspect.py

Place guard around cluster values

---

docs/source/install_cli.rst
install/roles/qpc_cli/tasks/main.yml

Pilot 0.0.42 install script and documentation reference centos for rhel 7 rpms

---

client/src/components/createCredentialDialog/createCredentialDialog.js

* Added state for disabling SSH Key when creating creds. Exception
cases for network creds, and if a file already exists
closes #1337 
@mdvickst

UI: Credentials, removed SSH Key for VCenter & Satellite

---

quipucords/api/source/model.py
quipucords/scanner/network/connect.py
quipucords/scanner/network/tests_network_connect.py

I didn't see anything that needed to be added to the docs.
Also the doc changes I added in the last merge aren't showing up yet on https://quipucords.readthedocs.io/en/0.0.42-pilot/man.html
(which they shouldn't really until this PR is merged and they become true)

added scanner capability to exclude hosts

---

quipucords/scanner/vcenter/connect.py
quipucords/scanner/vcenter/tests_vc_connect.py
quipucords/scanner/vcenter/utils.py

Replace the loop over all VMs and individual calls to retrieve the VM names with a single RetrieveProperties to get all names in one shot.
This reduces the time it takes to run the get_vm_names method from 12min 53sec to 22sec on a 10,240VM vCenter.

Use RetrieveProperties to get all VM names

---

qpc.spec
rel-eng/tito.props

Fixed classic spec errors and outdated tito props.

Fix invalid date issues in qpc.spec and update tito.props

---

quipucords/api/report/renderer.py
quipucords/api/report/tests_report.py

Commas Present in virt field for RHV host and other fields (#1385)

---

quipucords/scanner/network/processing/yum.py
roles/redhat_packages/tasks/main.yml

Suppress errors from yum repolist

---

quipucords/api/source/serializer.py
quipucords/api/source/tests_source.py

Filtered empty strings from host list

---

Makefile
README.rst

Small updates to make running docker image with UI easier

---

Jenkinsfile
README.rst
docs/source/configure.rst
docs/source/install_cli.rst
docs/source/install_container_image.rst
docs/source/install_scripted.rst
docs/source/troubleshooting.rst
docs/swagger.yml
install/roles/qpc_cli/tasks/main.yml
install/roles/qpc_server/tasks/main.yml

- references to COPR build
- references to release zip

0.0.44 release changes

---

install/roles/docker/tasks/main.yml
install/roles/epel/tasks/main.yml
install/roles/prep/tasks/main.yml
install/roles/qpc_cli/tasks/main.yml

Use only DNF for Fedora (#1452)

---

deploy/gunicorn.conf.py
quipucords/fingerprinter/__init__.py
quipucords/fingerprinter/jboss_eap.py
quipucords/fingerprinter/tests_engine.py
quipucords/local_gunicorn.conf.py
quipucords/scanner/network/processing/jws.py

Improve date parsing and increase gunicorn timeout

---

deploy/gunicorn.conf.py
quipucords/fingerprinter/__init__.py
quipucords/fingerprinter/jboss_eap.py
quipucords/fingerprinter/tests_engine.py
quipucords/local_gunicorn.conf.py
quipucords/scanner/network/processing/jws.py

* Improve date parsing and increase gunicorn timeout
* Fixed additional logging statements for jboss
* Add test case for new date parsing method
* Fix return code issue for jws

Improve date parsing and increase gunicorn timeout (#1459)

---

deploy/gunicorn.conf.py
docs/source/configure.rst
docs/source/install_scripted.rst
install/install.sh
install/roles/qpc_server/tasks/main.yml
quipucords/local_gunicorn.conf.py

* Add env to control gunicorn timeout value

Add env to control gunicorn timeout value (#1461)

---

quipucords/quipucords/settings.py
quipucords/scanner/network/connect.py
quipucords/scanner/network/inspect.py

Seperated the SSH timeout for connection and inspection (#1515)

---

install/install.sh

Installation scripts won't prompt for password if running as root (#1414)

---

docs/source/man.rst
qpc/messages.py
qpc/report/merge.py
qpc/report/tests_report_merge.py

Add QPC CLI bulk merge option (#1535)

---

quipucords/fingerprinter/__init__.py
quipucords/fingerprinter/tests_engine.py

VCenter infrastructure_type prefered over network 

---

.travis.yml
quipucords/scanner/job.py

Fail the scan job when the ScanTask fails and save to the database the
status message why it failed.

Update scan job logic when a ScanTask fails

---

dev-requirements.txt
requirements.txt

Finish last updates & pinning requirements

---

quipucords/fingerprinter/task.py

adding infrastructure to the fingerprinter task

Added infrastructure_type to fingerprinter task (#1521)

---

quipucords/api/messages.py
quipucords/api/signal/scanjob_signal.py
quipucords/scanner/manager.py

Harden scan manager to prevent crash and properly restart

---

quipucords/scanner/satellite/connect.py
quipucords/scanner/satellite/inspect.py
quipucords/scanner/satellite/tests_sat_connect.py
quipucords/scanner/satellite/tests_sat_inspect.py
quipucords/scanner/satellite/tests_sat_utils.py
quipucords/scanner/satellite/utils.py

Check sat6 endpoint before sat5. Closes #1564

Reverse order of satellite endpoint checking 

---

qpc/messages.py
qpc/report/merge.py
qpc/report/tests_report_merge.py

Fixed merge --json-files crash when file not found (#1566)

---

docs/source/man.rst
qpc/report/__init__.py
qpc/report/job.py

Renamed job command to match prefered syntax of insights #1585

---

.gitignore
quipucords/api/scantask/model.py
quipucords/api/scantask/serializer.py
quipucords/api/scantask/tests_scantask.py
quipucords/scanner/job.py
quipucords/scanner/network/inspect.py
quipucords/scanner/satellite/five.py
quipucords/scanner/satellite/inspect.py
quipucords/scanner/vcenter/inspect.py

Updates to ensure partial results are recorded for multiple source scans

---

qpc/report/tests_report_deployments.py
quipucords/api/common/util.py
quipucords/api/deployments_report/csv_renderer.py
quipucords/api/deployments_report/tests_deployments_report.py
quipucords/api/deployments_report/view.py
quipucords/fingerprinter/task.py

Add SystemFingerprint columns to csv report even if all values empty

---

quipucords/api/details_report/util.py
quipucords/scanner/job.py

Add report_version to all sources for future merges

---

install/install.sh

Look for the master release and exit with a non-zero return code when
ansible-playbook fail.

Update install script

---

quipucords/scanner/network/connect.py

Fix ssh-passphrase traceback 

---

quipucords/scanner/job.py

Handle case where connection has no results

---

qpc/scan/tests_utils.py
qpc/scan/utils.py
quipucords/api/scan/serializer.py
quipucords/api/scan/tests_scan.py

Update should check for None not a falsy value

---

deploy/run.sh
quipucords/scanner/network/connect.py

Fix sshpass & keyfile combo not working in container  (#1648)

---

quipucords/scanner/network/processing/__init__.py
quipucords/scanner/network/processing/redhat_packages.py
quipucords/scanner/network/processing/test_redhat_packages.py
roles/redhat_packages/tasks/main.yml

Add processing to remove trailing semicolon

---

quipucords/fingerprinter/jboss_eap.py
quipucords/fingerprinter/tests_product_eap.py

Fix eap manifest & jar version bugs

---

install/roles/qpc_cli/tasks/main.yml

Fix typo in version variable

---

Dockerfile
README.rst
deploy/gunicorn.conf.py
dev-requirements.txt
quipucords/local_gunicorn.conf.py

Upgrade gunicorn to 19.9.0

---

Dockerfile
install/roles/qpc_server/tasks/main.yml

* Fixed upgrade QPC container fails because ansible vault password is regenerated

Map ansible secret.txt to external volume

---

quipucords/scanner/satellite/five.py
quipucords/scanner/satellite/six.py

Collect mac and ip addresses from all interfaces (excluding loopback)

---

quipucords/scanner/satellite/five.py
quipucords/scanner/satellite/six.py

Backport fix for #1700 to 0.0.44

Collect all mac addresses (excluding loopback)

---

dev-requirements.txt
requirements.txt
roles/ifconfig/tasks/main.yml

I need to run some additional tests, but I will run them tonight because they take some time to run. However, after the initial run of testing it looks ready.

Collect IP addresses with hostname -I (#1684)

---

quipucords/api/common/middleware.py
quipucords/api/status/tests_status.py
quipucords/quipucords/settings.py

A X-Server-Version header

---

client/README.rst
client/config-overrides.js
client/src/components/mergeReportsDialog/mergeReportsDialog.js
client/src/components/sources/sourceListItem.js
client/src/redux/index.js
client/yarn.lock

Fix for #1709, involved simple update to response properties from `id` to `report_id`. Additional minor file lints and a yarn regenerate for the lock file. Minor future prep for centralizing Redux resources
- fix(ui build): ui regenerate yarn.lock, readme
* regenerate yarn.lock, readme update
* build script syntax lint
* sourceListItem lint update
- fix(ui mergeReportsDialog): ui 1709 merge reports
* centralize redux resources 
* 1709, minor property rename, prevented merging reports
- closes #1709

UI build updates and fix for issues/1709

---

client/package.json
client/scripts/swagger.js
client/src/common/helpers.js
client/src/components/mergeReportsDialog/mergeReportsDialog.js
client/src/components/scanHostList/scanHostList.js
client/src/components/scans/scanJobsList.js
client/src/components/scans/scanListItem.js
client/src/components/scans/scanSourceList.js
client/src/components/scans/scans.js
client/src/components/sources/createScanDialog.js
client/src/components/sources/sources.js
client/src/redux/reducers/addSourceWizardReducer.js
client/src/redux/reducers/credentialsReducer.js
client/src/redux/reducers/factsReducer.js
client/src/redux/reducers/reportsReducer.js
client/src/redux/reducers/scansReducer.js
client/src/redux/reducers/sourcesReducer.js
client/src/redux/reducers/statusReducer.js
client/src/redux/reducers/userReducer.js
client/yarn.lock

* fix(ui helpers): update for message helper
* update conditions for error message helper
* expand setStateProp
* new getStatusFromResults, prep for handling http status
* fix(ui scans): use centralized redux resources
* convert scans components for centralized redux
* comment clean up
* chore(ui build): package updates, minor file lint
* build packages, yarn.lock updates
* minor lint on swagger serve
* behind the scenes prep for #1710 
* "potential" fix for #1402 ui display "django mega message", 
* see update for `fix(ui helpers): update for message helper` commit
#1710 #1402

UI: Incremental updates towards issues/1710

---

docs/source/configure.rst
docs/source/install.rst
docs/source/install_cli.rst
docs/source/install_scripted.rst
docs/source/install_steps.rst

Update documentation for offline installation. 

---

quipucords/api/scan/serializer.py
quipucords/api/scan/tests_scan.py

Fix 500 error when editing sources on a scan 

---

install/install.sh
install/roles/docker/tasks/main.yml
install/roles/prep/tasks/main.yml

Fix RHEL6 not installing libselinux-python (#1764)

---

quipucords/scanner/network/processing/cpu.py
quipucords/scanner/network/processing/test_cpu.py
roles/cpu/tasks/main.yml

Fix cpu socket command including unpopulated sockets

---

quipucords/scanner/job.py

Remove details report print from pause/canceled jobs

---

install/install.sh
install/roles/qpc_server/tasks/main.yml

Install.sh will enable repos for RHEL7 machines and improved logging

---

docs/source/authentication.rst

https://github.com/quipucords/quipucords/issues/1831
This adds wording to satisfy the issue requirements explaining minimal permissions required and explaining no modifications in vcenter occur.

added vcenter account content in docs for issue 1831

---

dev-requirements.txt

- pytest to 4.3.0
- flake8 to 3.7.6

Update to requirements

---

install/qpc_playbook.yml
install/roles/prep/tasks/main.yml
install/roles/qpc_cli/tasks/main.yml
install/roles/qpc_server/tasks/main.yml

Move install server/cli to role level when

---

quipucords/api/common/common_report.py
quipucords/api/migrations/0003_system_platform_id.py
quipucords/quipucords/environment.py
quipucords/quipucords/release.py

Add release constants to a release.py

---

README.rst
install/install.sh
install/roles/docker/tasks/main.yml
install/roles/epel/tasks/main.yml
install/roles/prep/tasks/main.yml
install/roles/qpc_cli/tasks/main.yml
install/roles/qpc_server/tasks/main.yml

Remove ability to install quipucords on Fedora using scripts

---

README.rst

Added openssl section to readme.

---

quipucords/scanner/network/processing/test_yum.py
quipucords/scanner/network/processing/yum.py

Ensure that we are only collecting useful info for enabled repos

---

quipucords/scanner/satellite/six.py
quipucords/scanner/satellite/utils.py

Add timeout to requests

---

install/install.sh
install/roles/prep/tasks/main.yml
install/roles/qpc_cli/tasks/main.yml
install/roles/qpc_server/tasks/main.yml

Allow the versions to be passed in as an argument to the installer

---

quipucords/scanner/network/connect_callback.py
quipucords/scanner/network/inspect_callback.py

Add check to ignore the runner_on_start state

---

Jenkinsfile
quipucords/quipucords/release.py

Create 0.9.1 so that images will be newer than the 0.9.0 release.

Bump master version to 0.9.1

---

quipucords/scanner/network/inspect.py

Change behavior of scan failure when more than one system fails

---

docs/swagger.yml
quipucords/fingerprinter/task.py
quipucords/fingerprinter/tests_fingerprint_task.py

Add last_reported time to insights repots

---

quipucords/scanner/network/inspect.py

Ensure the finalize failed hosts method runs even when the scan reports success

---

quipucords/api/insights_report/tests_insights_report.py
quipucords/api/insights_report/view.py

Check for case where no hosts exist

---

quipucords/api/details_report/model.py
quipucords/scanner/network/processing/dmi.py
quipucords/scanner/network/processing/test_dmi.py

Add bounds checking for dmi_system_uuid

---

.coveragerc
Makefile
dev-requirements.txt
pytest.ini
quipucords/quipucords/settings.py

Use pytest test runner and allow parallel testing with pytest-xdist

Pytest xdist

---

.gitignore
Makefile
quipucords/quipucords/featureflag.py
quipucords/quipucords/settings.py
quipucords/quipucords/tests_feature_flags.py

Creates class FeatureFlag to administrate environment variable and status(ENABLED-DISABLED).
Filters feature flags in function get_env_flags_from_environ(), making sure only variables that follow the pattern are added or updated.
Creates unit tests for the class and helper fuction.

Creates class FeatureFlag to handle when new features will be added

---

dev-requirements.txt
pyproject.toml
quipucords/quipucords/featureflag.py
quipucords/quipucords/test_feature_flags.py
quipucords/scanner/network/inspect.py
quipucords/scanner/network/runner/roles/subman/tasks/main.yml

- Import FeatureFlags into scanjob as extra vars. Adds feature flag as condition for the gathering overall status fact.
- Addition of method as_dict for FeatureFlag class as Ansible extravars expects objects to be simpler than an instance of the class.
- Unit tests for new method.
- Adds subscription-management overall status fact to subman role.
Manually tested on:
-AWS machines(RHEL6, RHEL7, RHEL8)
-Vagrant(CentOS6, CentOS7, CentOS8)

Biz 400 / issue 2064- adds overall status fact to subman role

---

Makefile
docs/swagger.yml

Also, include a command to easily serve swagger UI

Fix a bug preventing the generation of swagger UI

---

AUTHORS.md
README.md

-adds installation instructions for asdf
-updates on Python version supported
-updates list of authors and current maintainers of quipucords project
-updates instructions on how to install the project using docker-compose for Mac and Linux OS

Update readme Quipucords

---

quipucords/utils/__init__.py
quipucords/utils/deepget.py
quipucords/utils/test_deepget.py

This feature will be used in the upcoming PR that collects all network scan fingerprints

deepget util to retrieve data in nested dict/lists

---

README.md

remove duplicated text from readme

remove duplicated text from readme

---

quipucords/api/common/entities.py
quipucords/api/common/serializer.py
quipucords/api/common/test_entities.py
quipucords/api/deployments_report/model.py
quipucords/api/exceptions.py
quipucords/api/insights_report/constants.py
quipucords/api/insights_report/serializers.py
quipucords/api/insights_report/test_serializers.py
quipucords/api/insights_report/tests_insights_report.py
quipucords/api/insights_report/view.py
quipucords/api/status/__init__.py
quipucords/tests/factories.py

- Add YupanaPayloadSerializer and a bunch of "child" serializers to properly format data for insights
- Refactor insights report view to use YupanaPayloadSerializer
Contributes to DISCOVERY-130
Implements DISCOVERY-129

[DISCOVERY-129] - Serializer dedicated to format data for Insights

---

quipucords/fingerprinter/task.py

last_checkin was not properly formatted.
Fix DISCOVERY-165.
Co-authored-by: Nicole Aragao <naragao@redhat.com>
Co-authored-by: Rudá Moura <rmoura@redhat.com>

[DISCOVERY-165] - Fix a bug on _process_satellite_fact

---

.github/workflows/build.yml
.github/workflows/test.yml
.gitignore
Makefile
README.md
dev-requirements.txt
docker-compose.yml
quipucords/tests/integration/conftest.py
requirements.in
requirements.txt

Also:
- Update postgres image to 12 (since this is the one we are recommending for use)
- QoL/Dx updates to docker-compose

Backports from release/1.0

---

Dockerfile
Makefile
quipucords/tests/integration/test_ui_rendering.py

UI version updated to latest (but still configurable through QUIPUCORDS_UI_VERSION env var)

Update UI version

---

Makefile
dev-requirements.in
dev-requirements.txt
quipucords/api/source/model.py
quipucords/api/source/test_model.py
quipucords/fingerprinter/task.py
quipucords/fingerprinter/test_fingerprint_process_sources.py
quipucords/scanner/exceptions.py
quipucords/scanner/job.py
quipucords/scanner/network/connect.py
quipucords/scanner/network/exceptions.py
quipucords/scanner/network/inspect.py
quipucords/scanner/network/tests_network_inspect.py
quipucords/scanner/satellite/api.py
quipucords/scanner/satellite/connect.py
quipucords/scanner/satellite/inspect.py
quipucords/scanner/satellite/task.py
quipucords/scanner/satellite/tests_sat_connect.py
quipucords/scanner/satellite/tests_sat_inspect.py
quipucords/scanner/task.py
quipucords/scanner/vcenter/connect.py
quipucords/scanner/vcenter/inspect.py
quipucords/tests/factories.py
quipucords/utils/__init__.py

These refactorings will contribute to DISCOVERY-186 implementation

ScanTaskRunners Refactorings

---

Makefile

- Minor update to the Makefile to remove the unused manpage directive.

Removed the manpage Makefile directive as it is not currently implemented.

---

quipucords/scanner/network/tests_utils.py

Protect raw_facts_template function against a regression as seen in DISCOVERY-262.

test(netscan): test raw_facts_template

---

quipucords/api/common/common_report.py
quipucords/api/common/report_json_gzip_renderer.py
quipucords/api/common/tests_common_util.py
quipucords/api/insights_report/insights_gzip_renderer.py
quipucords/api/insights_report/tests_insights_report.py
quipucords/api/reports/reports_gzip_renderer.py
quipucords/api/reports/tests_reports.py

fix(sha256sum): Fix SHA256 calc for reports

---

quipucords/api/deployments_report/tests_deployments_report.py
quipucords/api/details_report/tests_details_report.py
quipucords/api/details_report/tests_sync_report_creation.py
quipucords/api/details_report/util.py
quipucords/api/merge_report/tests_async_merge_report.py
quipucords/api/merge_report/tests_sync_merge_report.py
quipucords/api/reports/tests_reports.py
quipucords/api/scanjob/tests_scanjob.py
quipucords/api/status/misc.py
quipucords/api/status/model.py
quipucords/api/status/view.py
quipucords/fingerprinter/tests_fingerprint_task.py
quipucords/fingerprinter/tests_product_brms.py
quipucords/fingerprinter/tests_product_eap.py
quipucords/fingerprinter/tests_product_fuse.py
quipucords/fingerprinter/tests_product_jws.py
quipucords/quipucords/environment.py

- Replacing create_or_retreive_server_id() with create_or_retrieve_server_id().
- Also, updated a couple of comments for the same.

chore(refact): Fix method name

---

quipucords/api/credential/serializer.py
quipucords/api/credential/test_serializer.py
quipucords/api/credential/tests_credential.py
quipucords/api/messages.py

- Refactor Credential Serializer and removing lots of unnecessary code.
- Add new serializer tests to ensure this refactoring didn't break anything
A follow up PR will be created soon, but this one is already big enough as is.

DISCOVERY-287 - Refactor Credential serializer

---

quipucords/api/credential/model.py
quipucords/api/credential/serializer.py
quipucords/api/credential/test_serializer.py
quipucords/api/credential/tests_credential.py
quipucords/api/credential/view.py
quipucords/api/serializers.py
quipucords/api/source/model.py
quipucords/constants.py
quipucords/scanner/network/connect.py
quipucords/scanner/network/inspect.py
quipucords/scanner/network/tests_network_connect.py
quipucords/scanner/network/tests_network_inspect.py

1. fix the bugs highlighted by new tests added on the previous refactor
2. move "serialization logic" from credential view to serializer itself
3. cover credential view with more tests

refactor Credential Serializer 2 - electric boogaloo

---

Makefile
quipucords/quipucords/environment.py

refact: fix formatting to keep black happy
this was giving me make lint failures.

refact: fix formatting to keep black happy

---

conftest.py
quipucords/api/reports/tests_reports.py
quipucords/compat/requests.py
quipucords/compat/test_requests.py
quipucords/tests/integration/conftest.py
quipucords/tests/utils/container_wrappers.py
quipucords/tests/utils/http.py

DRY up a test and prepare our "specialized requests.Session" class for ansible controller integration.

One more refactor

---

pyproject.toml
quipucords/scanner/openshift/entities.py
quipucords/scanner/openshift/test_entities.py

backport DISCOVERY-308 fix to master

backport DISCOVERY-308 fix to master

---

quipucords/scanner/satellite/six.py

This change is another cleanup on the long journey to Celery. I have introduced a generator to consolidate several calls to Satellite v6 sources that would require multiple requests through paginated results. This is an improvement, but I'm not done cleaning up this module. Expect to see other PRs touching the same code in the near future.
I recommend reviewing the changes with "hide whitespace" enabled because I de-indent some code blocks.

refactor: dedupe several execute_request calls into a generator

---

Dockerfile

chore: adding ps to the image
- ps comes in handy for doing certain livenessProbes.

chore: adding ps to the image

---

quipucords/scanner/satellite/api.py
quipucords/scanner/satellite/five.py
quipucords/scanner/satellite/six.py
quipucords/scanner/satellite/tests_sat_connect.py
quipucords/scanner/satellite/tests_sat_inspect.py
quipucords/scanner/satellite/tests_sat_six.py

This PR is an effort to reduce lots of old copy-paste duplicated code. I am trying to bring more sanity to the Satellite modules before I resume the Celery conversion so that there will be fewer things to update.

dedupe satellite code

---

quipucords/api/credential/serializer.py
quipucords/api/credential/test_serializer.py

fix: add missing CredentialSerializer for ansible controller

---

pyproject.toml

Relates to JIRA: DISCOVERY-304

chore: bump version to 1.2.3

---

quipucords/scanner/ansible/inspect.py
quipucords/tests/integration/test_ansible_scan.py

chore(ansible): rename id fields

---

Dockerfile.scan-target
quipucords/scanner/network/processing/installed_products.py
quipucords/scanner/network/processing/test_installed_products.py
quipucords/tests/integration/test_network_scan.py

Output from stdout_lines was being retrieved instead of stdout, therefore causing an implementation error.

fix: wrong key was being retrieved from output

---

Makefile
quipucords/api/common/util.py
quipucords/api/deployments_report/tests_deployments_report.py
quipucords/api/details_report/tests_details_report.py
quipucords/api/reports/tests_reports.py
quipucords/tests/utils/__init__.py
quipucords/tests/utils/patch_mask_value.py

Mock "mask value" utility and get rid of now useless env vars for testing

Mock "mask value" utility

---

quipucords/fingerprinter/runner.py
quipucords/fingerprinter/test_fingerprint_process_sources.py

Addopting tuples adds reproducibility - which in turn makes this code easily testable.

fix(fingerprinting): use tuples instead of set

---

quipucords/scanner/satellite/api.py
quipucords/scanner/satellite/five.py
quipucords/scanner/satellite/six.py

Moving, deduplicating, and encapsulating the `multiprocessor.Pool` code in the Satellite scanners will make it easier to override and replace with Celery tasks in the near future.

refactor: deduplicate multiprocessing code in satellite scanner modules

---

quipucords/api/credential/tests_credential.py

- Adding tests that verifies that changing credentials types fail with a 400.
- Testing Network credential -> OpenShift type
- Testing vCenter credential -> Network type

test: changing credential types should fail

---

quipucords/quipucords/environment.py
quipucords/quipucords/tests_environment.py

change quipucords version format
X.Y.Z.commit-sha -> X.Y.Z+commit-sha

[discovery-344] change version fmt

---

.github/workflows/build.yml
.github/workflows/test.yml
CONTRIBUTING.md
README.md

Minor maintenance cleanup after renaming our main branch from `master` to `main`.

chore: s/master/main/g

---

quipucords/tests/api/credential/test_credential.py

Port [`test_edit_sshkeyfile`](https://github.com/quipucords/camayoc/blob/876a0eda4b3d7cebfb57432c4580e19c8e6c47a3/camayoc/tests/qpc/cli/test_credentials.py#L347) from Camayoc.
It's hard to test in Camayoc, as this test requires two valid files accessible to server - to meet this requirement, we would have to do additional thing when provisioning a server. And while provisioning is manual, we obviously want to minimize the number of things to do. Right now it's the only test in Camayoc that consistently fails.
At the same time, I don't see a reason why such test should be executed by Camayoc - it's not like `qpc` has any special logic for this particular case.

Test if SSH key path can be updated

---

Jenkinsfile

Let's see if Jenkins picks it up.

Add Jenkinsfile for internal CI

---

quipucords/api/reports/view.py

Since the url for reports tarball view gives no margin for a None report id, the error treatment the view had for report_id is completely useless (django is already doing that for us).

chore(reports-view): small cleanup

---

quipucords/tests/api/details_report/test_details_report.py

Convert test files I recently touched to pytest
will be covered on #2480 
won't touch this one since @abellotti will probably 🪓 it
won't touch since @abellotti fixed this one too
will be covered on #2480 
In the end most of these tests are already converted to pytest, so I'm only converting one. Yay us!

convert ~some tests~ a test to pytest

---

quipucords/tests/api/source/test_source.py

If you touch it, you refactor it. =)

refactor(source): unittest to pytest.

---

docs/swagger.yml

Update api spec with new sources.

feat(acs): update api spec to reflect new added sources

---

quipucords/scanner/acs/connect.py
quipucords/tests/integration/test_acs_scan.py
quipucords/tests/scanner/acs/test_connect.py

Update endpoint to enhance connection validation.
Replaced the previous healthcheck endpoint with a more accurate one for verifying ACS service connectivity.
Relates to Jira: Discovery-461
https://issues.redhat.com/browse/DISCOVERY-461

fix(acs): fix initial connection check

---

quipucords/scanner/openshift/entities.py
quipucords/tests/scanner/openshift/test_entities.py

This commit has a test that reproduces and fixes DISCOVERY-462. See the Jira issue for more details.
Relates to Jira: DISCOVERY-462

fix(OCP): don't break OCP scan if operator is missing information

---

quipucords/scanner/network/normalizer.py
quipucords/scanner/normalizer.py
quipucords/tests/scanner/network/test_normalizer.py
quipucords/tests/scanner/test_normalizer.py

Adds a base normalizer that will work as a foundation for the normalization phase.
Also, add a normalizer for network scans to have a more practical example.
This PR is a spiritual successor for its original RFC (#2442)
Relates to JIRA: DISCOVERY-226

feature: base normalizer

---

pyproject.toml
quipucords/log_messages.py
quipucords/scanner/network/connect.py
quipucords/scanner/network/connect_callback.py
quipucords/scanner/network/inspect.py
quipucords/scanner/network/inspect_callback.py
quipucords/tests/scanner/network/test_network_connect_callback.py
quipucords/tests/scanner/network/test_network_inspect.py

Relates to JIRA: DISCOVERY-490

fix(network-scan): handle unexpected ansible event data

---

quipucords/api/source/view.py

Relates to JIRA: DISCOVERY-372

fix(source-create): prevent a race condition on triggered scans

---

quipucords/api/insights_report/serializers.py

Relates to JIRA: DISCOVERY-404
https://issues.redhat.com/browse/DISCOVERY-404

fix: gracefully handle socket.gethostbyname failure

---

Jenkinsfile

Make Jenkinsfile consistent with what we have for internal jobs. See swatch-ci repo PR #242 .
Let's hope github PR runner can handle parallel agents :) .

Run Camayoc against PRs on all supported OSes

---

docker-compose.yml
quipucords/tests/api/scan/test_scan.py
quipucords/tests/api/status/test_status.py
quipucords/tests/api/user/test_user.py
quipucords/tests/factories.py

Port tests I'm working in another branch to pytest.

Port more tests to pytest

---

pyproject.toml

Relates to JIRA: DISCOVERY-519
https://issues.redhat.com/browse/DISCOVERY-519

chore: bump version to 1.5.0

---

quipucords/api/scan/view.py
quipucords/api/urls.py
quipucords/tests/api/scan/test_scan.py
quipucords/tests/api/scanjob/test_scanjob.py
quipucords/tests/factories.py

also fix a inconsistency in ScanFactory where related jobs were not fully associated to Scan instances.

tests: pytestfy quipucords/tests/api/scanjob/test_scanjob.py

---

quipucords/api/urls.py
quipucords/quipucords/settings.py
quipucords/quipucords/urls.py
quipucords/tests/api/credential/test_credential.py
quipucords/tests/api/details_report/test_sync_report_creation.py
quipucords/tests/api/merge_report/test_async_merge_report.py
quipucords/tests/api/scan/test_scan.py
quipucords/tests/api/scanjob/test_scanjob.py
quipucords/tests/api/source/test_source.py
quipucords/tests/api/status/test_status.py
quipucords/tests/api/user/test_user.py
quipucords/tests/scanner/network/test_network_inspect.py

this is a preparation step for the addition of api v2
Relates to JIRA: DISCOVERY-340

refactor: use DRF versioning for V1 api

---

quipucords/tests/api/credential/test_credential.py

I would like to reduce duplication between Camayoc and Quipucords unit tests. If something can be tested at unit level, it should be tested at unit level.
This is the port of https://github.com/quipucords/camayoc/blob/main/camayoc/tests/qpc/api/v1/credentials/test_manager_creds.py 
I am opening this to get early feedback. Mostly: how do people feel about extending existing unit tests to cover wider combination of things?   
What about readability and short variable names here? Should I move these parameters generation to separate functions?
I intend to add more ported tests before opening it for merge. And I assume there are going to be multiple PRs like this one.

Port API tests from Camayoc

---

quipucords/api/urls.py
quipucords/tests/api/credential/test_credential.py
quipucords/tests/api/deployments_report/test_deployments_report.py
quipucords/tests/api/details_report/test_details_report.py
quipucords/tests/api/insights_report/test_insights_report.py
quipucords/tests/api/merge_report/test_async_merge_report.py
quipucords/tests/api/reports/test_reports.py
quipucords/tests/api/scanjob/test_scanjob.py
quipucords/tests/api/test_urls.py
quipucords/tests/constants.py

- Updated tests with hard coded /api/v1 paths to use django's reverse() function.
- Updated tests using test constants referencing /api/v1 paths.

tests: Updated tests with hardcoded /api/v1 paths to use reverse()

---

quipucords/scanner/network/inspect_callback.py
quipucords/tests/utils/test_sanitize_for_utf8_compatibility.py
quipucords/utils/__init__.py
quipucords/utils/misc.py

Relates to JIRA: DISCOVERY-529
https://issues.redhat.com/browse/DISCOVERY-529

fix: sanitize raw ansible values before storing them to the database

---

pyproject.toml

Relates to JIRA: DISCOVERY-528
https://issues.redhat.com/browse/DISCOVERY-528

chore: bump version to 1.4.6

---

quipucords/tests/scanner/satellite/test_sat_connect.py
quipucords/tests/scanner/satellite/test_sat_factory.py
quipucords/tests/scanner/satellite/test_sat_five.py
quipucords/tests/scanner/satellite/test_sat_inspect.py
quipucords/tests/scanner/satellite/test_sat_six.py
quipucords/tests/scanner/satellite/test_sat_utils.py

- Converting the satellite sanner test from UnitTest (TestCase) to pytest.

test(sat): Converting Satellite UnitTests to pytest

---

quipucords/tests/api/scan/test_scan.py
quipucords/tests/api/scanjob/test_scanjob.py
quipucords/tests/scanner/test_util.py

Adding unit tests for things that we have in Camayoc.

Port Scan API tests from Camayoc

---

quipucords/tests/api/scan/test_scan.py

This is a followup to 5fb848e9 which applied the same new fixture to credentials tests.
* before this change: `33 passed, 78 warnings in 46.73s`
* after this change: `34 passed, 77 warnings in 7.10s`

refactor: accelerate scans test executions by using better fixtures

---

quipucords/api/credential/view.py
quipucords/api/deployments_report/view.py
quipucords/api/details_report/view.py
quipucords/api/insights_report/view.py
quipucords/api/merge_report/view.py
quipucords/api/reports/view.py
quipucords/api/scan/view.py
quipucords/api/scanjob/view.py
quipucords/api/source/view.py
quipucords/api/user/view.py
quipucords/quipucords/settings.py

This removes a lot of (probably copy-paste anti-pattern) unnecessary code duplicated across all our views.
DRY. ☀️ 🌵

refactor: simply use DEFAULT_AUTHENTICATION_CLASSES for all views

---

README.md
docs/swagger.yml
quipucords/api/credential/view.py
quipucords/api/source/view.py

Just a few minor fixes I noticed while working on other changes.

docs: update outdated docstrings, swagger, and readme

---

quipucords/api/source/view.py
quipucords/tests/api/source/test_source_bulk_delete.py

The is a followup to bbedc8b1 (https://github.com/quipucords/quipucords/pull/2605). Our original approach was too conservative and could result in sources that would not be bulk deleted despite following a bulk delete of all scans because deleting scans does not necessarily delete all related scanjobs and scantasks.
As a result of not filtering out sources based on relationships with scanjobs and scantasks, the API response to "bulk delete sources" is now simpler and no longer includes the IDs of related scanjobs and scantasks.

fix: do not skip deleting a source simply because a scanjob or scantask references it

---

quipucords/quipucords/settings.py

Relates to JIRA: DISCOVERY-573
https://issues.redhat.com/browse/DISCOVERY-573

feat: enable request throttling with configurable rates

---

conftest.py
quipucords/tests/api/credential/test_credential.py
quipucords/tests/api/deployments_report/test_deployments_report.py
quipucords/tests/api/details_report/test_details_report.py
quipucords/tests/api/insights_report/test_insights_report.py
quipucords/tests/api/merge_report/test_async_merge_report.py
quipucords/tests/api/reports/test_reports.py
quipucords/tests/api/scan/test_scan.py
quipucords/tests/api/scan/test_scan_bulk_delete.py
quipucords/tests/api/scanjob/test_scanjob.py
quipucords/tests/api/source/test_source.py
quipucords/tests/api/source/test_source_bulk_delete.py
quipucords/tests/api/status/test_status.py
quipucords/tests/api/user/test_user.py
quipucords/tests/compat/test_requests.py
quipucords/tests/integration/test_ansible_scan.py
quipucords/tests/integration/test_rhacs_scan.py
quipucords/tests/integration/test_smoker.py
quipucords/tests/utils/http.py

The reality is we don't need a live server for our tests. GOTTA GO FAST.

test: replace django_client fixture with the much faster client_logged_in

---

conftest.py
docs/swagger.yml
quipucords/api/status/view.py
quipucords/api/urls.py
quipucords/api/views.py
quipucords/tests/api/status/test_status.py

- adding a public /api/v1/ping/ endpoint
- text/plain pong response
- can be used for liveness probes

feature(ping): Adding a public ping endpoint

---

pyproject.toml
quipucords/api/migrations/0049_inspectresult_tasks.py
quipucords/scanner/exceptions.py
quipucords/scanner/network/exceptions.py
quipucords/scanner/network/inspect.py
quipucords/scanner/network/utils.py
quipucords/scanner/openshift/entities.py
quipucords/scanner/runner.py
quipucords/scanner/satellite/api.py
quipucords/scanner/satellite/five.py
quipucords/scanner/satellite/inspect.py
quipucords/scanner/satellite/runner.py
quipucords/scanner/satellite/six.py
quipucords/scanner/satellite/utils.py
quipucords/tests/api/scan/test_scan.py
quipucords/tests/factories.py
quipucords/tests/scanner/network/test_network_connect.py
quipucords/tests/scanner/network/test_network_inspect.py
quipucords/tests/scanner/satellite/test_sat_connect.py
quipucords/tests/scanner/satellite/test_sat_five.py
quipucords/tests/scanner/satellite/test_sat_inspect.py
quipucords/tests/scanner/satellite/test_sat_six.py
quipucords/tests/scanner/satellite/test_sat_utils.py

style: enable pep8-naming ruff checks

---

quipucords/api/insights_report/serializers.py

HBI and yuptoo require we now set this value to "discovery".
Relates to JIRA: DISCOVERY-180
Relates to JIRA: RHINENG-2639

chore: set insights-report source to "discovery"

---

quipucords/scanner/openshift/api.py
quipucords/scanner/openshift/entities.py
quipucords/tests/scanner/openshift/test_api.py

Relates to JIRA: DISCOVERY-623

feature(openshift-scanner): include unschedulable fact

---

quipucords/api/signal/scanjob_signal.py
quipucords/scanner/manager.py

Fixing a few minor issues I ran into when trying to invoke scan managers in a local development environment.

fix: scan manager logs

---

quipucords/tests/scanner/network/test_normalizer.py
quipucords/tests/utils/raw_facts_generator.py

These changes make our generated raw facts slightly more realistic or at least more varied so that they will product more interesting and less uniform fingerprints in tests.

test: improve raw fact generators value randomness

---

quipucords/api/aggregate_report/model.py
quipucords/api/aggregate_report/view.py
quipucords/tests/api/aggregate_report/test_aggregate_report_model.py
quipucords/tests/api/aggregate_report/test_aggregate_report_view.py

Relates to JIRA: DISCOVERY-611

fix: more explicit 404 handling for aggregate report view

---

poetry.lock
pyproject.toml

Relates to JIRA: [DISCOVERY-718](https://issues.redhat.com/browse/DISCOVERY-718)

build: update poetry.lock, update quipucords version to 1.8.5

---

quipucords/quipucords/settings.py

Relates to JIRA: DISCOVERY-733

fix: refuse to set DEBUG if PRODUCTION is set

---

deploy/entrypoint_web.sh
deploy/gunicorn_conf.py
docker-compose.yml

chore: remove option to run server with https

---

quipucords/scanner/network/inspect_callback.py
quipucords/tests/scanner/network/test_inspect_callback.py

Considering not all logs shared with us contain events from ansible (and we might even dial down its verbosity at some point), let's grab more context info from failed events.
Relates to JIRA: DISCOVERY-779

chore: refactor logging of failed ansible events

---

quipucords/scanner/job.py
quipucords/scanner/network/inspect_callback.py
quipucords/tests/integration/test_network_scan.py
quipucords/tests/integration/test_smoker.py
quipucords/tests/utils/facts.py
quipucords/tests/utils/raw_facts_generator.py

Add a much-needed smoke test for the network scan.

test: add an integration test for network scan

---

.github/workflows/build-arm64.yml
.github/workflows/build.yml

As discussed at standup with @ruda and the dev team on 2024-11-12.

build: bump quay.expires-after from 5d to 7d to allow more test time

---

quipucords/tests/integration/test_network_scan.py

The sanity check for network scan fingerprints was failing due to a flakiness with expected fingerprints. The full story is "system_creation_date" fact is only present when one of its raw facts has a non-null value. The test was failing when raw_facts_generator had all their values set to null[1], which has a chance of ~12% of ocurring.
Relates to JIRA: DISCOVERY-783
[1]: https://github.com/quipucords/quipucords/blob/6a935a47943366a2e8d0a0518f89d67acc009366/quipucords/tests/utils/raw_facts_generator.py#L124-L126

test(network-scan): patch a flaky test

---

quipucords/api/credential/view.py
quipucords/tests/api/credential/test_credential_view.py

This PR effectively restores the behavior of the v1 credentials API that we missed when we added the v2 credentials API. In addition to returning a 400 error when the requested credential is related to a source, the API also now returns a 404 error when the requested credential ID does not exist.
Thanks for finding this issue, @mirekdlugosz !

fix: forbid credential delete if assigned to a source (v2 credentials API)

---

pyproject.toml

Relates to JIRA: DISCOVERY-868

build: bump quipucords version to 1.11.1

---

quipucords/scanner/job.py
quipucords/scanner/satellite/api.py
quipucords/scanner/satellite/six.py
quipucords/scanner/tasks.py
quipucords/tests/scanner/job/test_job_celery_based.py
quipucords/tests/scanner/satellite/test_sat_api_prepare_and_process_hosts_using_celery.py
quipucords/tests/scanner/satellite/test_sat_six.py
quipucords/tests/scanner/tasks/test_celery_run_task_runner.py
quipucords/tests/scanner/tasks/test_finalize_scan.py
quipucords/tests/scanner/tasks/test_fingerprint.py
quipucords/tests/scanner/tasks/test_tasks.py

Relates to JIRA: DISCOVERY-800
Relates to JIRA: DISCOVERY-838

fix: update scan task/job status to failed when unhandled exception occurs in celery tasks

---

docs/swagger.yml
quipucords/api/source/view.py
quipucords/tests/api/source/test_source.py

Relates to JIRA: DISCOVERY-784

refactor: creating a Source should not create a connect-type ScanJob

---

.tekton/discovery-server-push.yaml

Relates to JIRA: DISCOVERY-708

ci(konflux): make snyk results available on ui

---

.tekton/discovery-server-pull-request.yaml
.tekton/discovery-server-push.yaml

- Adding "latest" tag for Konflux push pipeline images
- Adding "pr-#" tag for Konflus pull request pipeline images

Creating latest and pr-# tags on Konflux built images

---

AUTHORS.md
CONTRIBUTING.md
Makefile
README.md

Lots of old cruft was in our docs that was just plain wrong or irrelevant.
I took some large swings at reorganizing and rewriting the README. I hope it's more useful for our latest new-hire.

docs: update several project-level docs

---

.tekton/discovery-server-pull-request.yaml
.tekton/discovery-server-push.yaml

Relates to JIRA: DISCOVERY-969
This was tested on yaka repo.

ci(konflux): adjust pipeline to support discovery release workflow

---

quipucords/api/source/serializer.py
quipucords/tests/api/source/test_serializer.py

This PR ensures that ssl_cert_verify continues to default to True when omitted, both during create and update operations using the V2 API for HTTP sources. This aligns with the previous behavior from V1, preventing regressions and preserving expected defaults.
**Since we still plan to keep V1 active for a while, I opted for a minimal-impact approach that would avoid introducing side effects or breaking existing behavior in legacy code paths.**
I added explicit test cases for all the relevant combinations. Yes, the tests are intentionally verbose, I avoided parametrization here to make sure each scenario is clearly expressed and that no subtle variations were hidden by shared setup. This was important to gain confidence that we’re handling the ssl_cert_verify default consistently and …

fix: ensure ssl_cert_verify default is preserved on create and update

---

.tekton/discovery-server-pull-request.yaml
.tekton/discovery-server-push.yaml
Containerfile
lockfiles/requirements-build.txt
lockfiles/requirements.txt
lockfiles/rpms.lock.yaml
pyproject.toml
quipucords/tests/fingerprinter/test_fingerprint_process_sources.py
quipucords/tests/utils/facts.py
uv.lock

Relates to JIRA: DISCOVERY-1005

build: make update-lockfiles
