quipucords/api/models.py, quipucords/api/serializers.py, quipucords/api/tests.py, quipucords/api/urls.py, quipucords/api/views.py
This allows basic CRUD operations on NetworkProfiles, and does some
validation. The validation is not complete, but importing all of the
normalization and validation we do in rho will be a big change, and I
think it makes sense to get this reviewed first.
Closes #25 .
=> Create Model and ViewSet for NetworkProfile objects

README.rst
`/usr/bin/2to3` is required by one of the dependencies installed by pip,
and this is provided by the `python-tools` package in both Fedora and RHEL
7
Just a small update, but this not installed on a standard RHEL 7 or Fedora 25 install, and may slow users down, as the error  message is not totally clear, nor what package might provide this utility.
=> Update readme with required package info

docs/swagger.yml, quipucords/quipucords/settings.py
Closes #89 
- Trailing slashes are now required (return 404 regardless of HTTP verb)
- Updated swagger to match new requirement
=> Modify behavior for trailing slashes on REST API

quipucords/api/scanjob/model.py, quipucords/api/scanjob/serializer.py, quipucords/api/scanjob/tests_scanjob.py, quipucords/quipucords/settings.py, quipucords/scanner/callback.py, quipucords/scanner/host.py, quipucords/scanner/tests_discovery.py, quipucords/scanner/tests_host.py, quipucords/scanner/utils.py
The following changes were made:
- Host scans will now continue even if a previously reachable host is not unreachable
- If a host connectivity changes, the host will move from success to failed in the scan results
- Host scan will now count failed scans so a completed scan does not appear to be missing systems
- Added back APPEND_SLASH
Closes #203
=> Handle failed hosts post discovery

roles/date/tasks/main.yml
This will cause the date to be None.  Facts with None are not included.
Closes #217
=> Suppress stderr for anaconda-ks.cfg command

.dockerignore
This lets us build a Docker container after previously using the
source tree for running a server directly. This is an improvement on
the current situation, but the build still might not be clean.
Closes #341
=> Add quipucords/db.sqlite3 to .dockerignore

Makefile
We don't need to lint third-party code in our Python virtualenv.
=> Exclude 'venv' from linting

quipucords/scanner/network/inspect_callback.py
This prevents issues where quipucords marks a server as complete, but
crashes before storing the results from that server.
Closes #343 .
=> Make InspectResultCallback transactions atomic

quipucords/scanner/network/inspect.py, roles/redhat_release/tasks/main.yml
This should run 3x faster than the corresponding role in rho because this
implementation is deduplicated and collects its information from rpm only
once instead of using three separate rpm commands.
Closes #360.
=> Port redhat_release role from rho to quipucords

roles/etc_release/tasks/main.yml
- this also cleans up some of the `raw` shell outputs
- and deduplicates a lot of the behaviors
- and consolidates all the release files into a single var
- and prefixes all not-`etc_release_*` vars with `internal_`
Closes #353.
=> Rewrite etc_release role with more rigorous 'when' checks

Makefile, README.rst, docs/source/man.rst, qpc/cli.py, qpc/messages.py, qpc/request.py, qpc/server/__init__.py, qpc/server/commands.py, qpc/server/login_host.py, qpc/server/logout_host.py, qpc/server/tests_login.py, qpc/server/tests_logout_host.py, qpc/utils.py, quipucords/api/credential/view.py, quipucords/api/fact/view.py, quipucords/api/report_views.py, quipucords/api/scanjob/view.py, quipucords/api/signals/token_signal.py, quipucords/api/source/view.py, quipucords/api/urls.py, quipucords/quipucords/settings.py
- Creates a super user as part of `make server-init`.
- Establishes token endpoint at `api/v1/token-auth`. Supply POST of `{'username': <user>, 'password':<pass>}`
- Remaining endpoints for `api/v1/*` must be called with Authorization Header: `Authorization: Token <token>` [see link](http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication)
- Creates `qpc server login` cmd to get token
- Creates `qpc server logout` cmd to delete local token
- Adds Token authentication and Session authentication to all views. Requires users to be authenticated.
- Disables authentication during unit tests (i.e. `make test`)
=> Add token authentication to server. Closes #322.

roles/subman/tasks/main.yml
This should solve #438 and allow the scan to complete without encountering key errors if data is unavailable.
=> Only add facts file to dict if subscription manager is present.

client/src/components/app.js, client/src/components/content/content.js, client/src/index.js, client/src/routes.js
Optimize routing for a single update point under... ```/client/src/routes.js```. Removed the routes hardcoded under ```.../content/content.js```. Instead, add a route to the config.
The ```basename``` update is related to Django base directory updates after a product/production build and some curious refresh behavior.
No checks currently in place for duplicate entries. Depending on the number of routes, there may be some optimization required in the future.
Updates #434
=> UI Routing updates

quipucords/scanner/network/processing/eap.py, quipucords/scanner/network/processing/tests_eap.py
Per the discussion in #355, this change just ports over the post-processing in rho that detects the presence of fuse.
=> Add post-processing to check for fuse. Closes #355

docs/source/man.rst, qpc/cred/add.py, qpc/cred/edit.py
Be consistent on using dashes and the word separator for qpc options.
Close #475
=> Rename qpc cred become_* options to become-*

docs/swagger.yml
Mixed up type and description for Credentials "become_password".
closes #492 
@abaiken
=> Type and description for Credentials Swagger doc

.gitignore, Makefile, quipucords/api/fact/model.py, quipucords/api/fact/serializer.py, quipucords/api/fact/util.py, quipucords/api/fact/view.py, quipucords/fingerprinter/__init__.py, quipucords/quipucords/settings.py, quipucords/scanner/job.py, quipucords/scanner/manager.py
- Moved fact_collection_json into the fact_collection model instead of an external file.  This impacts the job, util, and fact view
- ScanJobs now reflect the status of the fingerprint processing.  Interrupted job logic will now cover fingerprint processing.  In other words, a scanjob is not complete until the fingerprint processing is complete.
Closes #377
=> Handle interrupted scans that have completed everything but fingerprint processing

quipucords/fingerprinter/__init__.py, quipucords/fingerprinter/tests_engine.py
Sample output: 
```
Remove duplicate network fingerprints by ['subscription_manager_id', 'bios_uuid']
Number network fingerprints before de-duplication: 25
Number network fingerprints after de-duplication: 25
Remove duplicate satellite fingerprints by ['subscription_manager_id']
Number satellite fingerprints before de-duplication: 167
Number satellite fingerprints after de-duplication: 167
Remove duplicate vcenter fingerprints by ['vm_uuid']
Number vcenter fingerprints before de-duplication: 109
Number vcenter fingerprints after de-duplication: 109
Merged network and satellite fingerprints using keypairs. Pairs: [(network_key, satellite_key)]=[('subscription_manager_id', 'subscription_manager_id'), ('mac_addresses', 'mac_addresses')]
Number network before: 25
Number satellite before: 167 …
```
=> Improve logging stats for fingerprint deduplication and merging

.travis.yml, bin/timeout_ssh, quipucords/scanner/network/inspect.py, quipucords/scanner/network/inspect_callback.py, quipucords/scanner/network/tests_network_inspect.py, roles/cpu/tasks/main.yml, roles/date/tasks/main.yml, roles/file_contents/tasks/main.yml, roles/subman/tasks/main.yml, roles/uname/tasks/main.yml, roles/virt_what/tasks/main.yml, test_util/crash.py, test_util/hang.py
Provide a custom ssh executable to Ansible that runs regular ssh
inside of 'timeout', and use this to add a timeout to every task. Add
infrastructure for testing this ssh executable by making it time out a
program that will hang forever. Also add a test for SSH crashes.
Closes #484 .
=> Timeout individual Ansible tasks

quipucords/scanner/network/inspect_callback.py, quipucords/scanner/network/processing/process.py, quipucords/scanner/network/processing/tests_process.py
Move logs for normal events from error to debug level. Also, include
the hostname of the host that triggred the log message in all logs, to
make it easier to reproduce and fix errors.
Closes #559 .
=> Improve logging in process.py

client/src/components/sources/addSourceWizard.js, client/src/components/sources/addSourceWizardConstants.js, client/src/components/sources/sources.js
Initial wizard steps added for updating sources, should only display basic sample copy. Since it affects the shared ```components/sources/sources.js``` file, checking it in early.
Need an opinion about where to place this component next round? Either leave it under -
- ```components/sources/..``` 
or place it under it's own  directiory like 
- ```components/addSourceWizard/..```
updates #534
=> UI Initial add sources wizard

quipucords/scanner/network/processing/process.py, quipucords/scanner/network/processing/tests_process.py
We need to handle the 'sudo: a password is required' message in the
controller, because we can't block it in Ansible.
Closes #623 .
=> Handle sudo error in the controller

qpc/messages.py
Currently there is no space after the `User name:` prompt and this is slightly annoying 🙄 . 
```
$ qpc server login
User name:admin
Password: (your cursor starts here)
```
=> Make user name prompt match password prompt

client/.env.development, client/.env.staging, client/README.rst, client/config-overrides.js, client/package.json, client/scripts/api.sh, client/src/services/userService.js
This PR adds the ability to run a containerized API against a generated local UI directory. 
**How to use & what to check**
1. run ``` $ npm run start:stage```
* You may have to wait as the Docker scripts recompile everything.
* Two browser tabs/windows should open, one broken (_see limitations below_), and the second, the login screen.
* You may have to clear the existing ```csrftoken``` authentication token/cookie 
2. Login
3. Edit a file with a visible change within the UI directory under ```[REPO]/client/src```. 
4. Focus back on the browser tab/window and navigate to https://localhost/client/index.html to refresh the screen (_see limitations below_). 
5. Your change should appear.
**Limitations:**
* Doesn't automatically refresh
* Django routing currently doesn't have index.html as …
=> UI: Container run build updates

quipucords/api/messages.py, quipucords/api/scanjob/tests_scanjob.py, quipucords/api/scanjob/view.py, quipucords/api/signals/scanjob_signal.py, quipucords/scanner/manager.py, quipucords/scanner/tests_manager.py
- Fixed logging for signal/manager
- Removed POST /jobs API.  Now must use POST /scans/{id}/jobs
- Updated test cases
=> Logging fixes and scan job API updates

quipucords/scanner/satellite/api.py, quipucords/scanner/satellite/five.py, quipucords/scanner/satellite/six.py, quipucords/scanner/satellite/tests_sat_five.py, quipucords/scanner/satellite/tests_sat_six.py
Adds the fix to `master` branch and Sat 5 interaction has been updated to interact like Sat 6.
=> Handle Satellite errors on a per system basis. Closes #792.

client/src/components/listStatusItem/listStatusItem.js, client/src/components/scans/scanListItem.js, client/src/components/sources/sourceListItem.js, client/src/styles/entitlements/_views.scss
=> UI: Update list views when items have 0 count

quipucords/quipucords/urls.py
Regex update for paths inside the UI ```client``` directory, related to page refresh.
The regex is a little specific, eventually could look at making it more generic since there may be a scenario where more routing/paths have to be added. But for now this fixes the immediate issue, and avoids conflicts with resources loaded under ```client```.
updates #690
=> UI: Minor client directory redirect

qpc/scan/job.py
When making the path in job.py, we need to cast the id as a string.
=> Cast the job id as a string. Closes #864

quipucords/scanner/network/inspect.py, quipucords/scanner/network/processing/__init__.py, quipucords/scanner/network/processing/eap.py, quipucords/scanner/network/processing/eap5.py, quipucords/scanner/network/processing/util.py, roles/jboss_eap5/tasks/main.yml
In addition, this PR
- Moves some common postprocessing code into `quipucords.scanner.network.processing.util`
- Marks two tasks as internal, since we don't use their output outside of Ansible.
Here's some sample output from a scan of a host with EAP 5 installed. This is what's logged when the scanner creates a fact collection just before sending the fact collection to the fingerprinter. The output is pretty-printed and only has the EAP 5 facts, but otherwise is the raw debug logging:
```
{
"eap5_home_candidates": [
"/opt/jboss/jbosseap-5.2.0/jboss-eap-5.2"
],
"eap5_home_version_txt": {
"/opt/jboss/jbosseap-5.2.0/jboss-eap-5.2": true
},
"eap5_home_readme_html": {
"/opt/jboss/jbosseap-5.2.0/jboss-eap-5.2": true
},
"eap5_home_ls_jboss_as": {
"/opt/jboss/jbosseap-5.2.0/jboss-eap-5.2": [ …
```
=> Add network postprocessing for EAP 5 facts

quipucords/fingerprinter/jboss_eap.py, quipucords/scanner/network/processing/eap5.py
Add EAP 5 support to the fingerprinting engine, using the network scan support from the previous PR.
Here's the output from a scan of an EAP 5 system, cleaned up:
```
{
...
"products": [
{
"name": "JBoss EAP",
"presence": "present",
"version": [
"EAP 5"
],
"metadata": {
"source_id": 2,
"source_name": "sonar-jbosseap-rhel-5-vc",
"source_type": "network",
"raw_fact_key": "jboss_eap_running_paths/jboss_eap_packages/jboss_eap_locate_jboss_modules_jar/eap_home_ls/eap5_home_version_txt/eap5_home_readme_html"
}
},
...
],
"report_id": 18
}
```
Closes #850 .
=> Detect EAP 5 in the fingerprint engine

roles/jboss_eap5/tasks/main.yml
Closes #934 .
Adding one more role to the EAP 5 playbook to allow us to detect EAP 4 as well. We're actually getting at the same information at the same directory offset as before. What's new here is that we can extract the EAP version from the `run.jar` file even if we can't run the jar, by extracting just the part we need.
Sample output from an EAP 4 machine:
```
{
"host": "10.10.182.109",
"result": {
"results": [
{
"rc": 0,
"stdout": "Manifest-Version: 1.0\r\r\nSpecification-Title: JBoss\r\r\nCreated-By: 1.5.0_18-b02 (Sun Microsystems Inc.)\r\r\nSpecification-Version: 4.3.0.GA_CP10\r\r\nImplementation-Vendor-Id: http://www.jboss.org/\r\r\nImplementation-URL: http://www.jboss.org/\r\r\nClass-Path: ../client/getopt.jar\r\r\nAnt-Version: Apache Ant 1.6.5\r\r\nMain-Class: …
```
=> Add a task to gather version from run.jar without java

quipucords/scanner/network/processing/eap5.py
The postprocessing step mimics the code in https://github.com/mdvickst/ansible-scan-jboss/blob/master/scan-jboss.py , but works a slightly different way. The format of the line we care about is `Implementation-Version: <short-version> (SVNTag=<long-version> ...`. `SVNTag` can also be `CVSTag`.
We look for the `Implementation-Version:` line in the `MANIFEST.MF`, pull out the `<long-version>`, then use a lookup table to find the version of `JBoss EAP` it corresponds to.
When I scan my EAP 4 test VM, I get `'eap5_home_run_jar_manifest': {'/opt/jboss/jboss-eap-4.3': 'EAP-4.3'}` in the network facts dictionary.
Closes #935 .
=> Add network postprocessing for EAP 4 and 5 run.jar MANIFEST files

quipucords/api/fingerprint/model.py, quipucords/api/fingerprint/serializer.py, quipucords/api/report/tests_report.py, quipucords/fingerprinter/__init__.py, quipucords/fingerprinter/tests_engine.py
Remove: 
- vm_host_cpu_cores
- vm_host_cpu_threads
- vm_memory_size
- cpu_core_per_socket
- cpu_hyperthreading
- cpu_siblings
- virtualized_num_guests
- virtualized_num_running_guests
=> Remove fields from Report Summary. Part of #951

docs/source/beta.rst
Added the new section that contains the support contact info, including the log instructions. Chris and Dan had approved a rough draft of that text via Slack, but there are a few wording changes.
Added the support contact email address in the intro.
Made a few small changes here and there from another read of the entire document to spot typos and etc.
=> 977: adding support contact info, more fixes. Closes #977.

quipucords/api/scan/model.py, quipucords/api/scan/serializer.py, quipucords/api/scan/tests_scan.py, quipucords/api/scan/view.py, quipucords/api/scanjob/model.py
Update tests and make ScanJob keep the reference up to date.
Closes #982 .
=> Add most_recent_scanjob to Scan model

quipucords/api/scan/tests_scan.py, quipucords/api/scan/view.py
Closes #983 .
Also refactors and simplifies the scan tests a bit.
This PR depends on https://github.com/quipucords/quipucords/pull/1004 , and should only be merged after that one.
=> Make scans sortable by their latest scan job's status

quipucords/api/common/util.py, quipucords/api/scan/view.py, quipucords/api/scanjob/model.py, quipucords/api/scanjob/tests_scanjob.py, quipucords/api/source/model.py, quipucords/api/source/tests_source.py, quipucords/api/source/view.py
Add a new memeber to Source, which tracks the latest connection scan
job. Update it when a connection scan job is queued, add its start
time to the source's sorting fields, and update tests appropriately.
Closes #984 .
=> Make sources sortable by latest connection scan job time

qpc/scan/list.py
Since the self.req_params was being built by `_build_req_params`, when the page was getting added to the dictionary in `_handle_response_success`, it was getting overwritten when `_build_req_params` was called.
=> Make the req params dictionary in the init instead of in build_req_params. Closes #1023

roles/jboss_brms/tasks/main.yml, roles/jboss_eap/tasks/main.yml, roles/jboss_eap5/tasks/main.yml
This prevents issues when the list of items to substitute in the
command gets corrupted with something that contains shell glob
characters.
Closes #1088 .
=> Avoid shell glob expansion in some cat commands

quipucords/fingerprinter/jboss_fuse.py, quipucords/fingerprinter/tests_product_fuse.py
The output for the`deployments` endpoint for `10.10.181.132` is now: 
``` {
"name": "JBoss Fuse",
"version": null,
"presence": "absent",
"metadata": {
"source_id": 1,
"source_name": "cred1",
"source_type": "network",
"raw_fact_key": null
=> Fix non-invasive scan to report fuse absent on machines that detect amq jar file only. Closes #1139

quipucords/fingerprinter/jboss_brms.py, quipucords/fingerprinter/tests_product_brms.py, quipucords/scanner/network/processing/brms.py, quipucords/scanner/network/processing/test_brms.py, quipucords/scanner/network/processing/util.py, roles/jboss_brms/tasks/main.yml
We were already collecting the necessary data. This change plumbs it
through to the fingerprinter and update the version classification
logic.
Closes #1014
=> Detect BRMS version in non-invasive scan

quipucords/fingerprinter/jboss_brms.py, roles/jboss_brms/tasks/main.yml
Closes #1114 .
Output from scanning a BRMS system with extended search off:
```
{
"name": "JBoss BRMS",
"presence": "present",
"version": [
"RHDM 7.0.0"
],
"metadata": {
"source_id": 11,
"source_name": "sonar-rhdm-rhel-7-vc",
"source_type": "network",
"raw_fact_key": "jboss_brms_kie_in_business_central/jboss_brms_locate_kie_api/jboss_brms_manifest_mf"
}
}
```
And with extended search on:
```
{
"name": "JBoss BRMS",
"presence": "present",
"version": [
"RHDM 7.0.0"
],
"metadata": {
"source_id": 11,
"source_name": "sonar-rhdm-rhel-7-vc",
"source_type": "network",
"raw_fact_key": "jboss_brms_drools_core_ver/jboss_brms_kie_api_ver/jboss_brms_kie_in_business_central/jboss_brms_kie_war_ver/jboss_brms_locate_kie_api/jboss_brms_manifest_mf"
}
}
```
And an EAP system with no BRMS, for comparison: …
=> Add fingerprinting support for Red Hat Decision Manager 7.0.0

install/roles/docker/tasks/main.yml
=> Enable Docker for Systemctl on RHEL/Centos 7 Through Installer Playbook

docs/swagger.yml
The new version changed validation rules in a way that makes
docs/swagger.yml fail validation. Stick with the old one for now.
Closes #1199
=> Make ListPagination not require results

quipucords/fingerprinter/__init__.py, quipucords/fingerprinter/tests_engine.py
Closes #1196. 
Example for one system in deployments report for Satellite 6.2 source:
```
{
"id": 3253,
"report_id": 2,
"name": "sles12.prov.lan",
"os_name": "John's",
"os_release": "John's SUSE OS",
"os_version": "OS",
"infrastructure_type": "unknown",
"mac_addresses": [],
"ip_addresses": [],
"cpu_count": null,
"architecture": null,
"bios_uuid": null,
"subscription_manager_id": null,
"cpu_socket_count": null,
"cpu_core_count": null,
"system_creation_date": null,
"virtualized_type": null,
"vm_state": null,
"vm_uuid": null,
"vm_dns_name": null,
"vm_host": null,
"vm_host_socket_count": null,
"vm_cluster": null,
"vm_datacenter": null,
"products": [
{
"name": "JBoss EAP",
"version": null,
"presence": "absent",
"metadata": {
"source_id": 5,
"source_name": "S62Source",
"source_type": …
```
=> Enhance the is_redhat fact to report for satellite & vcenter. #1196

quipucords/fingerprinter/jboss_eap.py, quipucords/scanner/network/processing/eap.py
There were several separate issues that lead to this:
- We considered jboss_eap_running_paths to be conclusive evidence of
EAP presence. This commit changes that to be potential, because
that fact can also find Wildfly.
- We considered jboss-modules.jar to be conclusive evidence of EAP,
when it is present for Wildfly too.
- We used several other indicator files as evidence for EAP, even
though they are present for Wildfly too.
- We had a typing error that lead to us treating version.txt as
present (which is evidence for EAP) when it was in fact absent.
We don't detect the version of Wildfly with this PR because we specifically added code to this fingerprinter to disable detecting Wildfly versions. It should be possible to detect the Wildfly version if we remove that, but that's a separate …
=> Fix false identification of Wildfly as EAP

qpc/cred/tests_cred_add.py, qpc/cred/tests_cred_clear.py, qpc/cred/tests_cred_edit.py, qpc/cred/tests_cred_list.py, qpc/cred/tests_cred_show.py
Remove fake assert statements & rename variables to match command. Closes #1221
=> Clean up CLI credential tests. #1221

quipucords/scanner/manager.py
Closes #1236 
I know that this is a silly thing to not know but what file are these logs being saved too (I have always relied on reading the server terminal print outs) and when I looked in the settings.py file it seemed like the default was app.log (but mine is empty)? 
Anyways, as an example, this is what the output looks like. The annoying thing (or maybe it's helpful) is that this will continue to log if there are no jobs as long as the scan manager is still alive:
ie. While running scan jobs:
```
INFO Task 18 (inspect, network, NSmallSource, elapsed_time: 5s) - PROCESSING 10.10.182.81 - ANSIBLE ROLE virt
INFO Scan Manager Stats: current_scan_job=3. queue_length=3.
INFO Task 18 (inspect, network, NSmallSource, elapsed_time: 8s) - PROCESSING 10.10.181.132 - ANSIBLE ROLE cpu
```
After …
=> Add logging to determine if scan manager is alive

quipucords/scanner/network/processing/subman.py, quipucords/scanner/network/processing/test_subman.py
Closes #1278 
When running with become capabilities, the value of the std_out lines was a list containing an empty string in some cases. This was causing a traceback error when the processor attempted to split the value.
For example:
```
ERROR Task 2 (inspect, network, NBecomeSource, elapsed_time: 24s) - FAILED POST PROCESSING 10.10.181.154. Processor for subman_consumed got value {'rc': 0, 'stdout': '\r\n', 'stdout_lines': [''], 'stderr': 'Shared connection to 10.10.181.154 closed.\r\n', 'changed': True, '_ansible_no_log': False}, returned Traceback (most recent call last):
File "/Users/ashleybaiken/quipucords/quipucords/scanner/network/processing/process.py", line 134, in process
processor_out = processor.process(fact_value)
File …
```
=> Add check to make sure the subman_consumed value is not the empty string

quipucords/scanner/network/processing/ifconfig.py, quipucords/scanner/network/processing/test_ifconfig.py, roles/check_dependencies/tasks/main.yml, roles/ifconfig/tasks/main.yml
Closes #1281 
For the system `10.10.182.46`:
```
"ifconfig_mac_addresses": [
"00:50:56:9e:99:a8"
],
"ifconfig_ip_addresses": [
"10.10.182.46"
],
```
=> Fix if_config facts when using become-password

quipucords/fingerprinter/jboss_fuse.py, roles/jboss_fuse_on_karaf/tasks/main.yml
The facts `fuse_activemq_version  fuse_camel_version  fuse_cxf_version` were detected even if fuse was not installed on the system. Amq, camel, and cxf can be installed independently of fuse. If amq/camel/cxf are a part of fuse they should be under a fuse subdirectory, so I added a `grep fuse` to the ansible commands after locating the files. 
This appears to work when running scans on test servers: 
sonar-jbossamq-rhel-5-vc             -> no detection of amq, camel or cxf
sonar-jbosseap-fuse-rhel-6-vc      -> same detection of fuse, camel, and cxf as before
Closes #1361
=> jboss amq no longer mistaken for fuse amq

quipucords/api/report/renderer.py, quipucords/api/report/tests_report.py
Commas are replaced by semicolons in all gathered facts.
closes #1384
=> Commas Present in virt field for RHV host and other fields

client/public/index.html, client/public/manifest.json
Removes the branding from the HTML UI title tag
* clean up UI displayed title
closes #1401
=> UI: Fix branding title for HTML

docs/source/man.rst
Confusing typo in the man page
=> fix typo that messes up extended product search

.gitignore, README.rst, quipucords/scanner/manager.py, quipucords/scanner/tests_manager.py
This work intends to ensure that a job will:
- Cause gunicorn to timeout while canceling a job
- Really cancel a job (at least by the end of the inventory group)
- Everything else should work the same
Closes #1416
=> Remove joins from scan manager to fix scan job cancel

quipucords/api/scantasks/model.py, quipucords/scanner/satellite/six.py, quipucords/scanner/satellite/tests_sat_six.py, quipucords/scanner/satellite/utils.py
Restructures sat61 & sat62 scans. 
TODO: 
- Fix tests 
- Rename a few things 
- Restructure Sat5
=> Restructure satellite scans to isolate threading to http requests

roles/redhat_packages/tasks/main.yml
=> Replaced carriage return with a ; for certs on network scans (#1522)

Jenkinsfile
Only publish the specific junit file for each integration test stage on
the pipeline.
=> Publish specific junit files on the pipeline

Makefile
The staticfiles app automatically serve the static files over the
`STATIC_URL` setting when running Django's dev server. Even though
quipucords has URL entries to serve the UI it was not working with the
dev server because the staticfiles was taking precedence.
This change to the Makefile runs Django's dev server with the
`--nostatic` option which removes the automatic static serving and allow
the URLs defined on the quipucords.urls to work. This now allows running
the UI locally after running `make build-ui` using Django's dev server.
=> Enable running UI over Django's dev server

quipucords/api/scan/serializer.py, quipucords/api/scan/tests_scan.py
Closes #1854 
Testing:
Create an inspect scan with the default concurrency.
Run PATCH /api/v1/scans/{id}/ with body:
```
{
"scan_type": "connect",
"options": {
"max_concurrency": 200
}
}
```
The type should now be connect.
Now try with disabled options and no max concurrency: 
Run PATCH /api/v1/scans/{id}/ with body:
```
{
"scan_type": "inspect",
"options": {
"disabled_optional_products": {"jboss_fuse": true}
}
}
```
The type should now be inspect
=> Update scan type even if scan options are provided

quipucords/scanner/network/processing/__init__.py, quipucords/scanner/network/processing/dmi.py, quipucords/scanner/network/processing/test_dmi.py, quipucords/scanner/network/runner/roles/dmi/tasks/main.yml
Closes #1825 
To test you can run a large network scan on both master & on my branch & download the corresponding deployment reports. Then you can run the compare script against the two reports.
=> handle multi-line output of dmi system uuid command

quipucords/quipucords/urls.py
* feat(gui routing): issues/1920 add route for docs
Adds a `https://localhost:9443/client/docs` route that can be accessed either with `index.html` or without.
* #1920 
@jlprevatt et all. If the directory name needs to be altered from `docs` to something else, we can do that
=> feat(gui routing): issues/1920 add route for docs

Jenkinsfile
I edited the docker image name for the server to match what the installer expects. I then ran this branch through Jenkins and everything seemed to build without issue, and naming the artifact `quipucords_server_image.tar.gz`.
I think this should close out the rest of [quipucords-installer issue #10](https://github.com/quipucords/quipucords-installer/issues/10).
=> Changed installer image tar.gz name to match installer changes

Makefile, README.rst, quipucords/api/credential/view.py, quipucords/quipucords/settings.py, requirements.txt
Closes #1946 
Closes #1947 
You can find a comment to why I don't think these packages are needed in the issues listed above. 
**How I tested:**
- I was able to use the browsable api locally on:
- http://127.0.0.1:8000/api/v1/credentials/
- http://127.0.0.1:8000/api/v1/reports/1/deployments/
- http://127.0.0.1:8000/api/v1/reports/1/details/
- http://127.0.0.1:8000/api/v1/scans/
**When testing in container:**
**(On each os):** 
```
qpc cred show --name VCreds
qpc cred edit --name VCreds --username cmyers && qpc cred show --name VCreds
qpc cred add --name NKeyCred --type network --username root --password
qpc cred clear --name NKeyCred
```
=> Remove drf-generators & drf-url-filters

Jenkinsfile, quipucords/quipucords/release.py
This ensures that master has a higher release number than the previous release.
=> Bump release version to 0.9.1 for master

dev-requirements.txt, quipucords/quipucords/urls.py
* fix(gui routing): issues/1974 additional docs routes
* additional route for install and usage docs
* default to usage doc
- Adds a `https://localhost:9443/client/docs/use.html` route that can be accessed either with `use.html`, `index.html` or without.
- Adds a `https://localhost:9443/client/docs/install.html` route
This example highlights an updated GUI based on https://github.com/quipucords/quipucords-ui/pull/62
To test you'll most likely need to navigate directly to the routes
- `/client/docs/install.html`
- `/client/docs/use.html`
And they will most likely throw some type of 404... this is expected until the GUI PR is merged/integrated.
* #1974 
* relates to #1920 
@jlprevatt
=> fix(gui routing): issues/1974 additional docs routes

Dockerfile, Makefile, README.md, deploy/server_run.sh, deploy/setup_user.py
This PR allows you to set the username/password/email for the quipucords server.  To test follow the instructions for building and running the container documented here --> https://github.com/quipucords/quipucords#container-image.  However, you must replace the run command for the quipucords server with:
```
docker run --name quipucords --link qpc-db:qpc-link -d -e QPC_SERVER_USERNAME=kevan -e QPC_SERVER_EMAIL=kholdawa@redhat.com -e QPC_SERVER_PASSWORD=nicekevan -e QPC_DBMS_HOST=qpc-db -p 9443:443 -v $QPC_VAR_DATA:/var/data -i quipucords:0.9.1
```
You can then docker exec and cat the quipucords logs to see that your user was created.
Now, if you `docker rm -f quipucords` and re-run just the run command and view logs you should see that the user already exists and will not be recreated.
=> Add ability to set the username/password/email for a user during installation

pyproject.toml
When  https://github.com/reverbc/pylint-pytest/pull/22 gets merged we might
reenable this check.
=> Disable problematic pylint-pytest check

Dockerfile
```
=> ERROR [15/15] RUN make server-static                                   0.5s
------                                                                          
> [15/15] RUN make server-static:                                              
#19 0.329 /opt/venv/bin/python quipucords/manage.py collectstatic --settings quipucords.settings --no-input
#19 0.472 Traceback (most recent call last):
#19 0.472   File "/app/quipucords/manage.py", line 34, in <module>
#19 0.472     execute_from_command_line(sys.argv)
#19 0.472   File "/opt/venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
#19 0.472     utility.execute()
#19 0.472   File "/opt/venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 345, in execute
#19 …
```
=> Fix build with Docker on mac regarding /var/data directory

quipucords/fingerprinter/task.py, quipucords/scanner/satellite/utils.py, quipucords/scanner/vcenter/inspect.py
Improper usage introduced on these commits:
- f660946e8ba87108f838c47cc4d4484cfd97ee1e
- f7e73cb7d039f12cff61955f51d1c17008da40cb
When reviewing I suggest taking those into consideration (their diff will show the original formatting of the messages).
=> Fix incorrect usage of f-string

quipucords/fingerprinter/task.py, quipucords/fingerprinter/tests_fingerprint_task.py
Force optional VCenter fingerprint facts to always return
Force optional Satellite fingerprint facts to always return
Modifies test_scan_all_facts_with_null_value_in_process_vcenter_scan
Modifies test_scan_all_facts_with_null_value_in_process_satellite_scan
=> Fingerprint facts for Vcenter and Satellite and theirs tests 

.dockerignore, Makefile
* Fix a typo in `.dockerignore` that may produce the side-effect of leaving the container image with UI broken (blank screen after logged in). `quipucords/quipucords/template` -> `quipucords/quipucords/templates`
* Create a Makefile rule to build the container image by passing the `UI_RELEASE` - Note: should we keep the release number inside the `ARG UI_RELEASE`?
=> [Discovery 173] fix container image build

.github/workflows/build.yml, .github/workflows/test.yml, dev-requirements.txt, requirements.in, requirements.txt
Since discovery 1.0.0, ansible is **always** using `paramiko` to connect to hosts (regardless of the option we chose when configuring sources).
A regression introduced in paramiko 2.9 is the culprit for RHEL-6 not being properly detected.
=> [DISCOVERY-177] - Fix older RHEL detection bug

dev-requirements.txt, requirements.in, requirements.txt
Later versions of paramiko are impairing detection of hosts using
only [legacy cryptographic algorithms](http://www.openssh.com/legacy.html).
=> Downgrade paramiko to 2.7.2

Dockerfile, Makefile
The layer fetching UI on quay.io is already cached with an older version of the UI. In order to update it we will need to force it to update by changing UI_RELEASE value.
=> Force quipucords-ui to version 0.11.1

Dockerfile, quipucords/quipucords/settings.py
This is a security risk for servers accessible outside of the user network.
Fix DISCOVERY-198.
NOTE: UI templates also require a small change - otherwise the application will always crash on login page if DEBUG mode is disabled.
=> [DISCOVERY-198] Allow turning off django DEBUG mode

docs/swagger.yml
- updated swagger.yml MUST pass swagger validation (running with `make serve-swagger`  should be served on http://localhost:5050/docs/api)
- must not break `yarn start` on QUIPUCORDS-UI side
Suggestion: on quipucords-ui edit [FILE variable](https://github.com/quipucords/quipucords-ui/blob/68ea5d9e4e5907ce35c87254ca315bccc1dfd2ae/scripts/api.sh#L301) to point to the modified version here and then run `yarn start`
=> [DISCOVERY-202] - Add OpenShift integration info to OpenApi spec

Dockerfile, quipucords/quipucords/environment.py
Fix: DISCOVERY-239
`curl --insecure  https://localhost:9443/api/v1/status/ | jq '.server_version'`
the final part of the version should match current commit version instead of "master"
=> [DISCOVERY-239] - update server-version upstream

Makefile
The -P option to grep for handline perl-flavored regex is not included in the default grep on MacOS. While a different can be installed with brew to support perl, there is nothing perl specific in that regexp in the Makefile that can't be handled with ERE, so using grep -E (aka egrep) does the trick and works on both Linux/CentOS/RHEL and MacOS.
=> chore: fix Makefile clean to work on MacOS

quipucords/api/common/entities.py, quipucords/api/common/serializer.py, quipucords/api/insights_report/serializers.py, quipucords/api/insights_report/test_serializers.py
Insights require some fields to be arrays, so instead of using a class in Meta to force this conversion, create method that will return the entity instance as a list.
This is a recurrent problem, this will be used again to send network_interfaces information to SystemProfile.
=> refat: simplify entity returning as forcedlist

quipucords/manage.py
Starting scans on MacOS cause an exception pertaining to the Django app not properly initialized and unable to use gettext for defining messages.
The issue is that for the scanner jobs, we create a Process for each. With Processes, MacOS (and Windows) spawn a new process instead of a fork as in Linux.  With the former, the Django is not passed through, so in which case, we need to import django and do a django.setup() similar to how a Celery app config is initialized.
This needs to be done early before any of the other imports are done like importing api models where gettext is used that requires django to be setup.
=> fix(scans): Scans raise exceptions when running on MacOS.

quipucords/scanner/network/utils.py
The template for raw facts was incorrectly cached, overriding the null values with the values of each system.
This was causing issues on scans where some data should be missing.
Fix: DISCOVERY-262
=> fix(netscan): Avoid data duplication in raw facts

quipucords/fingerprinter/task.py, quipucords/fingerprinter/tests_fingerprint_task.py, quipucords/scanner/network/runner/roles/subman/tasks/main.yml, quipucords/tests/integration/test_network_scan.py
subscription-manager-id fingerprint (and the homonymous field in insights reports) was incorrectly mapped to subman_virt_uuid in network scanner.
This adds a new fact "subscription_manager_id" that collects that value and maps it to its fingerprint.
Fix: DISCOVERY-264
=> fix: Incorrectly mapped fact in network scanner

quipucords/api/status/misc.py, quipucords/utils/__init__.py, quipucords/utils/misc.py
Keeping PyCharm and the Python demi-gods happy, moving functions out of __init__.py and into separate files.
=> chore(refact): Moving functions out of __init__.py

poetry.lock, pyproject.toml, quipucords/api/insights_report/serializers.py, quipucords/api/status/misc.py, quipucords/quipucords/environment.py, quipucords/quipucords/tests_environment.py
This might be seem as a bugfix too, because quipucords wasn't able to generate insights reports with a big number of hosts.
create a report with 1000 fingerprints
```
poetry run quipucords/manage.py shell
>>>from tests.factories import DeploymentReportFactory
>>>DeploymentReportFactory.create(number_of_fingerprints=1000, status="completed")
```
take note of the report id generated, exit shell and then open a browser, login to quipucords and access this url
```
https://<quipucords-host>:<quipucords-port>/api/v1/reports/<REPORT-ID>/insights/?format=tar.gz
```
Before applying this PR quipucords won't be able to render a report so big.
=> perf(insights-report): speed up generation of tags

quipucords/api/connresult/serializer.py, quipucords/api/inspectresult/serializer.py
fix: minor typos in doc strings
Replacing serialzer with serializer.
=> fix: minor serialzer typos in doc strings

quipucords/api/scanjob/model.py
fix: extra % character in logging message
The system_fingerprint_count included a % prefix to the count in the log message.
INFO Job 3 (inspect, elapsed_time: 6s) - FAILURE STATS. Stats: systems_count=10, systems_scanned=0, systems_failed=0, systems_unreachable=10, system_fingerprint_count=%0
That should just be:
INFO Job 3 (inspect, elapsed_time: 6s) - FAILURE STATS. Stats: systems_count=10, systems_scanned=0, systems_failed=0, systems_unreachable=10, system_fingerprint_count=0
=> fix: extra % character in logging message

quipucords/api/scan/model.py, quipucords/api/scanjob/tests_scanjob.py
This was missed in earlier PR converting to JSONField, No need to do json.loads on search_directories.
=> chore: remove unneeded json.loads for search_directories

quipucords/fingerprinter/tests_fingerprint_task.py
fix: removed unneeded json.dumps for a Source hosts
Remove an unneeded json.dumps for the hosts of a Source. Source hosts are now Python objects. This passed earlier because the hosts field was not being used in those tests.
=> fix: removed unneeded json.dumps for a Source hosts

quipucords/api/credential/serializer.py, quipucords/api/credential/tests_credential.py
CLI is ALWAYS sending ssh_keyfile for credentials (and setting it as null [1] when auth_token or password are informed)
[1]: https://github.com/quipucords/qpc/blob/688d63a2350ea4ebaa20c3052d18f4d1267e1191/qpc/cred/utils.py#L83-L84
=> fix(CredentialSerializer): support ssh_keyfile=null in payloads

.gitignore, poetry.lock, pyproject.toml, quipucords/quipucords/settings.py
After a normal `poetry install`, set and export `QPC_ENABLE_DJANGO_EXTENSIONS=True` into your environment to enable Django Extensions and gain access to new management commands like `shell_plus`.
See the Django Extensions docs for usage details: https://django-extensions.readthedocs.io/
To start a Jupyter Notebook server, for example, you might run:
```
QPC_ENABLE_DJANGO_EXTENSIONS=True poetry run ./quipucords/manage.py shell_plus --notebook
```
I included `notebook` as a dev dependency in this PR, but please note that it pulls in _several_ more package dependencies. 😬 If this is too much, please let me know, and I can drop that commit and just install it manually in my local environment.
Also, I added a `.gitignore` line for a top-level `notebooks` directory. As a matter of habit, when …
=> add (optional) django extensions for devs

quipucords/quipucords/settings.py, quipucords/scanner/job.py, quipucords/scanner/manager.py, quipucords/scanner/network/connect.py, quipucords/scanner/task.py
In a separate branch, I'm trying to understand and tease apart some of the scan management code so that I can start replacing local threads/processes/pools with Celery tasks. This PR just yanks some cleanup commits from that other branch so that branch doesn't grow too big too fast. There will be many more like this to make Celery a reality for quipucords.
- Replace more of those deep `os.environ` calls with more sensible Django settings.
- Fix or expand some old docstrings as I encounter them. I'm also adding a few type hints because the types are sometimes not at all obvious (or even counterintuitive based on variable names).
- Extract a few class methods into standalone functions because I expect soon I will need to call them from other places.
=> misc scan manager (and related) cleanups

conftest.py, quipucords/quipucords/settings.py, quipucords/scanner/job.py, quipucords/scanner/manager.py, quipucords/tests/dummy_scan_manager.py
With this small change we can finally run tests synchronously.
The "timeout" related code was also removed from DummyScanManager because that same behavior in tests can be achieved through pytest-timeout (with --timeout=15).
=> refactor(ScanJobRunner): unbind "runner" logic from multiprocessing

Dockerfile
fix: fix broken build-container on Mac M1
make build-container was failing on M1 Macs. Dockerfile could not install psycopg2_binary as it tries to build it for aarch64. Was missing gcc, postgresql-devel and the python39-devel packages.
=> fix: fix broken build-container on Mac M1

quipucords/api/credential/serializer.py, quipucords/api/credential/test_serializer.py, quipucords/api/credential/tests_credential.py
The extra validation for non expected keys was both poorly ported from the original CredentialSerializer implementation and unnecessary. DRF Serializers default behavior is to completely ignore unexpected data, so the validation was only required when everything was just one huge serializer.
updates DISCOVERY-287
context here: https://url.corp.redhat.com/95032f2
=> fix(CredentialSerializer): remove custom "strict" validation

quipucords/quipucords/settings.py
Treating this as a "fix" as this choice can cause confusion for end users.
=> fix: use default port for postgresql

.gitignore
I'm not sure when or what triggered this change, but recently (within the last week maybe?), `flakeheaven` has been using a local `.flakeheaven_cache` directory in the project root.
=> refactor(.gitignore): ignore flakeheaven cache dir

quipucords/api/credential/serializer.py, quipucords/api/credential/test_serializer.py, quipucords/api/credential/tests_credential.py
Restore the very weird middle-ground validation we had for CredentialSerializer:
Don't allow extra fields UNLESS they are set to `None`.
I personally would rather have a FULL STRICT validation or keep DRF default, but CLI would need to change accordingly.
=> DISCOVERY-287 - strict credential validation

quipucords/api/credential/serializer.py
NOTE: sorry for the ridiculous branch name. yet another credential serializer god knows how many at this point
=> perf(CredentialSerializer): avoid subclassing logic when not needed

quipucords/scanner/job.py, quipucords/scanner/runner.py
More code cleanup and logic separation to clear the way for Celery tasks.
The reason I have separated **finding** the class from **instantiating** the class is that I plan to use this later with Celery, where passing the heavy model objects into task functions isn't achievable. I haven't finished prototyping that (in a separate branch), but _I think_ this is a step in that direction.
=> more scanner runner cleanup

quipucords/quipucords/settings.py, quipucords/quipucords/test_settings.py
chore: adding support for DJANGO_SECRET_KEY env variable.
This is necessary when the application keys are coming from OpenShift project secrets through the environment
=> chore: adding support for DJANGO_SECRET_KEY env variable.

quipucords/api/details_report/view.py, quipucords/api/merge_report/view.py, quipucords/api/scan/tests_scan.py, quipucords/api/scanjob/tests_scanjob.py, quipucords/api/scantask/model.py, quipucords/api/scantask/tests_scantask.py, quipucords/api/source/tests_source.py, quipucords/api/source/view.py, quipucords/scanner/job.py, quipucords/scanner/network/processing/test_process.py, quipucords/scanner/test_util.py
This PR moves some code from `SyncScanJobRunner` to regular functions so that we can reuse them later with Celery tasks.
I'm also tidying up a little bit of related code along the way. It may help to look at the individual commit diffs.
=> split up job runner run method

quipucords/api/scan/view.py, quipucords/api/scanjob/model.py, quipucords/api/scanjob/tests_scanjob.py, quipucords/api/scanjob/view.py, quipucords/api/scantask/model.py, quipucords/api/scantask/tests_scantask.py, quipucords/scanner/job.py, quipucords/scanner/manager.py, quipucords/scanner/network/tests_network_inspect.py, quipucords/scanner/test_util.py, quipucords/scanner/vcenter/tests_vc_inspect.py
This is a legibility improvement, IMO. Readability counts, and explicit is better than implicit.
Previously, `ScanJob` and `ScanTask` had methods like `start` and `fail`, but those methods don't _actually_ start or fail their respective jobs and tasks. They simply update (with conditional sanity-checking) their _status values_ in the database. Other code is responsible for actually starting, failing, etc. the functions that perform work for these jobs and tasks.
These new names still aren't perfect, but I think they are much clearer than the old names and should cause me (and hopefully anyone else new to our code) less confusion.
=> rename model status-setting methods

quipucords/scanner/job.py, quipucords/scanner/network/connect.py, quipucords/scanner/network/connect_callback.py, quipucords/scanner/network/inspect.py, quipucords/scanner/network/inspect_callback.py, quipucords/scanner/network/utils.py, quipucords/scanner/runner.py
As we migrate functionality into Celery tasks, we will no longer be passing multiprocessing `Value` interrupt-handling objects throughout the system. We will need a completely different mechanism to stop processing activity in asynchronous Celery workers.
I introduced this change in a local branch where I am working on those Celery tasks, but I pulled it out to this separate branch/PR for early review in isolation. For now, I am simply wrapping all uses of the interrupt object with conditional checks. If it's not set, we simply proceed as though we're not being interrupted.
=> refactor: gracefuly handle when interrupt signal is not set

quipucords/api/credential/tests_credential.py
test: Test failures for all cred type updates
Added tests so we test that changing cred_type for all of the DataSource types will return in a failure.
=> test: Test failures for all cred type updates

quipucords/api/insights_report/serializers.py, quipucords/quipucords/environment.py, quipucords/quipucords/tests_environment.py
Swatch expects tags namespace to be "qpc", as exemplified in this query: https://github.com/RedHatInsights/rhsm-subscriptions/blob/706979cd1a44e76bec00ff237bf8727fa7df0dd6/src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java#L93-L138
Also backport fix #2372
=> facts namespace should be qpc

Dockerfile
fix: Allow git to run in /app
With the Exception catch removed while doing a git rev-parse for determining the commit sha for the server version (see https://github.com/quipucords/quipucords/commit/1c415df5bf0b4d5caca93d2d4de36b5ba8cfb805), git fails with the following error while running in OpenShift:
fatal: detected dubious ownership in repository at '/app'
This pertains to file/directory ownership vs the user running the git command.  The fix to this is to tell git that /app is a safe directory to run git in and proceed normally. The git config adds /app as a safe directory to the user's .gitconfig file.
=> fix: Allow git to run in /app

quipucords/quipucords/settings.py
This change should resolve the following warning emitted during test runs (and also probably at server startup):
RemovedInDjango50Warning: The USE_L10N setting is deprecated. Starting
with Django 5.0, localized formatting of data will always be enabled.
For example Django will display numbers and dates using the format of
the current locale.
warnings.warn(USE_L10N_DEPRECATED_MSG, RemovedInDjango50Warning)
This setting is already enabled by default in Django 4.2, the version quipuicords is already using. See also:
https://docs.djangoproject.com/en/4.2/topics/i18n/formatting/
=> fix: remove deprecated USE_L10N setting

quipucords/tests/api/source/test_serializer.py
This change should resolve the following warning emitted during test runs:
PytestUnknownMarkWarning: Unknown pytest.mark.xpass - is this a typo?
You can register custom marks to avoid this warning - for details,
see https://docs.pytest.org/en/stable/how-to/mark.html
2023-06-05 update: Instead of `xfail`, we decided simply to use `skip` on this test because we agree there is no value in attempting to run it. Another issue exists here to reconsider and fix the underlying implementation: https://issues.redhat.com/browse/DISCOVERY-352
=> fix: skip test_openshift_source_update since it does not make sense

quipucords/quipucords/settings.py
This change should resolve the following warning emitted during test runs (and also probably at server startup):
RemovedInDjango51Warning: The STATICFILES_STORAGE setting is deprecated. Use STORAGES instead.
warnings.warn(STATICFILES_STORAGE_DEPRECATED_MSG, RemovedInDjango51Warning)
The new STORAGES setting is supported by Django 4.2, the version quipuicords is already using. See also:
https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-STORAGES
=> fix: replace deprecated STATICFILES_STORAGE setting

quipucords/api/inspectresult/model.py, quipucords/scanner/openshift/inspect.py, quipucords/tests/scanner/openshift/test_inspect.py
One of the premisses of OCP scanner "extra facts" is that they should not break a scan if an API error is caught. When that happens, an OCPError entity would be collected instead of the extra fact. 
This behavior was broken because OCPErrors were not able to be properly encoded as json.
=> fix(ocp): properly encode potential OCP error entities

.github/workflows/build.yml
Forks don't have access to secrets and can't complete this step.
=> Skip upload container image step on PRs from forks

.github/workflows/build.yml
Apparently 097a2c8f1bfa167caf85d304f1805776739b3d53 doesn't work as I wanted. Let's try again.
=> Skip upload container image step on PRs from forks... for real

Dockerfile, Dockerfile.scan-target
UBI 9 has stricter criptographic policies for ssh. We need to explicitly set those to "legacy mode" for detection of rhel 5 and 6.
=> compatibility with older RHELs

quipucords/api/connresult/model.py, quipucords/api/deployments_report/model.py, quipucords/api/details_report/model.py, quipucords/api/inspectresult/model.py, quipucords/api/scan/model.py, quipucords/api/scanjob/model.py, quipucords/api/scantask/model.py, quipucords/api/status/model.py, quipucords/scanner/job.py, quipucords/scanner/tasks.py, quipucords/tests/api/scantask/test_model.py
some `__str__` methods are making calls to related models, which can quickly cascade into a nasty N+1 problem.
We don't need all this info in `__str__` anyways, just remove it and log explicitly when required.
relates to JIRA: DISCOVERY-220
=> perf: remove all dunder str methods from models

pyproject.toml, quipucords/api/common/common_report.py, quipucords/api/common/util.py, quipucords/api/credential/serializer.py, quipucords/quipucords/settings.py, quipucords/scanner/network/connect.py, quipucords/scanner/network/inspect.py, quipucords/scanner/network/utils.py, quipucords/tests/api/test_vault.py, quipucords/tests/scanner/network/test_network_connect.py, quipucords/tests/scanner/network/test_network_inspect.py, scripts/test_generate_sudo_list.py
and enable a ruff checker to ensure we keep true to the one and only way to handle paths in python.
ALL PRAISE pathlib.Path.
=> chore(style): prefer pathlib over os.path

.github/workflows/build.yml
Do not skip pushing to the registry when the original repo appears to be a fork; this job now always attempts to push when it reaches this step. This means the job may fail if a forked repo does not correctly configure its variables and secrets.
`IMAGE_NAME` and `REGISTRY` are now optional variables that forks may set in their GitHub project settings to override to use another registry or image name.
To verify that the variables works as expected, I opened an identical PR in my up-to-date fork (https://github.com/infinitewarp/quipucords/pull/1).
* The first time the build job ran, I did not have any custom variables or secrets set. As expected, the build job failed (https://github.com/infinitewarp/quipucords/actions/runs/5615107995/job/15214675647?pr=1). The build job used the default …
=> push to registry regardless of fork, use more variables

.github/workflows/build.yml
git chery-pick these commits from main:
* ff5f0f09
* 0977427c
* b44d7e58
These commits were originally introduced by https://github.com/quipucords/quipucords/pull/2419, but we want to include them in the 1.3 release branch.
Relates to JIRA: DISCOVERY-388
https://issues.redhat.com/browse/DISCOVERY-388
=> 1.3 cherry pick workflow fixes

.github/workflows/build.yml, pyproject.toml
git chery-pick these commits from main:
* ff5f0f09
* 0977427c
* b44d7e58
These commits were originally introduced by https://github.com/quipucords/quipucords/pull/2419, but we want to include them in the 1.3 release branch.
This PR also adds one commit to update the project version to `1.3.1` because we intend to tag `1.3.1` after this PR merges.
Relates to JIRA: DISCOVERY-388
https://issues.redhat.com/browse/DISCOVERY-388
=> 1.3 cherry pick and update to 1.3.1

Makefile, requirements-build.in, requirements-build.txt
This was required for Kombu < 5.3, but we are now on Kombu 5.3.1.
=> chore: remove setuptools<67 requirement now that kombu has been updated

Makefile, requirements-build.in, requirements-build.txt
`git cherry-pick` bb74f5a9
Back-porting https://github.com/quipucords/quipucords/pull/2429 from `main` to `release/1.3` branch.
=> fix: strip [extras] from package names before passing to pybuild-deps, stop ignoring errors from pybuild-deps

poetry.lock, pyproject.toml
chore: Pinning debugpy to version 1.6.7
- Apparently 1.6.8 wasn't a fully-blown/published release, it was just a link to the 1.6.7 commit.
=> chore: Pinning debugpy to version 1.6.7

pyproject.toml
Relax the rules for pydocstyle checks. Allow having empty `__init__` methods.
=> chore(lint): disable pydocstyle check for __init__ methods

quipucords/quipucords/settings.py, quipucords/scanner/openshift/api.py, quipucords/tests/scanner/openshift/test_api.py
This fixes an issue I encountered when trying to scan an OpenShift source where the cluster _does not_ have ACM installed.
Previously, the scan would fail and report an unhandled exception like this in the server logs:
```
ERROR 2023-08-21 15:32:26,947 model 39918 123145369550848 Job 7, Task 2 of 3 (inspect, openshift, shrocp4upi412ovn, elapsed_time: 4s) - Unexpected failure occurred. See context below.
SCAN JOB: ScanJob object (7)
TASK: ScanTask object (14)
SOURCE: Source object (3)
CREDENTIALS: [['Credential object (5)']]
INFO 2023-08-21 15:32:26,948 model 39918 123145369550848 Job 7, Task 2 of 3 (inspect, openshift, shrocp4upi412ovn, elapsed_time: 4s) - FAILURE STATS. Stats: systems_count=7, systems_scanned=6, systems_failed=0, systems_unreachable=0
ERROR 2023-08-21 15:32:26,949 model …
```
=> fix: handle when openshift source has no ManagedCluster API (no ACM)

quipucords/scanner/openshift/api.py
This should handle an uncommon (maybe?) situation wherein we find an operator from the subscriptions API that was not also found in the cluster service versions API.
Specifically, I encountered this problem when attempting to scan an internal shared cluster (`shrocp4upi49`). The inspection crashed out with an unhandled `KeyError` due to finding an operator named `amq-streams` but our keys from the CSV API were:
```
container-security-operator.v3.8.8
devworkspace-operator.v0.19.1-0.1682321189.p
elasticsearch-operator.5.5.11
jaeger-operator.v1.42.0-5
kiali-operator.v1.57.7
openshift-gitops-operator.v1.6.7
openshift-pipelines-operator-rh.v1.7.3
quay-operator.v3.8.8
servicemeshoperator.v2.3.3
web-terminal.v1.4.0
amq-broker-operator.v7.11.1-opr-2
gitlab-runner-operator.v1.12.0 …
```
=> fix: handle uncommon case when we find an operator not listed in service versions

quipucords/quipucords/settings.py
I'm getting real tired of seeing walls of these messages flood my local logs as I am developing and scanning sources...
```
warnings.warn(
/Users/brasmith/Library/Caches/pypoetry/virtualenvs/quipucords-A54Z8Zh8-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.cluster-name.internal-example.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
warnings.warn(
/Users/brasmith/Library/Caches/pypoetry/virtualenvs/quipucords-A54Z8Zh8-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.cluster-name.internal-example.com'. Adding …
```
=> feat: add optional QPC_URLLIB3_DISABLE_WARNINGS to disable warning noise

quipucords/scanner/openshift/inspect.py, quipucords/scanner/openshift/metrics.py, quipucords/tests/integration/test_openshift_scan.py, quipucords/tests/scanner/openshift/test_inspect.py
feat(OpenShift): Enhance OCP Inspection to query Node metrics
- With this enhancement, we now fetch whether or not a node is running with hyperthreading enabled or not.
- Metrics facts get added to the "cluster" section in the details report.
Leverages foundational work here: https://github.com/quipucords/quipucords/pull/2438
=> Enhance OCP Inspection to query Node metrics

quipucords/scanner/network/processing/eap.py
Relates to JIRA: DISCOVERY-412
https://issues.redhat.com/browse/DISCOVERY-412
=> fix: add another special case for "id: 'jboss': no such user" that we've seen in the wild

Makefile
This is part of DISCOVERY-392 .
We want to build container on Jenkins agent. We _could_ modify `get-pipeline-data.py` to assume different container URL when PR is a fork, but that will only complicate a script that is already getting complicated. I think it's better to create a container with a name that already matches what we would have pulled in from quay.
Also, allowing user to set custom container name sounds like a reasonable feature anyway. This allows for easy building of multiple containers locally, or whatever.
=> Allow user to override default container tag

docker-compose.yml
Thank you @mirekdlugosz for spotting this!
I spun up a new set of containers with docker-compose, confirmed that the Celery config was enabled, created a network source, and performed a network scan (this uses the Celery workers), waited for it to complete successfully, and downloaded and reviewed the reports. As far as I can tell, everything worked normally without the exposed port.
=> refactor: remove unnecessary exposed port for celery worker container in docker-compose

quipucords/tests/api/reports/test_reports.py
Among other recent changes, I was trying to update `test_reports.py` but struggled with some test assertions. This PR very slightly improves this test class:
* do not use plain `assert` style assertions inside a unittest test; you will lose the explanation message
* set maxdiff to increase the diff verbosity on assertion equality failures
=> slightly improve test_reports.py

docs/swagger.yml, quipucords/api/common/entities.py, quipucords/api/insights_report/serializers.py, quipucords/tests/api/common/test_entities.py
This function was deprecated on hbi side some time ago. Currently, if we want to send instaled_products information we have to do it through system profile.
=> refactor(insights): remove rh_installed_products

quipucords/scanner/network/processing/cloud_provider.py, quipucords/tests/scanner/network/processing/test_cloud_provider.py
Inventory UI expects GCP tag instead of GOOGLE and Discovery should use the same value.
Relates to JIRA: DISCOVERY-414
https://issues.redhat.com/browse/DISCOVERY-414
=> fix(insights): report correct cloud provider tag

.gitignore, Dockerfile, quipucords/quipucords/settings.py, quipucords/tests/quipucords/test_settings.py
Initially secret, app.log, and sqlite files were being saved (by default) to quipucords/quipucords. That's... unwise, as this path is reserved for source code and a "vanilla" development environment would not have the env vars customizing the path to save this files set.
=> Change default path for secret, logs and sqlite

.gitignore, Dockerfile, quipucords/api/reports/reports_gzip_renderer.py, quipucords/api/reports/view.py, quipucords/constants.py, quipucords/quipucords/settings.py, quipucords/scanner/network/inspect.py, quipucords/tests/integration/conftest.py, quipucords/tests/integration/test_network_scan.py, quipucords/tests/quipucords/test_settings.py, quipucords/tests/scanner/network/test_network_inspect.py
Backport #2462 to release 1.3
the following commits were cherry-picked
cfbc1a1f2a6473fccacce59eb5ce876f12f12e5f
d09ad68ef33a9e850c4023f76b5e27232bece46f
e4c7be1943ffbdf0ebde69fcd0aace4f3b668ee7
c805c383c679f8eaf477a53670430311fb5a047d
Relates to JIRA: DISCOVERY-415
=> feature: add ansible logs to report tarball

pyproject.toml
Picking the recent change from `release/1.3` to `main`:
```
git checkout main
git pull
git checkout -b cherry-pick-1.3-to-main
git cherry-pick aeae70f8
```
It looks like aeae70f8 is the only recent change that exists exclusively in the `release/1.3` branch. Everything else has been ported to or from `main`.
=> chore: bump to version 1.3.4

quipucords/scanner/network/processing/cloud_provider.py, quipucords/scanner/network/processing/cpu.py, quipucords/scanner/network/processing/dmi.py, quipucords/scanner/network/processing/jws.py, quipucords/scanner/network/processing/subman.py, quipucords/scanner/network/processing/system_purpose.py, quipucords/scanner/network/processing/util.py, quipucords/scanner/network/processing/virt.py, quipucords/scanner/network/runner/roles/check_dependencies/tasks/main.yml, quipucords/scanner/network/runner/roles/cpu/tasks/main.yml, quipucords/scanner/network/runner/roles/date/tasks/main.yml, quipucords/scanner/network/runner/roles/dmi/tasks/main.yml, quipucords/scanner/network/runner/roles/etc_release/tasks/main.yml, quipucords/scanner/network/runner/roles/memory/tasks/main.yml, quipucords/scanner/network/runner/roles/redhat_packages/tasks/main.yml, quipucords/scanner/network/runner/roles/redhat_release/tasks/main.yml, quipucords/scanner/network/runner/roles/subman/tasks/main.yml, quipucords/scanner/network/runner/roles/uname/tasks/main.yml, quipucords/scanner/network/runner/roles/virt/tasks/main.yml, quipucords/scanner/network/runner/roles/virt_what/tasks/main.yml, quipucords/tests/scanner/network/processing/test_cloud_provider.py, quipucords/tests/scanner/network/processing/test_cpu.py, quipucords/tests/scanner/network/processing/test_date.py, quipucords/tests/scanner/network/processing/test_dmi.py, quipucords/tests/scanner/network/processing/test_system_purpose.py
This changes some processing to read the last line of stdout instead of the first or to process stdout lines in reverse order. This should avoid some problems where a badly configured target system emits unexpected lines to stdout upon establishing the ssh connection.
Relates to JIRA: DISCOVERY-407
https://issues.redhat.com/browse/DISCOVERY-407
=> fix: avoid unexpected stdout in network scan Ansible result

conftest.py, quipucords/api/management/commands/randomize_db_sequences.py
Randomizing database sequences to:
1. Force tests to not hardcode ids
2. Avoid false positive tests passing only because models had coinciding ids
3. Attempt to simulate a more real world like scenario
In the future this fixture could be an util used to highlight and help debugging the UI issues with incorrect ids being used.
=> test: randomize db sequences

Makefile
Thanks to @bruno-fs for making this possible with quipucords/pull/2481! 🎉 
I want this in the make target so I don't need an extra step for it in my sandbox DB rebuild routine…
```
dropdb -U qpc qpc \
&& createdb -U qpc qpc \
&& poetry install \
&& make server-migrate \
&& poetry run python ./quipucords/manage.py randomize_db_sequences \
&& make server-set-superuser serve
```
Since the makefile is chiefly for us developers/maintainers anyway, I think we should *always* be running the sequence randomizer to ensure we don't miss any unfortunate ID collisions. (I'm looking at you, report IDs…)
Now my local command is simply:
```
dropdb -U qpc qpc \
&& createdb -U qpc qpc \
&& poetry install \
&& make server-migrate server-randomize-sequences server-set-superuser serve
```
=> feat: randomize sequences after migrating database

quipucords/api/deployments_report/serializer.py, quipucords/api/details_report/util.py, quipucords/api/details_report/view.py, quipucords/api/merge_report/view.py, quipucords/api/reports/view.py, quipucords/api/scantask/model.py, quipucords/api/serializers.py, quipucords/fingerprinter/runner.py, quipucords/scanner/job.py, quipucords/scanner/tasks.py, quipucords/tests/api/deployments_report/test_deployments_report.py, quipucords/tests/api/details_report/test_details_report.py, quipucords/tests/api/details_report/test_sync_report_creation.py, quipucords/tests/api/reports/test_reports.py, quipucords/tests/factories.py, quipucords/tests/fingerprinter/test_fingerprint_process_sources.py, quipucords/tests/fingerprinter/test_fingerprint_task.py, quipucords/tests/scanner/tasks/test_fingerprint.py, quipucords/tests/test_factories.py
Finishes mass renaming details_report -> report. The only references to details report that persist in the codebase should now be referring to the actual report (you know, the file, the json response...), not the model.
Relates to JIRA: DISCOVERY-226
=> chore: yet another details report renaming PR

.dockerignore, Dockerfile, Dockerfile.scan-target, Makefile, quipucords/tests/integration/conftest.py
Context: On internal Jenkins, `make build-container` may fail because GitHub rate-limits API requests, and a lot of internal traffic appears as a single IP to GitHub.
With this change, we can use GitHub token to authenticate API request during `make build-container`. Jenkins pipeline will use that capability, but it remains optional for everyone else.
The easy way would be to pass environment variable using `podman --env`, but then token will be embedded in final image layer. The correct way is to use docker / podman `--secret` flag. Unfortunately, this flag requires file with secret to exist when running `podman build`, so I have to add new empty file to repo.
Since secrets are not part of built layer, changing secrets file content will not invalidate cached layers. So if you run `make …
=> DISCOVERY-435: Authorize GitHub requests if token is available

.github/workflows/build.yml
Pushing to quay only works reliably if PR is created from branch in main repo, not fork.
However, users *may* configure their fork in a way that will make push step succeed.
Jenkins detects PR was created from fork and will build container image locally before running Camayoc.
To support all possible use-cases, instead of using brittle conditionals, let's just mark a push step as allowed failure. Standard PRs from branches should continue to work as they did, and forks with custom setup have a chance to succeed, while others won't prevent merge.
=> Don't fail workflow if we can't push to quay

quipucords/tests/api/scan/test_scan.py, quipucords/tests/api/scanjob/test_scanjob.py, quipucords/tests/api/scantask/test_scantask.py
Removing unused variable cred_for_upload in quipucords api tests.
=> refact(tests): remove unused cred_for_upload variable from tests.

pyproject.toml, quipucords/api/common/common_report.py, quipucords/api/management/commands/randomize_db_sequences.py, quipucords/api/messages.py, quipucords/api/source/serializer.py, quipucords/quipucords/environment.py, quipucords/quipucords/settings.py, quipucords/scanner/manager.py, quipucords/scanner/network/processing/ip.py, quipucords/scanner/openshift/api.py, quipucords/scanner/openshift/entities.py, quipucords/tests/scanner/network/processing/test_brms.py, quipucords/tests/scanner/openshift/test_api.py, quipucords/tests/scanner/openshift/test_entities.py, quipucords/utils/debugger.py
Yet another linter enabled in ruff. This time, [bandit](https://pypi.org/project/bandit/).
The inspiration to add this check came from this comment: https://github.com/quipucords/quipucords/pull/2492#discussion_r1345776403
=> chore: addopt bandit static linter

.gitignore, Vagrantfile
QoL for development. Easily spin multiple vms to run network scans locally.
My personal cheat sheet for vagrant:
```
vagrant up
vagrant ssh-config | grep HostName | awk '{print $2}'
vagrant destroy -f
```
=> chore: add a vagrant config to spin multiple vms

quipucords/scanner/network/runner/roles/check_dependencies/tasks/main.yml, quipucords/scanner/network/runner/roles/cloud_provider/tasks/main.yml, quipucords/scanner/network/runner/roles/cpu/tasks/main.yml, quipucords/scanner/network/runner/roles/date/tasks/main.yml, quipucords/scanner/network/runner/roles/dmi/tasks/main.yml, quipucords/scanner/network/runner/roles/etc_release/tasks/main.yml, quipucords/scanner/network/runner/roles/file_contents/tasks/main.yml, quipucords/scanner/network/runner/roles/ifconfig/tasks/main.yml, quipucords/scanner/network/runner/roles/insights/tasks/main.yml, quipucords/scanner/network/runner/roles/installed_products/tasks/main.yml, quipucords/scanner/network/runner/roles/ip/tasks/main.yml, quipucords/scanner/network/runner/roles/jboss_brms/tasks/main.yml, quipucords/scanner/network/runner/roles/jboss_eap/tasks/main.yml, quipucords/scanner/network/runner/roles/jboss_eap5/tasks/main.yml, quipucords/scanner/network/runner/roles/jboss_fuse/tasks/main.yml, quipucords/scanner/network/runner/roles/jboss_fuse_on_karaf/tasks/main.yml, quipucords/scanner/network/runner/roles/jboss_ws/tasks/main.yml, quipucords/scanner/network/runner/roles/memory/tasks/main.yml, quipucords/scanner/network/runner/roles/redhat_packages/tasks/main.yml, quipucords/scanner/network/runner/roles/redhat_release/tasks/main.yml, quipucords/scanner/network/runner/roles/subman/tasks/main.yml, quipucords/scanner/network/runner/roles/system_purpose/tasks/main.yml, quipucords/scanner/network/runner/roles/uname/tasks/main.yml, quipucords/scanner/network/runner/roles/user_data/tasks/main.yml, quipucords/scanner/network/runner/roles/virt/tasks/main.yml, quipucords/scanner/network/runner/roles/virt_what/tasks/main.yml
=> fix: `export LANG=C LC_ALL=C;` before all ansible raw commands

Makefile, README.md, deploy/entrypoint_web.sh, deploy/rejected_common_passwords.txt, deploy/setup_user.py, quipucords/quipucords/settings.py, quipucords/quipucords/user.py, quipucords/tests/quipucords/test_user.py
- Eliminating the default admin password and relying on the users to specify their default via the environment variable QPC_SERVER_PASSWORD (which also supports the OpenShift/Kubernetes secret declared ones).
- If not specified, we generate a random password for the user and provide it to them upon creation.
- When the secret is specified via QPC_SERVER_PASSWORD (either coming from OpenShift or from bash), we also allow the users to update the admin password
During server initialization:
```
$ make server-init QPC_SERVER_PASSWORD="SuperAdmin1"
```
As well as any point in time:
```
$ make set-superuser QPC_SERVER_PASSWORD="NewAdminPassword2"
```
When initially creating the superuser and no QPC_SERVER_PASSWORD is specified, a random password is generated:
```
$ make server-init …
```
=> Support admin password specification

poetry.lock, pyproject.toml, quipucords/compat/db.py, quipucords/fingerprinter/runner.py, quipucords/scanner/network/inspect_callback.py, quipucords/scanner/network/processing/karaf.py
chore: Updating ruff to 0.1.3
- Updating to latest ruff and keeping consistency with qpc
- Latest ruff 0.1.3 was not as forgiving for a couple of syntaxes as the earlier version. So, fixing those errors here which also helped eliminate a couple of noqa and lint exceptions.
=> Update ruff to 0.1.3

.github/workflows/test.yml
Dropping `test-integration` due to the recent mysterious failures that we have not been able to explain or reproduce locally.
I also removed `test-integration` from GitHub's required PR checks on https://github.com/quipucords/quipucords/settings/branch_protection_rules/1091609.
Discussion thread: https://redhat-internal.slack.com/archives/C02QSNF1UKE/p1699382962577379
=> test: drop test-integration from github test matrix

docs/installation.md
The intent of this update is simply to modernize and correct errors with the existing documentation. Yes, we will eventually drop compose in favor of something else, and we should consider exposing more of the recently added environment variables, but neither of those is within the scope of this update. I'm simply preserving existing functionality and expectations and making sure the instructions actually work for new users.
Throughout and after making these updates, I have been periodically destroying and rebuilding images and containers (following the updated instructions) to confirm they actually work. Disclaimer: I'm on an Intel (x86-64) Mac, and I cannot currently confirm that the instructions work for Linux or other CPU architectures. I left the Linux-specific instructions largely …
=> update instructions for building quipucords containers from source and running in podman

Jenkinsfile
As we might get RHEL agents in the future (once qpc RPM is available), it might be necessary to be more specific when selecting agent machine - i.e. run something else on RHEL than on Fedora. This change ensures that Fedora job is not mistakenly picked up by RHEL agent.
=> Make Jenkins agent labels consistent with internally defined jobs

pyproject.toml, quipucords/scanner/openshift/entities.py, quipucords/tests/scanner/openshift/test_entities.py
Pulling these commits in from the `release/1.4` branch.
* f9c80cb3
* 177c0673
* 6c7fee6b
I used `cherry-pick` because the branches have diverged enough that `rebase` attempts to duplicate commits that were originally made in `main` but also ported to `release/1.4`.
=> Port 1.4 changes to main

quipucords/quipucords/environment.py
- When user selects to dump the environment variables via the boolean QPC_LOG_ALL_ENV_VARS_AT_STARTUP at start-up, let's sort them as it is tedious to find a variable by name otherwise.
=> chore: sort environment variables when logging.

docs/swagger.yml, quipucords/api/common/util.py, quipucords/api/credential/view.py, quipucords/api/exceptions.py, quipucords/api/messages.py, quipucords/api/urls.py, quipucords/api/views.py, quipucords/tests/api/credential/test_credential.py
- Adding support for deleting credentials in bulk via the /api/v1/credentials/bulk_delete/ POST URL. That URL takes the list if ids to delete via the ids: [ id1, id2, ... ] entry in the posted request.
Related to: https://issues.redhat.com/browse/DISCOVERY-511
=> feat: Add support for bulk deleting credentials

quipucords/scanner/rhacs/inspect.py, quipucords/tests/integration/test_rhacs_scan.py
Updated 2024-01-17: When fetching RHACS data, we now use the new API paths as introduced in RHACS 4.3. We expect requests to the older RHACS 4.2 API to fail.
~When fetching RHACS data, we now try the "new" API paths as introduced in RHACS 4.3. If a request to the new 4.3 API path fails, we seamlessly retry the request with the old RHACS 4.2 path.~
~This may be a good solution while 4.2 is still available and in use, but we should consider removing this retry logic and embrace the 4.3+ APIs exclusively after some amount of burn-in or if we learn that we have minimal or no customers using RHACS 4.2.~
Relates to JIRA: DISCOVERY-502
https://issues.redhat.com/browse/DISCOVERY-502
=> feat(rhacs): use new RHACS v4.3+ API paths

quipucords/api/common/util.py, quipucords/api/details_report/util.py, quipucords/api/inspectresult/model.py, quipucords/api/migrations/0029_migrate_rawfact_value_to_jsonfield.py, quipucords/api/reports/model.py, quipucords/fingerprinter/runner.py, quipucords/tests/integration/test_openshift_scan.py, quipucords/tests/scanner/job/test_job_celery_based.py, quipucords/tests/utils/raw_facts_generator.py
Adds test coverage to fingerprint-only scan jobs as a pre-requisite for the upcoming refactors for upload & merge views.
Relates to JIRA: DISCOVERY-340
=> DISCOVERY-340: ensure fingerprint-only scan jobs are properly working

quipucords/tests/scanner/vcenter/test_vc_connect.py, quipucords/tests/scanner/vcenter/test_vc_inspect.py, quipucords/tests/scanner/vcenter/test_vc_utils.py
- Converting the vCenter test to pytest.
This is needed in https://github.com/quipucords/quipucords/pull/2549 and done in a separate PR to minimize its scope.
=> test(vcenter): Converting vCenter test to pytest

quipucords/tests/api/source/test_serializer.py, quipucords/tests/api/source/test_source.py
Adding unit tests for things that we have in Camayoc.
Also removed some duplication and generalized some tests (used pytest params where they make sense instead of keeping multiple almost identical tests).
=> Port Source API tests from Camayoc

quipucords/api/migrations/0044_credential_created_at_credential_updated_at.py
- Adding the reverse_code to the migration, while we would lose the *_at attributes added since those were added and we don't have those before the 0044 migration, we can at least reverse the migration.
=> chore(migrations): make credentials timestamp attribute migration reversible

quipucords/quipucords/settings.py, quipucords/scanner/network/inspect.py, quipucords/scanner/network/inspect_callback.py, quipucords/tests/scanner/network/test_network_inspect.py, quipucords/tests/utils/test_sanitize_for_utf8_compatibility.py, quipucords/utils/__init__.py, quipucords/utils/misc.py
This branch/PR contains the following commits cherry-picked from the `release/1.4` branch:
* b4fe714f89eef2e44bd32517f89352ef783ffca0
* fb502b2115367b8f99d1a3847dfcbd03eaf343e3
* aa3cdc3771f34d263b9bfc604c3f1f01e836dbaa
This includes changed introduced by https://github.com/quipucords/quipucords/pull/2563 and https://github.com/quipucords/quipucords/pull/2565.
I believe all other recent commits in `release/1.4` already exist in some equivalent form in `main`. I specifically used `cherry-pick` instead of `rebase` because the branches have diverged significantly and the rebase operation introduced several conflicts that I did not want to resolve manually.
=> chore: port 1.4 changes to main

quipucords/scanner/network/inspect.py
Store some ansible runner object metadata as soon as we are sure it finished. This might help in debugging some issues.
=> Log ansible runner obj metadata

quipucords/api/credential/serializer.py, quipucords/api/messages.py, quipucords/tests/api/credential/test_credential.py, quipucords/tests/api/credential/test_serializer.py
This simply removes the custom `CredentialSerializer.validate` method to restore standard DRF behaviors.
Relates to JIRA: DISCOVERY-534
https://issues.redhat.com/browse/DISCOVERY-534
=> fix: ignore unexpected fields in credential serializer

quipucords/quipucords/settings.py
- While the pathname is good to have, it is sometimes quite long for what we just need is just the relative path to the filename being logged from the root of the project.
Adding and using a relative_pathname attribute for the verbose formatter.
This saves on logging output size and our eyes.
Current verbose log output:
```
[INFO 2024-02-09T13:31:48 pid=26460 tid=6174175232 /Users/abellotti/DevHome/projects/discovery/quipucords/quipucords/scanner/manager.py:log_info:107] SCAN JOB MANAGER: No scan job currently running.  Scan queue length is 0. Queued jobs: []
[INFO 2024-02-09T13:31:49 pid=26460 tid=6191001600 /Users/abellotti/DevHome/projects/discovery/quipucords/quipucords/scanner/manager.py:log_info:107] SCAN JOB MANAGER: No scan job currently running.  Scan queue length is 0. Queued …
```
=> feat(Logging): adding and using a relative_pathname for the verbose logger

quipucords/quipucords/settings.py
- For pathnames that are not relative to the project's BASE_DIR, relative_to fails with an exception causing the logging to fail. In such cases (i.e. error from a python library file), let's lost the full pathname instead.
=> fix(Logging): Verbose logging fails with non relative pathnames

Makefile, conftest.py, quipucords/scanner/network/__init__.py, quipucords/scanner/network/inspect.py, quipucords/scanner/network/inspect_callback.py, quipucords/scanner/network/processing/process.py, quipucords/tests/integration/test_network_scan.py, quipucords/tests/scanner/network/test_inspect_callback.py, quipucords/tests/scanner/network/test_network_inspect.py
Decouple logic saving data to database and postprocessing from
InspectCallback.
Now inspect callback only acts as a helper to parse and group together
facts collected from ansible events and mantains it's original
functionality for cancel callback. This will make understanding and
testing this class much, much easier.
InspectTaskRunner now holds the logic for post processing and storing results to db.
=> refactor(network-scan): decouple InspectCallback logic

quipucords/api/user/view.py, quipucords/tests/api/user/test_user.py
This branch changes three behaviors to improve the security of quipucords' logout API: 
1. Include the `Clear-Site-Data` response header to encourage clients to clear their local data.
2. Delete *all* of the user's tokens at logout, not just the first (unordered!) result from the database.
3.  *Do not* create a new auth token at logout. Only new logins should create tokens. I don't understand why we ever would want to create a new token at logout, but I confirmed manually with the UI and `qpc` CLI that my updated behavior works fine.
Relates to JIRA: DISCOVERY-468
https://issues.redhat.com/browse/DISCOVERY-468
=> feat: improve logout security

quipucords/scanner/network/runner/roles/jboss_ws/tasks/main.yml
Make it possible to detect JWS 6 installation through systemd unit file.
JWS 6 supports 2 installation methods - through archive and through RPM. Both will create systemd unit file, which is a recommended way of starting a daemon.
Also fixed a glaring issue in the same file - see comment.
=> Detect JWS 6 installations

Makefile
As discussed in Slack here: https://redhat-internal.slack.com/archives/C02QSNF1UKE/p1708458696080799?thread_ts=1708456997.169309&cid=C02QSNF1UKE
=> refactor: add --durations=10 to identify slow tests

quipucords/scanner/network/runner/roles/jboss_ws/tasks/main.yml
dnf introduced backwards incompatible change - `dnf grouplist` will return early if any argument is not a valid group name. This means we can't ask for status of multiple groups at once and see which one is installed - if any is not a valid group identifier, dnf will not even check what is the status of others.
We need multiple `dnf grouplist` invocations in a loop. I tried just grabbing them all and processing them on quipucords side, but unfortunately too much of our code assumes that a raw fact value from ansible is going to be a dict similar to raw command return value. While I think we might want to re-think this design decision and allow processing of results list, that would be too much for what I hoped to be relatively easy change.
Alternative would be to loop in the shell, but …
=> fix: Work around dnf grouplist returning early on unknown groups

quipucords/api/merge_report/view.py, quipucords/api/scan/view.py, quipucords/api/scanjob/model.py, quipucords/api/scanjob/queryset.py, quipucords/api/scanjob/serializer.py, quipucords/api/scanjob/view.py, quipucords/api/serializers.py, quipucords/api/urls.py, quipucords/api/views.py, quipucords/tests/api/scanjob/test_scanjob.py, quipucords/tests/api/scanjob/test_scanjob_queryset.py
Add a new ViewSet for ScanJobs. It has list and retrieve, replacing both
`/v1/jobs/<job-id>`, `/v1/scans/<scan-id>/jobs/` and `/v1/report/merge/jobs/<job-id>`.
Part of the rationale is to support upcoming scanless fingerprint type
jobs that will be created for upload reports (DISCOVERY-452). If we would
follow the original pattern, yet another endpoint for listing jobs would be
required instead.
Compared to the original endpoints, this one lacks: 
- `scan.name` (since we are planning to move away from it - and name don't seem a really useful info in this context)
- tasks (since neither UI nor CLI actually use this info - and it will very likely be populated with way more than just 3 tasks to support parallel celery tasks in the future)
- counts_fingerprint (also not used by UI/CLI - and …
=> ScanJob ViewSet for v2 API

quipucords/api/inspectresult/serializer.py, quipucords/api/scanjob/view.py, quipucords/tests/api/scanjob/test_scanjob.py
This view is only used by the UI, which isn't consuming nor will consume facts from this view. Removing facts from this view removes a potential issue for sources with multiple hosts/subnets, avoiding unnecessary queries and a unnecessary large json response.
Relates to JIRA: DISCOVERY-218
=> refactor(inspect-view): remove unused facts info

.gitignore, conftest.py, quipucords/api/common/util.py, quipucords/api/credential/view.py, quipucords/api/exceptions.py, quipucords/tests/api/credential/test_credential.py
This also fixes a few minor issues in recent commits to this API, and this also adds a new `client_logged_in` test fixture that is much faster than our `django_client` fixture that this code was previously using extensively.
Running `poetry run pytest quipucords/tests/api/credential/test_credential.py` on my local system at commit f49787ad (**before** converting it to the new fixture):
```
129 passed, 5 warnings in 116.75s (0:01:56)
```
Running `poetry run pytest quipucords/tests/api/credential/test_credential.py` on my local system at commit fe44a58d (**after** converting it to the new fixture):
```
129 passed, 4 warnings in 8.62s
```
Gotta go fast. 🦔💨
I could split out the new fixtures into a separate PR if requested.
=> feat: support partial deletes in bulk delete API

quipucords/api/credential/view.py, quipucords/api/deployments_report/view.py, quipucords/api/details_report/view.py, quipucords/api/insights_report/view.py, quipucords/api/merge_report/view.py, quipucords/api/reports/view.py, quipucords/api/scan/view.py, quipucords/api/scanjob/view.py, quipucords/api/source/view.py, quipucords/api/user/view.py, quipucords/quipucords/settings.py
This removes a lot of (probably copy-paste anti-pattern) unnecessary code duplicated across all our views.
DRY. ☀️ 🌵 
This is a followup to https://github.com/quipucords/quipucords/pull/2601 that implements a similar cleanup.
=> refactor: simply use DEFAULT_PERMISSION_CLASSES for all views

Makefile
- Provide ability to deploy the celery worker to run with a minimum and maximum concurrency via the following 2 environment variables:
QPC_CELERY_WORKER_MIN_CONCURRENCY
QPC_CELERY_WORKER_MAX_CONCURRENCY
Defaults to 10, 10 for consistency with the current default (--concurrent=10 when not specified)
=> feat(CeleryWorker): Allow for min and max concurrency specification

docs/swagger.yml, quipucords/api/common/util.py, quipucords/api/credential/view.py, quipucords/api/source/view.py, quipucords/api/urls.py, quipucords/api/views.py, quipucords/tests/api/common/test_common_util.py, quipucords/tests/api/credential/test_credential.py, quipucords/tests/api/source/test_source_bulk_delete.py, quipucords/tests/api/test_urls.py, quipucords/tests/factories.py, quipucords/tests/scanner/network/test_network_connect.py, quipucords/tests/scanner/network/test_network_inspect.py
This change is a followup to https://github.com/quipucords/quipucords/pull/2540, https://github.com/quipucords/quipucords/pull/2586, and https://github.com/quipucords/quipucords/pull/2593 to add the ability to bulk delete sources with a single HTTP POST. The new sources bulk delete API behaves similar to the recent credentials bulk delete API.
To delete *all* sources, post a json payload like `{"ids": "all"}`:
```bash
http post \
http://127.0.0.1:8000/api/v1/sources/bulk_delete/ \
'Cookie:csrftoken=mytoken; sessionid=mysession' 'X-CSRFToken:mytoken' \
ids:='"all"'
```
To delete specific sources, post a json payload like `{"ids": [1,2,3,4]}`:
```bash
http post \
http://127.0.0.1:8000/api/v1/sources/bulk_delete/ \
'Cookie:csrftoken=mytoken; sessionid=mysession' 'X-CSRFToken:mytoken' \ …
```
=> feat: add support for bulk deleting sources

setup.py
We are using Python 3.11 (at minimum) everywhere and we forgot to update setuptools.
=> chore: requires Python >= 3.11 for setuptools.

quipucords/api/scan/view.py, quipucords/api/urls.py, quipucords/tests/api/credential/test_credential.py, quipucords/tests/api/scan/test_scan_bulk_delete.py, quipucords/tests/api/source/test_source_bulk_delete.py
This change is a followup to https://github.com/quipucords/quipucords/pull/2540, https://github.com/quipucords/quipucords/pull/2586, https://github.com/quipucords/quipucords/pull/2593, https://github.com/quipucords/quipucords/pull/2605, and https://github.com/quipucords/quipucords/pull/2608 to add the ability to bulk delete scans with a single HTTP POST. The new scans bulk delete API behaves similar to the recent credentials bulk delete and sources bulk delete APIs.
To delete *all* scans, post a json payload like `{"ids": "all"}`:
```bash
http post \
http://127.0.0.1:8000/api/v1/scans/bulk_delete/ \
'Cookie:csrftoken=mytoken; sessionid=mysession' 'X-CSRFToken:mytoken' \
ids:='"all"'
```
To delete specific scans, post a json payload like `{"ids": [13652,13653,13654,13655]}`:
```bash
http …
```
=> feat: add support for bulk deleting scans

conftest.py, quipucords/tests/api/credential/test_credential.py, quipucords/tests/api/merge_report/test_async_merge_report.py, quipucords/tests/api/scan/test_scan.py, quipucords/tests/api/scan/test_scan_bulk_delete.py, quipucords/tests/api/source/test_source_bulk_delete.py
Replace `django_client` fixture with the much faster `client_logged_in`.
Also increase rate limit threshold for tests and "hack" django's test `Client` setting the default  `content_type="application/json"`.
=> Replace django_client fixture on test async merge + test QoL

quipucords/api/common/pagination.py
- While the UI may have a restriction to not show more than 10 items at a time, the default paging size for an API back-end server should be larger than 10 items.
we have the enforced paging size limit of 1000, let's up the default paging size to 100.
UI was calling the requests with the appropriate ?page_size=10 so this should have no effect there.
=> chore(pagination): Upping the default paging size to 100

quipucords/scanner/network/inspect_callback.py, quipucords/tests/scanner/network/test_inspect_callback.py
This previously-working behavior regressed at 86ff19d9c3b65ebe82eca5c2481acb7bc246f1d8.
=> fix: restore broken fact sanitization

deploy/entrypoint_web.sh, deploy/gunicorn_conf.py
- Allow the legacy UI to be used when the Celery scan manager is enabled and used in a quadlet environment.
We can change this once the new UI replaces it and we can eliminate the legacy one.
=> fix: allow legacy UI to be used with Celery and Quadlets

.github/workflows/test.yml, .shellcheckrc, Makefile, deploy/entrypoint_celery_worker.sh, deploy/entrypoint_web.sh
I've been using `shellcheck` on my local development environments for a few years, and I find it helps make shell scripts more consistent in their style and catches bugs that I missed myself. I thought it might be time to add it to `quipucords` since our little shell scripts are starting to grow a bit.
This change adds a PR check to run `shellcheck ./deploy/*.sh`. I also applied several recommended `shellcheck` fixes to our existing code to make the check happy:
```
SC2006 (style): Use $(...) notation instead of legacy backticks `...`.
SC2046 (warning): Quote this to prevent word splitting.
SC2181 (style): Check exit code directly with e.g. 'if mycmd;', not indirectly with $?.
SC2248 (style): Prefer double quoting even when variables don't contain special characters.
SC2250 (style): …
```
=> test: run shellcheck against deploy scripts to avoid bugs

.github/workflows/test.yml, Dockerfile, deploy/check_related_services_liveness.sh, deploy/entrypoint_celery_worker.sh, deploy/entrypoint_web.sh
If psql is the specified database but its port is not open, we now loop and emit messages like this before trying to run migrations:
```
Checking localhost:5432 status...
Ncat: Connection refused.
Checking localhost:5432 status...
Ncat: Connection refused.
```
Once the port is open, the loop exits, and migrations proceed.
I also upgraded to `postgresql:15` in our GitHub CI jobs since we recently updated to `postgresql-15` in discovery-ci.
I based these changes on the branch in https://github.com/quipucords/quipucords/pull/2622. So, that PR should merge before this one, or I need to yank its commits.
=> feat: check psql liveness before running migrations

quipucords/api/inspectresult/model.py, quipucords/tests/fingerprinter/test_fingerprint_process_sources.py
Fix the problem by reproducing the original behavior of not exposing systems with no facts on Report.sources.
=> fix: fix a bug in fingerprinting when systems have no facts

quipucords/tests/factories.py, quipucords/tests/scanner/network/test_network_connect_callback.py
only create "connect" task related objects for connect type scan tasks.
=> refactor(factories): cleanup unnecessary factories

docs/swagger.yml, quipucords/api/scanjob/view.py, quipucords/tests/api/scanjob/test_scanjob.py, quipucords/tests/api/test_urls.py
Relates to Jira: DISCOVERY-390
=> refactor(scanjob)!: drop restart/pause functionality

quipucords/scanner/network/inspect.py, quipucords/scanner/network/inspect_callback.py, quipucords/tests/scanner/network/test_inspect_callback.py, quipucords/tests/scanner/network/test_network_inspect.py
Fix a vulnerability found in network scan that could cause a whole scan to fail if a failure occurs in a single "inspection group".
This is related to [DISCOVERY-353](https://issues.redhat.com/browse/DISCOVERY-353) and could also be related to   [DISCOVERY-464](https://issues.redhat.com/browse/DISCOVERY-464) 
Relates to JIRA: DISCOVERY-353
=> refactor error handling in network scan

quipucords/api/scantask/model.py, quipucords/fingerprinter/utils.py, quipucords/tests/api/scantask/test_scantask.py, quipucords/tests/fingerprinter/test_utils.py
Some possible "fixes" inspired by @bruno-fs's recent findings [documented here](https://docs.google.com/document/d/1wwZDHXa1dD_0UeP-fWg1lLR7MeIT5GpzUUdrmWTjrSk/edit).
These changes do not fix the underlying problems of missing data. They only improve handling of bad data so we don't crash out with unhandled exceptions.
Also, this diff grew a lot because I needed to touch `test_scantask` but I also needed to convert it from unittest style to pytest. If might help to review the commits one at a time.
=> fix: better handle some unexpected None values

quipucords/scanner/network/inspect.py, quipucords/tests/scanner/network/test_network_inspect.py
cherry-picks de45f84b
Relates to JIRA: DISCOVERY-353
[Standalone Jenkins job](https://stage-jenkins-csb-smqe.apps.ocp-c1.prod.psi.redhat.com/view/Discovery/job/discovery-standalone/110/)
EDIT: all ✅ in standalone jenkins job!
=> refactor(network-inspect): don't let errors to ansible runner stop the scanner

quipucords/api/messages.py
As far as I can tell, nothing uses these string variables.
=> chore: remove unused message strings definitions

quipucords/scanner/network/inspect.py
This should solve the issues we've seen in the field where we've been recommending customers to increase the timeout value
=> fix(network-inspect): alter job timeout to respect inspect group size

quipucords/api/aggregate_report/model.py, quipucords/api/aggregate_report/view.py, quipucords/api/urls.py, quipucords/api/views.py, quipucords/tests/api/aggregate_report/test_aggregate_report_model.py, quipucords/tests/factories.py, quipucords/tests/utils/raw_facts_generator.py, quipucords/tests/utils/test_datetime.py, quipucords/utils/datetime.py
Relates to JIRA: DISCOVERY-611
This is a first pass at what Justin needs. On 2024-05-02, I walked with him through the top 42 rows in [his request spreadsheet](https://docs.google.com/spreadsheets/d/1YvI7KQc7ZyBtoDqj8y0kyo5PU-NerkAuoAhzLI6pDmE/edit#gid=0), explained exactly how I determine each output value, and resolved several questions about ambiguous inputs and outputs. Following that discussion, I kept some inline comments with the code to clarify a few potentially confusing parts.
The current version is still far from optimal, but it technically works. This API looks up the report fingerprints and facts and calculates the output _on demand_ every time. This obviously won't scale up to large data sets. So, a logical next step (in a future PR, not this one) would be to store the …
=> feat: add aggregate report API

quipucords/tests/utils/raw_facts_generator.py
Without `tzinfo`, the generated `creation_timestamp` will fail fingerprint processing because `fingerprinter.runner.RAW_DATE_KEYS` requires this date's string representation to match the `"%Y-%m-%dT%H:%M:%S%z"` format.
Additionally, `replace(microsecond=0)` is required because the default `faker.date_time()` output includes a random microsecond value, but then its string representation includes microseconds which also fails to match the aforementioned pattern.
=> fix: improve creation_timestamp in _openshift_raw_facts_generator

quipucords/api/aggregate_report/model.py, quipucords/tests/api/aggregate_report/test_aggregate_report_model.py
See also Slack discussion: https://redhat-internal.slack.com/archives/C02QSNF1UKE/p1716241418596129
Relates to JIRA: DISCOVERY-611
=> fix: only count missing_cpu_core_count for network and satellite sources

.github/workflows/build-arm64.yml, .github/workflows/build.yml
- When building release containers, i.e. 1.7.1, let's make sure we create both, the x.y.z and x.y tags, i.e 1.7.1 and 1.7
- Same with the ARM64, when creating the 1.7.1-arm64 flavor of the container build, also create the 1.7-arm64 tag.
=> feat(build): Create x.y release tags when building release containers

quipucords/api/scanjob/model.py, quipucords/api/scantask/model.py, quipucords/fingerprinter/runner.py, quipucords/quipucords/settings.py, quipucords/tests/fingerprinter/test_fingerprint_task.py
🙈 🙈 🙈
🤫
🔥 🐶 ☕ 🔥 
This PR adds support for a new environment variable `QUIPUCORDS_BYPASS_BUILD_CACHED_FINGERPRINTS` that will bypass building and setting `DeploymentsReport.cached_fingerprints` during the fingerprinting process. This will cause problems if actual customers tried to enable that variable because it will result in empty or broken data when they try to download their report tarball. So, I set this only when `PRODUCTION` is not `True`, and that means our containers (both upstream and downstream) _will not_ enable this bypass because they both set `ENV PRODUCTION=True` in their respective `Dockerfile`s.
Then why am I adding this bypass? I'm performance testing quipucords with moderately large sets of simulated raw facts and fingerprints, but due to …
=> perf: allow bypassing cached_fingerprints build for non-production dev environments

quipucords/api/aggregate_report/model.py, quipucords/tests/api/aggregate_report/test_aggregate_report_model.py
Following a demo on 2024-05-29, Justin and I discussed several potential changes to the new aggregate report. These `openshift_operators_by_name` and `instances_not_redhat` additions were trivially easy and high on his request list.
This PR only adds those two new attributes to the response JSON and does not affect other aggregated counts or lists.
Example request and response after this change:
```sh
qpc report aggregate --report 32764
```
```json
{
"ansible_hosts_all": 0,
"ansible_hosts_in_database": 0,
"ansible_hosts_in_jobs": 0,
"inspect_result_status_failed": 0,
"inspect_result_status_success": 7,
"inspect_result_status_unknown": 0,
"inspect_result_status_unreachable": 0,
"instances_hypervisor": 0,
"instances_not_redhat": 0,
"instances_physical": 0,
"instances_unknown": 6, …
```
=> feat: add `openshift_operators_by_name` and `instances_not_redhat` to aggregate report

quipucords/scanner/network/processing/cloud_provider.py
Should fix this exception that @bruno-fs and I have seen on rare occasions:
```
[ERROR 2024-06-06T20:37:01 pid=64315 tid=140704491662208 api/scantask/model.py:_log_scan_message:195] Job 25, Task 2 of 3 (inspect, network, 20240606, elapsed_time: 78s) - FAILED POST PROCESSING [IP ADDRESS]. Processor for cloud_provider got value QPC_FORCE_POST_PROCESS, returned Traceback (most recent call last):
File "/Users/brasmith/projects/quipucords/quipucords/scanner/network/processing/process.py", line 146, in process
processor_out = processor.process(fact_value, dependencies)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/brasmith/projects/quipucords/quipucords/scanner/network/processing/cloud_provider.py", line 75, in process
if "amazon" in dmi_bios_version.lower():
^^^^^^^^^^^^^^^^^^^^^^ …
```
=> fix: ensure cloud_provider facts are never None when processing

quipucords/api/scanjob/model.py, quipucords/quipucords/settings.py, quipucords/scanner/ansible/inspect.py, quipucords/scanner/network/inspect.py, quipucords/scanner/openshift/inspect.py, quipucords/scanner/rhacs/inspect.py, quipucords/tests/api/common/test_entities.py, quipucords/tests/factories.py
The motivation for this change is that when I tried performance testing quipucords with very large sets of synthetic (factory-generated) data, the system I was running quipucords would OOM or Postgres would reject some of the bulk insert requests for being too large.
We now read the env var `QUIPUCORDS_BULK_CREATE_BATCH_SIZE` with a default value of 100 to use in all current Django model bulk_create calls.
The default value 100 should comfortably cover the overwhelming majority of our users' needs, and the performance penalty shouldn't be too bad for users with larger data sets. Since it's configurable, we could always investigate performance on different hardware characteristics and recommend different values for different hardware.
=> refactor: use a configurable batch_size in all current Django model bulk_create calls

conftest.py, quipucords/api/apps.py, quipucords/api/deployments_report/model.py, quipucords/api/migrations/0054_remove_deploymentsreport_cached_csv_and_more.py, quipucords/quipucords/settings.py, quipucords/tests/api/deployments_report/test_deployments_report.py, quipucords/tests/factories.py
Relates to JIRA: DISCOVERY-691
Aside from confirming that unit tests still pass, I manually verified with a running server a few ways, probably most interestingly by migrating an existing database that already had several small scans and few "large" scans (one with about 60,000 related raw facts).
Before applying migrations:
```
❯ psql -U qpc -c 'vacuum full analyze'
VACUUM
❯ du -sh $(echo $(psql -U qpc -tc 'show data_directory')/base/$(psql -U qpc -tc "select oid from pg_database where datname='qpc'") | tr -d '[:space:]')
460M	/usr/local/var/postgresql@14/base/21683799
```
Migration output looks like this:
```
❯ poetry run make server-migrate
/Users/brasmith/Library/Caches/pypoetry/virtualenvs/quipucords-A54Z8Zh8-py3.12/bin/python quipucords/manage.py migrate --settings …
```
=> refactor: store cached deployment report CSV and fingerprints JSON in files, not in the database

quipucords/scanner/network/runner/roles/jboss_eap/tasks/main.yml, quipucords/scanner/network/runner/roles/jboss_fuse_on_karaf/tasks/main.yml, quipucords/scanner/network/runner/roles/jboss_ws/tasks/main.yml
This is a followup to https://github.com/quipucords/quipucords/pull/2685 since I discovered very ugly output being captured by Ansible in network scans for _some_ systems. Also discussed in Slack [here](https://redhat-internal.slack.com/archives/C02QSNF1UKE/p1719351251768579).
Quoting myself:
> I just noticed that when Ansible is invoking hostnamectl, sometimes it's getting ansi escape codes that are totally mucking up the output. These are the hidden bytes that add color and style like in this screenshot.
>
> When we get those bytes, we keep passing them along, and facts can get ugly and useless like this bit copied from a details.json:
```json
"hostnamectl": {
"value": {
"\u001b[0;94m______________kernel": "\u001b[0m Linux 6.9.4-200.fc40.x86_64",
"\u001b[0;94m_____________boot_id": …
```
=> fix: set `TERM=dumb` to discourage systemctl from writing ANSI escape codes

quipucords/api/deployments_report/model.py, quipucords/tests/api/deployments_report/test_deployments_report.py
After reflecting on the initial change introduced by 8729eb4d, we decided that we would prefer to log errors and fail bigger if we fail to read data from DeploymentsReport cached_fingerprints or cached_csv. This can happen if the cached files were moved after they were written or if the process trying to access the data does not have access to the files. The latter could easily happen in a misconfigured container orchestration.
Following this change, if you perform a successful scan but then manually destroy, move, or make unreadable its cached files, the next time you try to download the report, you should encounter a 500 Internal Server Error. Returning a 500 error is appropriate here because there is nothing the client can do to fix the issue, and it requires some investigation and …
=> fix: fail bigger when failing to access DeploymentsReport cached_fingerprints or cached_csv

quipucords/fingerprinter/runner.py, quipucords/tests/fingerprinter/test_runner.py, quipucords/tests/utils/raw_facts_generator.py
This is a followup to https://github.com/quipucords/quipucords/pull/2685 which only added `hostnamectl` to fact collection but did not yet use its values in fingerprinting.
=> feat: use hostnamectl to fingerprint infrastructure_type

quipucords/fingerprinter/runner.py, quipucords/scanner/network/normalizer.py, quipucords/tests/fingerprinter/test_fingerprint_task.py, quipucords/tests/scanner/network/test_normalizer.py, quipucords/tests/utils/raw_facts_generator.py
When we refactored and removed the old virt_what_type fact from Ansible in 325b23db, we forgot that the old code invented the "bare metal" response, and virt-what never actually emits that value. So, this code became unreachable and useless.
Relates to JIRA: DISCOVERY-427
=> refactor: remove unreachable code

quipucords/api/reports/model.py, quipucords/api/scanjob/model.py, quipucords/fingerprinter/runner.py, quipucords/scanner/runner.py
This resolves a race condition when running quipucords with Celery enabled and running parallel scan tasks for multiple sources in the same scan job could result in one task prematurely deleting the results from the other task which would later crash the fingerprint logic.
See Slack discussion here for additional context and partial reproduction steps: https://redhat-internal.slack.com/archives/C02QSNF1UKE/p1720472739484699
> I hit an unexpected error a few minutes ago when I was trying to run a multi-source scan containing 1 network, 1 ansible, 1 openshift, 1 vcenter, and 1 satellite source. Scanning each source individually beforehand worked just fine, but scanning them all together crashed out during fingerprinting. When I removed the ansible source from the group, the combined scan …
=> fix: delete InspectResults only related to the current task

quipucords/api/scanjob/model.py, quipucords/api/scantask/model.py, quipucords/api/user/authentication.py, quipucords/api/user/token_view.py, quipucords/quipucords/settings.py, quipucords/scanner/vcenter/inspect.py, quipucords/tests/api/credential/test_credential.py, quipucords/tests/api/credential/test_serializer.py, quipucords/tests/api/scan/test_scan.py, quipucords/tests/api/scanjob/test_scanjob.py, quipucords/tests/api/source/test_source.py, quipucords/tests/factories.py, quipucords/tests/scanner/vcenter/test_vc_inspect.py
and replace deprecated datetime.datetime.utcnow, which is what prompted this change:
> DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
=> refactor: enable timezone-aware datetimes everywhere

quipucords/fingerprinter/runner.py, quipucords/scanner/ansible/connect.py, quipucords/scanner/ansible/inspect.py, quipucords/scanner/network/connect.py, quipucords/scanner/network/inspect.py, quipucords/scanner/openshift/runner.py, quipucords/scanner/rhacs/connect.py, quipucords/scanner/rhacs/inspect.py, quipucords/scanner/runner.py, quipucords/scanner/satellite/runner.py, quipucords/scanner/vcenter/connect.py, quipucords/scanner/vcenter/inspect.py
This ScanTaskRunner method was useful when quipucords supported pausing and resuming scans, but since we removed the pause/resume functionality, there should be no partial data to clean up, and these old methods and properties are now useless.
=> refactor: remove unnecessary cleanup_unsupported_partial_results and supports_partial_results

quipucords/scanner/manager.py
JOB_TERMINATE_CANCEL is not normally a valid/expected value for ScanJob.status. That pseudo-constant is intended to be used as a multiprocessing signal value to be sent when cancelling jobs in the old thread-based manager, not to be stored as a persistent status. When JOB_TERMINATE_CANCEL was set as the status, the UI would incorrectly show the "working" spinner graphic and still show the "stop" cancel button, implying that the job was actually still running. The backend server would also emit this seemingly nonsensical warning:
Cannot change job state to canceled when it is 2
This bug was introduced in 5bae95cd1 and only affects the Celery-based scan manager.
=> fix: remove erroneous ScanJob.status assignment

deploy/entrypoint_web.sh, deploy/gunicorn_conf.py, docker-compose.yml
When running discovery behind nginx and/or HA proxy, there's no need to have HTTPS turned on. The proxy should be the one handling the certificates.
=> feature: conditionally disable https

docs/sudo_cmd_list.txt, quipucords/scanner/network/runner/roles/check_dependencies/tasks/main.yml, quipucords/scanner/network/runner/roles/cloud_provider/tasks/main.yml, quipucords/scanner/network/runner/roles/cpu/tasks/main.yml, quipucords/scanner/network/runner/roles/date/tasks/main.yml, quipucords/scanner/network/runner/roles/dmi/tasks/main.yml, quipucords/scanner/network/runner/roles/ifconfig/tasks/main.yml, quipucords/scanner/network/runner/roles/installed_products/tasks/main.yml, quipucords/scanner/network/runner/roles/ip/tasks/main.yml, quipucords/scanner/network/runner/roles/jboss_eap/tasks/main.yml, quipucords/scanner/network/runner/roles/jboss_fuse_on_karaf/tasks/main.yml, quipucords/scanner/network/runner/roles/jboss_ws/tasks/main.yml, quipucords/scanner/network/runner/roles/redhat_packages/tasks/main.yml, quipucords/scanner/network/runner/roles/redhat_release/tasks/main.yml, quipucords/scanner/network/runner/roles/virt/tasks/main.yml, quipucords/tests/integration/test_network_scan.py, quipucords/tests/scanner/network/test_inspect_callback.py
The main point of the PR is:
* use `command -v` consistently inside `check_dependencies` role
* use bare executable names in all roles
A bit historical context: this fundamentally follows up to #1298 and #1309 . The main problem is that we want to run some roles conditionally (only if required tools are found), but sometimes we run roles as root and sometimes we do not. The attempt to solve it was to use hardcoded absolute paths, but this created the new issue that host might have the tool under different path. The core insight in this PR is that we should split dependencies check into root and non-root check, and then trust the path to find the right executable.
Each ansible variable is changed in separate commit. I will squash them before merging, I just thought it might be easier to …
=> DISCOVERY-419: use bare executable names in roles

quipucords/scanner/network/connect.py
Thanks @mirekdlugosz for spotting this!
Caused by bff7ee94
Relates to JIRA: DISCOVERY-723
=> fix: network connect timeout should multiply by number of ips in the current group, not the number of groups

docs/swagger.yml
Relates to JIRA: DISCOVERY-680
While debugging scans functionality on the UI, noticed scans/bulk_delete/ wa snot documented on the api spec.
=> docs: add /scans/bulk_delete/ to api spec

quipucords/api/aggregate_report/model.py, quipucords/api/reports/reports_gzip_renderer.py, quipucords/api/reports/view.py, quipucords/tests/api/aggregate_report/test_aggregate_report_model.py, quipucords/tests/api/reports/test_reports.py, quipucords/tests/constants.py
Also, reformat an AggregateReport into a slightly more readable dict. The JSON now contains two top-level keys `results` and `diagnostics` with all the previous keys sorted into one or the other.
Example output:
```json
{
"results": {
"ansible_hosts_all": 0,
"ansible_hosts_in_database": 0,
"ansible_hosts_in_jobs": 0,
"instances_hypervisor": 0,
"instances_not_redhat": 1,
"instances_physical": 0,
"instances_unknown": 1,
"instances_virtual": 3,
"jboss_eap_cores_physical": 0,
"jboss_eap_cores_virtual": 1.0,
"jboss_eap_instances": 1,
"jboss_ws_cores_physical": 0,
"jboss_ws_cores_virtual": 0,
"jboss_ws_instances": 0,
"openshift_cores": 0,
"openshift_operators_by_name": {},
"openshift_operators_by_kind": {},
"os_by_name_and_version": {
"Linux": {
"6.1.92-99.174.amzn2023.aarch64": 1
},
"Red Hat …
```
=> feat: add aggregate report to reports tarball

docs/sudo_cmd_list.txt, quipucords/scanner/network/processing/jws.py, quipucords/scanner/network/runner/roles/jboss_ws/tasks/main.yml, quipucords/scanner/network/runner/roles/redhat_packages/tasks/main.yml
What does `-C` do here? From the `man yum` page:
-C, --cacheonly
Run entirely from system cache, don't update the cache and use
it even in case it is expired.
DNF  uses a separate cache for each user under which it executes.
The cache for the root user is called the system cache. This switch
allows a regular user read-only access to the system cache, which
usually is more fresh than the user's and thus he does not have to
wait for metadata sync.
Specifically, we are interested in the "don't update the cache" part because pulling updates from the remote repos could be slow or impossible, and we don't need those updates anyway. Whatever is already present on the local system should be good enough for us.
See also this discussion: https://redhat-internal.slack.com/archives/C06CZ28NRHT/p172546 …
=> fix: send "-C" arg to `yum` to avoid slow cache updates

conftest.py, quipucords/api/signal/scanjob_signal.py, quipucords/quipucords/wsgi.py, quipucords/scanner/manager.py, quipucords/tests/api/merge_report/test_async_merge_report.py, quipucords/tests/api/reports/test_reports.py, quipucords/tests/api/scan/test_scan_bulk_delete.py, quipucords/tests/api/source/test_source_bulk_delete.py, quipucords/tests/integration/test_ansible_scan.py, quipucords/tests/integration/test_openshift_scan.py, quipucords/tests/integration/test_rhacs_scan.py, quipucords/tests/integration/test_smoker.py, quipucords/tests/scanner/job/test_job_celery_based.py, quipucords/tests/scanner/satellite/test_sat_six.py, quipucords/tests/test_celery_scan_manager.py
In another step towards getting rid of the ScanManager, remove the global manager, and the need to create a single class instance. Celery doesn't need these things.
Also, remove scan_manager fixture. From now on, tests relying on celery shall either use celery_app/celery_worker fixtures or enable CELERY_TASK_ALWAYS_EAGER.
=> chore(ScanManager): remove fluff celery don't need

quipucords/api/credential/serializer.py, quipucords/tests/api/credential/test_credential.py, quipucords/tests/api/credential/test_serializer.py
Example API responses showing the new `auth_type` field:
```sh
http 127.0.0.1:8000/api/v1/credentials/ Authorization:"Token $API_TOKEN" page_size==2 page==8
```
```json
{
"count": 23,
"next": "http://127.0.0.1:8000/api/v1/credentials/?page=9&page_size=2",
"previous": "http://127.0.0.1:8000/api/v1/credentials/?page=7&page_size=2",
"results": [
{
"auth_type": "password",
"created_at": "2024-09-16T18:39:23.329554Z",
"cred_type": "vcenter",
"id": 27823,
"name": "b2ebca84-f592-43ef-8f90-98c3e2910046",
"password": "********",
"updated_at": "2024-09-16T18:39:24.941053Z",
"username": "87a46b00-da1e-43bc-b8fc-87371861c611"
},
{
"auth_type": "ssh_keyfile",
"become_method": "sudo",
"become_user": "root",
"created_at": "2024-09-16T18:39:53.259351Z",
"cred_type": "network",
"id": 27829,
"name": …
```
=> feat: add "auth_type" to credentials api

quipucords/quipucords/user.py, quipucords/tests/quipucords/test_user.py
We use `secrets.token_hex()` to generate a random password for user. Our default password policy specifies that passwords can't contain only numeric characters.
`token_hex()` returns string that contains hexadecimal numbers, so it may contain numeric characters by pure chance. The default upstream function output length is 20 characters, and testing showed that you need to generate about 12 000 passwords before you get one that contains numbers only.
However, we also decided to generate passwords of minimum length allowed by password policy (upstream 10 characters). In such setup, you needed only about 100 passwords before you got one that contains only numbers.
That was the root cause of intermittent failures in CI. Technically the issue is not fixed yet, but should be exceedingly rare.
=> chore: Use full token generated by secrets lib

CONTRIBUTING.md, Dockerfile, quipucords/quipucords/settings.py, quipucords/tests/scanner/network/processing/test_hostnamectl.py, quipucords/utils/debugger.py
- get rid of more docker references
- don't enable debugpy in "production" mode
- add QUIPUCORDS_ prefix to PRODUCTION env var
=> chore: do not enable debugpy in production mode

quipucords/scanner/network/connect.py, quipucords/scanner/network/utils.py, quipucords/tests/scanner/network/test_network_connect.py
This resolves a longstanding issue where the UI would present an apparent success status for a network-type connection scan even if all of the hosts in the source were unreachable. Previously, we would only fail if an individual ansible run (hosts are split into groups, and run is invoked once for each group) returned an edge-case final status like "timeout".
Relates to JIRA: DISCOVERY-823
=> fix: connect scan should fail if no hosts are reachable

quipucords/api/common/util.py, quipucords/fingerprinter/formatters.py, quipucords/fingerprinter/runner.py, quipucords/scanner/network/normalizer.py, quipucords/scanner/normalizer.py, quipucords/tests/fingerprinter/test_fingerprint_task.py, quipucords/tests/fingerprinter/test_formatters.py, quipucords/tests/integration/test_network_scan.py, quipucords/tests/utils/raw_facts_generator.py
Explicit is better than implicit. This should fix a RIDICULOUS bug that caused os_version "8.10" to become "8.1".
For the record, type coercions were all based on SystemFingerprint fields as follows:
Integer fields:
- cpu_count
- cpu_socket_count
- cpu_core_per_socket
- system_user_count
- vm_host_socket_count
- vm_host_core_count
- redhat_package_count
- system_memory_bytes
Float fields:
- cpu_core_count
Boolean fields:
- cpu_hyperthreading
- is_redhat
Relates to JIRA: DISCOVERY-783
=> refactor(fingerprinter): make all type coercions EXPLICIT

quipucords/api/credential/serializer.py, quipucords/tests/api/credential/test_serializer.py
Username is mandatory field for network credentials, no matter if you authenticate with password or SSH key. We correctly rejected new credentials without username, but allowed PATCH requests that would set username to empty string.
Also, add unit tests for network / openshift / ansible credentials; the scenario covers editing credential to set name / username / password to empty string. Right now backend still allows to set network credential password to empty string - we discussed that on Slack and decided to not mess with complex internals for now. See also [DISCOVERY-860](https://issues.redhat.com/browse/DISCOVERY-860) for a number of scenarios we should eventually support.
=> fix(serializers): reject empty username on editing

Dockerfile
After https://github.com/quipucords/quipucords-ui/pull/525 merged, quipucords image builds started failing because quipucords is not designed for the "new" UI code. This change TEMPORARILY pins the previous stable UI tag while we finish the rollout of the new UI code.
Relates to JIRA: DISCOVERY-867
Relates to JIRA: DISCOVERY-868
=> build: include old UI version with the container *TEMPORARILY*

Dockerfile, Makefile, quipucords/quipucords/settings.py, quipucords/quipucords/urls.py
With the new and standalone UI released we can finally get rid of UI views, templates, js, css and other static files from that UI.
With this change, Django development server can FINALLY run in true standalone mode, without the argument --nostatic.
Please remember to remove these unneeded files from local storage:
```
rm -rf quipucords/client
rm -rf quipucords/quipucords/templates
rm -rf quipucords/staticfiles
```
~~EDIT: This PR removes Django admin and adds an autogenerated schema view (mostly for v2 endpoints).~~
Relates to JIRA: DISCOVERY-777
~~Relates to JIRA: DISCOVERY-726~~
=> chore: get rid of the deprecated legacy UI views

quipucords/api/scanjob/model.py, quipucords/api/scantask/model.py, quipucords/api/source/model.py, quipucords/scanner/job.py, quipucords/tests/api/scanjob/test_scanjob.py, quipucords/tests/api/scantask/test_scantask.py, quipucords/tests/api/source/test_source.py, quipucords/tests/scanner/job/test_run_task_runner.py
This should resolve some issues where a scan job would appear to be stuck running forever (spinner graphic in web UI) despite its task having already failed and having no other activity.
This PR also includes an unrelated commit that adds basic `__str__` method to several of our model classes to aid future issue investigation and debugging. For example `ScanTask object (27188)` becomes `ScanTask(id=27188, scan_type=connect, status=failed, job_id=25735, sequence_number=1)`.
Relates to JIRA: DISCOVERY-800
Relates to JIRA: DISCOVERY-838
=> fix: set job status to FAILED when its task fails

quipucords/api/credential/model.py, quipucords/constants.py, quipucords/scanner/network/connect.py, quipucords/scanner/network/inspect.py, quipucords/scanner/network/utils.py, quipucords/tests/api/credential/test_credential.py, quipucords/tests/api/credential/test_credential_model.py, quipucords/tests/factories.py, quipucords/tests/scanner/network/test_network_connect.py, quipucords/tests/scanner/network/test_network_inspect.py
Temporary SSH keyfiles were being prematurely deleted under certain conditions.
To fix the issue, the whole architecture of how temporary SSH key files were managed was modified. Now, they have a dedicated context manager that should delete them. Ansible runner MUST run nested on these dedicated contexts.
Relates to JIRA: DISCOVERY-890
Relates to JIRA: DISCOVERY-894
=> fix: patch a misshandle on ssh keyfiles

quipucords/api/deployments_report/model.py, quipucords/api/deployments_report/tasks.py, quipucords/api/deployments_report/view.py, quipucords/api/management/commands/regenerate_missing_report_cache_files.py, quipucords/api/scanjob/model.py, quipucords/fingerprinter/runner.py, quipucords/quipucords/celery.py, quipucords/tests/api/deployments_report/test_deployments_report.py, quipucords/tests/api/deployments_report/test_tasks.py, quipucords/tests/scanner/job/test_job_celery_based.py, quipucords/tests/utils/test_is_valid_cache_file.py, quipucords/utils/misc.py
This change automatically recreates files in the `cached_reports` directory if they are missing when any report download that needs them is requested. The initial download request may immediately return an error message (we should consider making the UI handle this more gracefully), but if you wait a few seconds for a newly spawned async task to complete and then try the download again, you should get the completed report. This works for operations in the UI and the CLI.
Additionally, this change adds a management command `regenerate_missing_report_cache_files` that attempts to identify and fix all missing `cached_reports` files. Running this command still uses Celery tasks. So, be sure you have Celery workers running when you call it or else it will hang forever while it waits for Celery …
=> feature: regenerate cached fingerprint and cached csv if missing when requested

Containerfile
One of Red Hat Enterprise Contract rules enforces that the default user in container images SHOULD NOT be root (0).
This PR will fail on camayoc until quipucords/quipucords-installer#48 is merged.
Relates to JIRA: DISCOVERY-708
=> chore: set quipucords uid=1001

codecov.yml
I _feel like_ quipucords used to have non-default codecov configs somewhere, probably in codecov's web interface, and I _suspect_ those might have just disappeared some time ago when they upgraded their system (likely when they changed token use requirements).  🤷  Regardless, we should set our own config with the repo for complete visibility.
This config basically says:
* For the diff, require 80% coverage to pass the PR check.
* For the overall project, target the previous/parent commit's recorded coverage, but allow it to dip by 5% before it fails the PR check.
* The "range" value is purely aesthetic, IIUC. Files under 70% show as red, under 90% as yellow, and over 90% as green when viewed on codecov's website.
=> refactor: add codecov.yml config to override defaults

quipucords/api/deployments_report/model.py, quipucords/api/deployments_report/tasks.py, quipucords/api/deployments_report/view.py, quipucords/api/management/commands/regenerate_missing_report_cache_files.py, quipucords/tests/api/deployments_report/test_deployments_report.py, quipucords/tests/api/deployments_report/test_tasks.py, quipucords/tests/scanner/job/test_job_celery_based.py
This change significantly simplifies the feature originally added in https://github.com/quipucords/quipucords/pull/2793 that (re)generates missing cached fingerprint files. Instead of running a whole fingerprint-type `ScanTask` as in the original implementation, now we simply look for the related `SystemFingerprint` objects and save their serialized contents. I previously just missed the fact that `SystemFingerprint` objects exist with _effectively_ the full contents of the `cached_fingerprint` field.
Quoting an explanation I [originally posted here in Slack](https://redhat-internal.slack.com/archives/C02QSNF1UKE/p1740426777485639?thread_ts=1740411522.844759&cid=C02QSNF1UKE):
> …the idea for my manual verification so far has been:
>
> * create a new network source, scan it, and download …
=> fix: unexpected report count inflation caused by regenerating missing cache files

.tekton/discovery-server-pull-request.yaml, .tekton/discovery-server-push.yaml, .tekton/task/generate-version-labels.yaml
Dynamically create "version" and "version_minor" labels based on pyproject.toml
version. These labels are expected on downstream `ReleasePlanAdmission`.
Relates to JIRA: DISCOVERY-708
=> ci(konflux): dynamically set version labels

Containerfile, Makefile, README.md, lockfiles/rpms.lock.yaml, rpms.in.yaml
The necessity of locking RPM dependencies forced us to repeat them both on `Containerfile` and `rpms.in.yaml`.
This PR changes that.
- DRY: parse rpm dependencies from the now obligatory "rpms.in.yaml"
file; since we are now forced to track our dependencies on
rpms.in.yaml, no need to actually repeat it on the Containerfile
- Move `rpms.in.yaml` from `lockfiles` folder to make it clear it is NOT
an automatically managed file.
- Create a dedicated builder stage on our Containerfile. This makes
cleaning up build dependencies easier. Right now this might seem
overkill, but in a subsequent PR rust transitive dependencies will
be included and this will help on cleanup.
=> build: DRY rpm dependencies

.github/workflows/build-arm64.yml
[last `build-arm64` run from `main`](https://github.com/quipucords/quipucords/actions/runs/13845360122): `19m 30s` 
[latest `build-arm64` run from this branch](https://github.com/quipucords/quipucords/actions/runs/13902784235/job/38898458182?pr=2856): `5m 33s`
[last `build` (`x86_64`) run from `main`](https://github.com/quipucords/quipucords/actions/runs/13845360123): `3m 18s`
So, it's not _as fast_ as the pure `x86_64` build job, but it seems much better than the CPU emulated one. Hopefully it will get faster over time as GitHub rolls out more and faster `arm64`/`aarch64` workers.
=> build: update base image for github arm64 job

quipucords/api/scanjob/model.py, quipucords/scanner/job.py, quipucords/scanner/satellite/api.py, quipucords/scanner/satellite/six.py, quipucords/tests/scanner/satellite/test_sat_six.py
Before this change, standalone scans for each type (Satellite, network, etc.) all worked fine in isolation. However, if you created a scan with multiple types of sources, and one of those types included Satellite which recently stopped using connect scan tasks, the overall scan would fail because the task models had an inconsistent API across different source types. That problem was introduced in b4999fde72c35b1d0712b529d2f6b92ac0ff12bf via <https://github.com/quipucords/quipucords/pull/2845>.
This change restores the use of connect scan tasks for Satellite to preserve the old internal interface as still used by other source types. The restored use of the connect scan task is only superficial, though, and all "connect" logic for Satellite has still been moved out of its old connect task …
=> fix: restore connect task for satellite to fix broken multi-type scans

quipucords/api/scanjob/view.py
This will aid qpc to decide if insights report should be downloaded.
The report itself does not know what sources were used to create it, and qpc users can run `qpc report insights --report ID` to download report directly. If we want to tell user that maybe insights report does not exist for this particular report, then we need to obtain scan / scanjob that was used to create a report. And without this patch there's no easy way to get scan / scanjob data if you only have report id.
With that patch, you can filter scanjobs by related report id.
Relates to JIRA: DISCOVERY-791
=> feat: Allow listing scanjobs by related report id

quipucords/quipucords/settings.py
When creating `secret.txt` file, chmod it to 600 (owner read write, no permissions for group or others). Permissions of existing file are not modified.
Relates to JIRA: DISCOVERY-928
=> fix(settings): Limit permissions of locally stored secret.txt

quipucords/scanner/satellite/six.py, quipucords/scanner/satellite/utils.py, quipucords/tests/scanner/satellite/test_sat_utils.py
Also some minor cleanup following https://github.com/quipucords/quipucords/pull/2899. See individual commit messages for details.
=> fix: gracefully handle mismatch in Satellite inspection counts

.tekton/discovery-server-pull-request.yaml, .tekton/discovery-server-push.yaml, CONTRIBUTING.md, Makefile, lockfiles/requirements-build.txt, lockfiles/requirements.txt, lockfiles/rpms.lock.yaml, pyproject.toml, uv.lock
Add another lockfile related make target. This time to help patching konflux pipelines.
Also use this target to update konflux task references.
=> build: yet another lockfile target

.github/workflows/build.yml
See this conversation for context:
https://redhat-internal.slack.com/archives/C02QSNF1UKE/p1746208791358419
TLDR: I discovered that we are pushing the combined manifest for `latest` but not for `main`, `latest` basically aliases the `main` tag, and nothing we know currently uses `main`. So, drop `main` and keep `latest`.
=> build: stop pushing `main` container tags (but continue pushing `latest`)

.tekton/discovery-server-pull-request.yaml, .tekton/discovery-server-push.yaml, .tekton/task/generate-version-labels.yaml, Containerfile, lockfiles/artifacts.lock.yaml, lockfiles/requirements-build.txt, lockfiles/requirements.txt, lockfiles/rpms.lock.yaml, pyproject.toml, uv.lock
Since the uv migration the labeling required for releasing downstream is broken. This PR fixes that.
NOTICE: this is also bumping quipucords to 1.14.1 and refreshing all locks. A commit per commit review is advised.
=> ci(konflux): fail if the labels are not in the required format

quipucords/api/common/common_report.py, quipucords/api/common/util.py, quipucords/api/report/reports_gzip_renderer.py, quipucords/tests/api/common/test_common_util.py, quipucords/tests/api/report/test_reports.py, quipucords/tests/constants.py, quipucords/tests/integration/test_smoker.py
This should help users who are manually processing files from multiple report directories. That use case came to us as a specific feature request from an end user.
Upon expanding a report tarball download, the contents should now look like this example:
```
report_id_18578
├── aggregate-18578.json
├── deployments-18578.csv
├── deployments-18578.json
├── details-18578.csv
├── details-18578.json
├── scan-job-18137-ansible-stderr-18578.txt
├── scan-job-18137-ansible-stdout-18578.txt
└── SHA256SUM
```
In this example, the `-18578` suffix is newly added to the various filenames, and that value is the same as the report ID used in the parent directory's name and the downloaded tarball filename. However, please also note that the numeric values in the *middle* of the `ansible` logs filenames, …
=> feat: add report ID to each JSON and CSV filename in downloaded tarball

quipucords/api/aggregate_report/model.py, quipucords/tests/api/aggregate_report/test_aggregate_report_model.py
We had a bug where downloading a report tarball multiple times would result in some aggregate report numbers doubling the second time you performed the download. The root cause is related to cached details and deployments report files being written to disk at the time of the download. Writing those files to disk causes their models' updated_at field to update, but an aggregate report model instance was already created during the tail end of the scan (fingerprinting task, I think). Subsequent attempts to retrieve the aggregate report would compare updated_at values, find that the aggregate report is "older" than the related report objects, and attempt to recalculate the aggregate report contents. However, because aggregate report data already existed, that "recalculation" began with the …
=> fix: destroy and create new aggregate report model; never update it
